### ISSUE TITLE
Enhancement idea

### ISSUE THREAD

**Issue by matb33** [DiscoverMeteor/book#1]
Just throwing it out there, feel free to ignore: When you are showing blocks of example code being run in browser, then in server console, perhaps the styling for each could match a typical browser console and terminal window respectively (light vs dark perhaps?). This would help the reader understand the context more easily without having to read/absorb the footer note -- less cognitive overhead

For example, the Collections section has a few of these: http://book.discovermeteor.com/chapter/collections/

**Comment by tmeasday** [comment]
This is a great idea Mathieu!

**Comment by SachaG** [comment]
Done :)
