### ISSUE TITLE
Commit 10-5 - Add code sample

### ISSUE THREAD

**Issue by brotherbill** [DiscoverMeteor/book#109]
You wrote: "Finally, we can just simply remove the commentsCount helper from client/views/posts/post_item.js, as the field is now directly available on the post."

But there is no code sample with distinctive background color, and path/filename.
I'm sorry, but this went right by me, until I did a search for post_item on that page, and found the above directive to remove the commentsCount method from post_item.js.

So it IS there, but for consistency, and since post_item.js is so short, I recommend displaying the new contents of post_item.coffee, without the commentsCount function.

Please keep your directive.  Just show the new code for post_item.js immediately below it.

**Comment by SachaG** [comment]
I see your point, and it's a bit tricky because it's the only point in the book where we're actually deleting code. But I'm not sure I want to add the `post_item.js` code again. I will close that issue for now, and if anybody else is confused by this I'll try to think of a better way.
