### ISSUE TITLE
What happened to {{postsListPath}} in the header?

### ISSUE THREAD

**Issue by GiraffeSlacks** [DiscoverMeteor/book#11]
Hi,

On http://book.discovermeteor.com/chapter/creating-posts/ header.html is no longer using {{postsListPath}} and has reverted to just '/'. I haven't recorded all other pages where this happens but I'm going through the book a second time and I believe it stays this way for the rest of the book IIRC.

**Comment by SachaG** [comment]
That was a mistake, we've fixed it.
