### ISSUE TITLE
Commit 11-1 Replace existing Comments.insert

### ISSUE THREAD

**Issue by brotherbill** [DiscoverMeteor/book#110]
Since the code sample for collections/comments.js is partial (has ...), make it clear that we are replacing a naked Comments.insert(comment) with one that accepts its return value, and then add createCommentNotification.

I made this mistake, and then figured it out.
Otherwise, the new Comment gets inserted TWICE.

**Comment by SachaG** [comment]
I think in these cases, the best way is to check the file on GitHub to make sure what's getting added and/or replaced.
