### ISSUE TITLE
Add details to deploy sidebar

### ISSUE THREAD

**Issue by paulmolluzzo** [DiscoverMeteor/book#115]
In the sidebar chapter you briefly mention deploying to Meteor on your own domain, but there are additional directions that you may want to include describing how to allow an app to be available on your own domain with _and without_ the `www.` subdomain.

The quick background is: An application deployed using `meteor deploy www.myapp.com` will only be available using the `www.` subdomain, and similarly, using `meteor deploy myapp.com` doesn't handle connections from the `www.` subdomain. In fact, running both commands will create two separate instances of the application that are not connected. Further, CNAME records can't (or at least shouldn't) be attached to the naked domain.

The solution I've found is to deploy to the `www.` subdomain and point the naked domain to the subdomain using a 301 redirect.

Steps:
1. Have/acquire some sort of hosting where you can upload an .htaccess file for the naked domain, and point (at least) the naked domain to that hosting service.
2. In the `html` folder on that naked domain's hosting, upload a .htaccess file with the 301 redirect snippet below.
3. Following the Meteor directions run `meteor deploy www.domain.com`.
4. Also following the directions, point the CNAME for the `www.` subdomain to `origin.meteor.com`

.htaccess Snippet:

```
Redirect 301 / http://www.domain.com/
```

EDIT: I should add the expected result. If this is done correctly navigating to the `www.` subdomain should behave exactly the same, and navigating to the naked domain will redirect. What a User would notice is that the URL is updated in the browser to prepend the subdomain. The directory path (i.e. domain.com/pathname) remains intact through the redirect and the app's routing should work as usual.

NB - Doing this process inversed — i.e. pointing the `www.` to the naked domain and pointing deploying on http://domain.com — is possible if you use an A record that points to the Meteor server at 107.22.210.133 but it's not advised since a change in that IP address will down your entire application.

**Comment by SachaG** [comment]
Thanks for the details! We're currently reworking the deployment chapter, we'll try to fit this in :)

**Comment by SachaG** [comment]
Actually, I would suggest writing this up in a blog post of your own. We'll be happy to tweet/link to it :)
