### ISSUE TITLE
Advanced Publications topic

### ISSUE THREAD

**Issue by geekyme** [DiscoverMeteor/book#116]
Hi, 

I'm on the chapter and topic about multiple collections per publication. I've having a hard time understanding how this resulted in publishing multiple collections in one go: 

<pre>

Meteor.publish('topPosts', function(limit) {
  var sub = this, commentHandles = [], postHandle = nil;

  // send over the top two comments attached to a single post
  function publishPostComments(post) {
    var comments = Comments.find({postId: post._id}, {limit: 2});
    commentHandles[post._id] = comments.observe({
      added: function(id, comment) {
        sub.added('comments', id, comment);
      }
      // etc, see _publishCursor (in the Meteor core source code) for hints
    });
  }

  postHandle = Posts.find({}, {limit: limit}).observe({
    added: function(id, post) {
      publishPostComments(post);
      sub.added('posts', id, post);
    },
    removed: function(id) {
      // stop observing changes on the post's comments
      commentHandles[id] && commentHandles[id].stop();
      // delete the post
      sub.removed('posts', id, _.keys(oldPost));
    }
    // etc, see _publishCursor for hints
  });

  sub.ready();

  // make sure we clean everything up
  sub.onStop(function() {
    postsHandle.stop();
    commentsHandle.stop();
  });
});

</pre>

Can anyone help to explain how the above works? 

Alternatively, I browsed the docs (http://docs.meteor.com/#meteor_publish) and found the below. Could it work too?

<pre>
// publish dependent documents and simulate joins
Meteor.publish("roomAndMessages", function (roomId) {
  check(roomId, String);
  return [
    Rooms.find({_id: roomId}, {fields: {secretInfo: 0}}),
    Messages.find({roomId: roomId})
  ];
});
</pre>

**Comment by tmeasday** [comment]
Hi Shawn,

I think you first question is probably better asked on the Meteor talk mailing list or within the Disqus comments attached to the advanced publications chapter. We try to just deal with problems people find in the book here.

To answer your second point, the issue that the first method is trying to solve is when you want to publish _more than one room_ and all the associated messages. In that case there's no simple cursor that you can create which matches the relevant messages.
