### ISSUE TITLE
Deploy to Heroku APPLICATION ERROR - Meteor requires.....

### ISSUE THREAD

**Issue by benstr** [DiscoverMeteor/book#117]
If you deploy to Heroku with your specified build package you also need to create a new file in the app root `package.json` and fill it up with:

```
{
  "name": "Whatever",
  "version": "0.0.1",
  "engines": {
    "node": "0.8.24"
  }
}
```

http://stackoverflow.com/questions/18253014/buildpack-for-meteor-0-6-5/18284238#18284238

**Comment by tmeasday** [comment]
Hey,

We don't advise using Heroku for Meteor deployment any more as it's not a scalable solution. We'd recommend Modulous for a similar solution these days. 

You can check out the updated deployment chapter for more details.

Cheers,
