### ISSUE TITLE
mrt add router still not working

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#118]
Hello there,

when doing "mrt add router" it raises an error and "mrt add router --repoPort 443" does it too: 

---

✓ router
    tag: https://github.com/tmeasday/meteor-router.git#v0.5.4.1

/usr/local/lib/node_modules/meteorite/lib/sources/git.js:108
        throw "There was a problem cloning repo: " + self.url;
                                                   ^
There was a problem cloning repo: https://github.com/tmeasday/meteor-router.git

---

How can I fix this ? Thanks a lot!

**Comment by tmeasday** [comment]
Hey @jodu38 -- can you try `mrt uninstall --system` and try again?

**Comment by ghost** [comment]
Thank you @tmeasday!!

{ problem : "solved" }
