### ISSUE TITLE
Issues running metoer

### ISSUE THREAD

**Issue by dcrunch** [DiscoverMeteor/book#119]
I have been building app in the book.I just upgraded to 0.6.6 version of meteor and now I am having issues running meteor.
Error message comes up regarding 'router' package. Is source code compaitble with latest version of meteor.

router: updating npm dependencies -- connect...
npm WARN using --force I sure hope you know what you are doing.
npm WARN package.json packages-for-meteor-smartpackage-router@0.0.0 No description
npm WARN package.json packages-for-meteor-smartpackage-router@0.0.0 No repository field.
npm WARN package.json packages-for-meteor-smartpackage-router@0.0.0 No README data
npm http GET https://registry.npmjs.org/connect/2.7.10
npm http GET https://registry.npmjs.org/connect/2.7.10
npm http GET https://registry.npmjs.org/connect/2.7.10
npm http GET https://registry.npmjs.org/connect/-/connect-2.7.10.tgz
npm ERR! fetch failed https://registry.npmjs.org/connect/-/connect-2.7.10.tgz
npm http GET https://registry.npmjs.org/connect/-/connect-2.7.10.tgz
npm ERR! fetch failed https://registry.npmjs.org/connect/-/connect-2.7.10.tgz
npm http GET https://registry.npmjs.org/connect/-/connect-2.7.10.tgz
npm ERR! fetch failed https://registry.npmjs.org/connect/-/connect-2.7.10.tgz
npm ERR! Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR!     at SecurePair.<anonymous> (tls.js:1356:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:968:10)
npm ERR!     at CleartextStream.read [as _read](tls.js:462:15)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write](tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:221:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:211:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 12.4.1
npm ERR! command "/Users/atyagi/.meteor/tools/a80b2d5689/bin/node" "/Users/atyagi/.meteor/tools/a80b2d5689/bin/npm" "install" "--force"
npm ERR! cwd /Users/atyagi/.meteorite/packages/router/tmeasday/meteor-router/d00e380dda2184b70e909fc4a0fb5358d602c586/.npm/package-new-16re7ot
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/atyagi/.meteorite/packages/router/tmeasday/meteor-router/d00e380dda2184b70e909fc4a0fb5358d602c586/.npm/package-new-16re7ot/npm-debug.log
npm ERR! not ok code 0

=> Errors prevented startup:

While building package `router`:
error: couldn't install npm packages from npm-shrinkwrap

**Comment by tmeasday** [comment]
Hey @dcrunch,

I don't think there's any problems with the router (or the book in general) and 0.6.6. 

I'm not sure, but it seems like the issue here is installing the connect npm library and some certificate error. Perhaps it was a temporary problem and you should try again?

Also, try running `mrt uninstall --system` to clear out your Meteorite cache and try again.
