### ISSUE TITLE
No upgrade link in members area

### ISSUE THREAD

**Issue by mattcam** [DiscoverMeteor/book#121]
Would like to read the very useful pattern for integrating third-party data into your app which is premium content and there is no upgrade link in members area. I have "Full Edition" package. How do I upgrade?

**Comment by SachaG** [comment]
That's strange. This is what the link should look like: http://cl.ly/S9sf

Is it not appearing for you?

**Comment by mattcam** [comment]
My "full edition" screen grab ![screen shot 2013-10-27 at 10 48 31 pm](https://f.cloud.github.com/assets/3451548/1415389/e826476a-3efd-11e3-8845-1b3f3a96ccd2.png)

**Comment by tmeasday** [comment]
Hey Matt,

This is strange. I don't really know how this can be happening (perhaps there's an error in the JS console?). Sacha is the best person to figure it out.

Anyway, if you are keen to update, you can use this direct link: https://gumroad.com/l/GPah -- make sure you use the same email that you use for your account.

Tom

On 27 Oct 2013, at 10:52 pm, mattcam notifications@github.com wrote:

> My "full edition" screen grab 
> 
> —
> Reply to this email directly or view it on GitHub.

Tom Coleman
Development Lead
http://percolatestudio.com
@tmeasday
+61 409 949 663
