### ISSUE TITLE
Possible spelling issue

### ISSUE THREAD

**Issue by dcrunch** [DiscoverMeteor/book#122]
Please review following code. 
We declare  'postHandle=nil' in first line.
In 'OnStop' handler in the end we use 
postsHandle.stop();

Please notice exta 's' in 'postsHanldle.Stop' while intial variable was 'postHandle'.  (postsHandle vs postHandle). 
Similar case is with commentHandles as well. It is spelled different in 'onStop' handler.  (commentHandles vs commentsHandle)

Also I believe that 'commentsHandle.stop();' in 'OnStop' handler in not right. 
'commentsHandle' is an array and we are calling 'stop' on it which is only available to handler objects in that array and not on array itself. 

Here is code for your reference. 

Meteor.publish('topPosts', function(limit) {
  var sub = this, commentHandles = [], postHandle = nil;

  // send over the top two comments attached to a single post
  function publishPostComments(post) {
    var comments = Comments.find({postId: post._id}, {limit: 2});
    commentHandles[post._id] = comments.observe({
      added: function(id, comment) {
        sub.added('comments', id, comment);
      }
      // etc, see _publishCursor (in the Meteor core source code) for hints
    });
  }

  postHandle = Posts.find({}, {limit: limit}).observe({
    added: function(id, post) {
      publishPostComments(post);
      sub.added('posts', id, post);
    },
    removed: function(id) {
      // stop observing changes on the post's comments
      commentHandles[id] && commentHandles[id].stop();
      // delete the post
      sub.removed('posts', id, _.keys(oldPost));
    }
    // etc, see _publishCursor for hints
  });

  sub.ready();

  // make sure we clean everything up
  sub.onStop(function() {
    postsHandle.stop();
    commentsHandle.stop();
  });
});

**Comment by SachaG** [comment]
Thanks, that code will be fixed in the next version of the book.
