### ISSUE TITLE
11 Notifications instruction update for comments.js

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#123]
It is not clear in 11 Notification to remove or update   "return Comments.insert(comment);" from comments.js in collections

Perhaps I missed the removal earlier, but until I checked every file against the github code base, it was difficult to find the issue.

**Comment by SachaG** [comment]
Thanks, I'll make that clearer. And by the way, you have access to the diffs of every commit on GitHub, which is a great way to quickly check for code changes :)

In this case: https://github.com/DiscoverMeteor/Microscope/commit/7a67b68867f6095b744ce2140e7e0dd78322b3ad
