### ISSUE TITLE
Odd refresh of contents while reading

### ISSUE THREAD

**Issue by physiocoder** [DiscoverMeteor/book#124]
While I'm reading the book in Chrome 30 OsX it happens to refresh cyclycally content. Sometimes leaving a blank page for a second or two.

In particular in chapter "Routing 5" this snippet of code:

```
Meteor.Router.add({
  '/': 'postsList',
  '/posts/:_id': {
    to: 'postPage', 
    and: function(id) { Session.set('currentPostId', id); }
  }
});
```

Gets refreshed inserting and deleting a blank line after `'/': 'postsList',`

Both are distracting and annoying.

**Comment by SachaG** [comment]
Oh, that's super weird. I'll take a look.

**Comment by SachaG** [comment]
It's probably related to our server troubles (working on it now), so I'll close this for now. If it keeps happening let us know!
