### ISSUE TITLE
Re-installing meteor on Mac OS X

### ISSUE THREAD

**Issue by zdusper** [DiscoverMeteor/book#125]
Hi!
I have followed the instructions in the book and came successfully until the user part where problems started. After googling a bit I think I've realised what the problem was, but in the meantime I've created quite a mess because I can not seem to make it work anymore (I get error: no such package: errors all the time, can run meteor only as root etc).

What would be a proper way to go back and install all from scratch (node.js, mongodb, meteor, meteorite, all packages etc)?

**Comment by tmeasday** [comment]
Hi @zdusper  - have you tried following the instructions here: https://github.com/oortcloud/meteorite#permission-woes? 

I can't give much more advice than that beyond perhaps re-installing your computer!
