### ISSUE TITLE
Typo...

### ISSUE THREAD

**Issue by em-gazelle** [DiscoverMeteor/book#129]
A super simple, easy-to-fix typo:

From: http://book.discovermeteor.com/chapter/collections/

$ meteor reset

The reset command completely clears out the Mongo database. It's a useful command in development, where there's a strong possibility of our database falling into a inconsistent state.

Where "a inconsistent" should say "an inconsistent".

P.S. DiscoverMeteor is beautifully written, and is unique in the tech world. Thank you so much for this book!

**Comment by SachaG** [comment]
Thanks for the heads up, and glad you like the book!
