### ISSUE TITLE
main.js inconsistency

### ISSUE THREAD

**Issue by eostrom** [DiscoverMeteor/book#13]
In http://book.discovermeteor.com/chapter/collections/ there's an instruction to add a line to `client/main.js`, but we've never created that file. In the GitHub repo, it's created as part of https://github.com/DiscoverMeteor/Microscope/commit/chapter2-3, but that's not covered in http://book.discovermeteor.com/chapter/getting-started/.

Related: in http://book.discovermeteor.com/chapter/getting-started/ we're told to delete `microscope.html` but not replace it with anything. This breaks the app in the browser until we create `main.html` in http://book.discovermeteor.com/chapter/templates/. In the repo, you create `main.html` as part of "rearranging the file structure," which might keep the app intact.

**Comment by SachaG** [comment]
Good point, we'll make that clearer.
