### ISSUE TITLE
2.5 Deploying to Softlayer server

### ISSUE THREAD

**Issue by kafechew** [DiscoverMeteor/book#130]
Hi,

I had done until the "bundle and untar" successfully.
Now, I'm in trouble in running the app part

“$ sudo PORT=80 MONGO_URL=mongodb://localhost:27017/myapp ROOT_URL=http://myapp.com node bundle/main.js”

Excerpt From: Tom Coleman. “Discover Meteor: Building Real-Time JavaScript Web Apps.” iBooks.  

From the Terminal:

```
root@softlayer:/home# sudo PORT=80 MONGO_URL=mongodb://localhost:27017/cawcah ROOT_URL=http://cawcah.com node bundle/main.js

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRINUSE
    at errnoException (net.js:770:11)
    at Server._listen2 (net.js:910:14)
    at listen (net.js:932:10)
    at Server.listen (net.js:998:5)
    at run (/home/bundle/server/server.js:332:16)
root@softlayer:/home# 
```

Might I know what is the issue? How to solve this?
Thanks!

**Comment by tmeasday** [comment]
Hi - it looks like there's already a server running on port 80 of that machine. Could apache have been pre-installed?

**Comment by kafechew** [comment]
@tmeasday Hi, I had stopped the apache, putting the command back, everything is working fine now! Thanks a lot!
It's live now at http://cawcah.com

**Comment by kafechew** [comment]
@tmeasday @SachaG @DiscoverMeteor If I had updated my code and push into bitbucket... how to sync with my server for new code?

**Comment by tmeasday** [comment]
Hey @kafechew - you can just do `git pull` (on the server), then re-bundle, place it over the top of the old code, and restart the node process.

**Comment by kafechew** [comment]
Hi @tmeasday 

I did that:

```
cd home
cd meteor

git pull

meteor bundle ../bundle.tgz
cd ..
tar -zxvf bundle.tgz
```

Everything is working until here... but the old issue occurred again...

```
root@softlayer:/home# sudo PORT=80 MONGO_URL=mongodb://localhost:27017/cawcah ROOT_URL=http://cawcah.com node bundle/main.js

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRINUSE
    at errnoException (net.js:770:11)
    at Server._listen2 (net.js:910:14)
    at listen (net.js:932:10)
    at Server.listen (net.js:998:5)
    at run (/home/bundle/server/server.js:332:16)
root@softlayer:/home# 
```

What's the issue this time?
Thanks a lot for your help!

**Comment by tmeasday** [comment]
Hey @kafechew -  you need to make sure you kill the old node process before starting a new one.

**Comment by kafechew** [comment]
@tmeasday I'm totally new to terminal, is there any step-by-step guide to teach me kill the old node? Thanks!

**Comment by tmeasday** [comment]
Hey @kafechew - try `killall node`. 

At this point you might want to look into using something like forever to control the running process etc. There's a bunch more that you need to know to effectively run Meteor on your own server (and we are considering releasing some material to help people with that). I think Evented Mind is going to run a track on it too.

**Comment by kafechew** [comment]
Hi @tmeasday 
For sure. I just started learning more and more about Meteor. 
I had finished your book and created an application.
The server side is my problem now...

Go back to the issue, seems like not working yet...

```
root@softlayer:/home# killall node
node: no process found
root@softlayer:/home# 
```

Can you guide me next?
Thanks!

**Comment by tmeasday** [comment]
Maybe try `killall nodejs`.

**Comment by kafechew** [comment]
@tmeasday 
It's working now! 
Thanks a lot! You're the best!

**Comment by kafechew** [comment]
@tmeasday 

Hi again. I think I'm having a great problem in running the Meteor at my server forever.

```
root@softlayer:/home# forever start bundle/main.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: bundle/main.js
root@softlayer:/home# sudo PORT=80 MONGO_URL=mongodb://localhost:27017/cawcah ROOT_URL=http://cawcah.com node bundle/main.js
Write failed: Broken pipe
KafeChew-2:~ kafechew$ 
```

Each time the broken pipe, (always less than a day) the server is down.
How to make sure the Meteor app is online uninterrupted ?
Thanks!

![screen shot 2013-11-17 at 11 48 44 am](https://f.cloud.github.com/assets/1162020/1557777/49a030da-4f3b-11e3-9aef-958f4b136aaf.png)

**Comment by tmeasday** [comment]
Hi @kafechew  - probably you need to figure out how to properly background forever so it keeps running when you close your connection to the server.

Perhaps you should consider hosting your site on meteor.com where things are a lot simpler?

**Comment by kafechew** [comment]
@tmeasday Yes. I wish to. 
But, seems like the new apps built was not loaded at meteor.com server, while immediately loaded at my own server. 

So, I need to figure out how to properly background forever, so it keeps running when I close the connection, just meteor.com server itself.

Do you have any suggestion or guidelines (maybe not yet proven also will do) that relates to this topic?
Thanks a lot!

**Comment by tmeasday** [comment]
Hey @kafechew  - you are probably best just finding a guide to using forever online.

We'll be updating the deployment chapter soon to include a bit more useful information.

**Comment by kafechew** [comment]
Noted with thanks!
