### ISSUE TITLE
Grammar mistake in Routing Chapter

### ISSUE THREAD

**Issue by ayork** [DiscoverMeteor/book#133]
In the chapter on Routing, "The Router gives us a couple of conveniences that _allows_ us to write links that use our routes."

...should read:

"The Router gives us a couple of conveniences that _allow_ us to write links that use our routes."

**Comment by ayork** [comment]
Also, as a new reader of the book I want to join those in the comments in expressing my disappointment that IronRouter is still not used by default. When I read your answer to the question "Will you provide free updates?" on Discover Meteor's front page, I thought I could expect better service.

**Comment by SachaG** [comment]
IronRouter is coming, sorry it's taken us a while!
