### ISSUE TITLE
Edit post displays a blank page rather than the edit form

### ISSUE THREAD

**Issue by redshirtrob** [DiscoverMeteor/book#134]
I'm using the latest HTML version of the book with the Iron Router updates.  When I click on the edit link for one of the posts, the page is blank.

AFAICT, this is because 'currentPostId' is not stored in the Session.  I see where it was once stored in the session:

https://github.com/DiscoverMeteor/Microscope/commit/chapter8-1

But I don't see anything in the current version of the book that stores it in the session.

**Comment by SachaG** [comment]
You're right, that's a mistake on our part. To get it to work just remove the `{{#with}}` tags and the `posts` helper.

**Comment by SachaG** [comment]
OK, so apparently it's a problem with the commit links. The right code is here:

https://github.com/DiscoverMeteor/Microscope/commit/a723ddfed7e8a7117f2c86d0be8c29040e7bc4d4

It seems like the book's link points to an older commit for some reason, I'll ask @tmeasday to investigate.

**Comment by tmeasday** [comment]
Sorry, sorted this one out now.
