### ISSUE TITLE
Log out on code push?

### ISSUE THREAD

**Issue by SachaG** [DiscoverMeteor/book#136]
It seems like pushing a new version of the code logs people out. Anybody can confirm?

**Comment by owenoak** [comment]
Yes, happened to me last night.  Book was completely inoperable (saw spinny in the middle of the page, that ended and the page was just blank).  No "log out" or "log back in" button to tell me how to get back to the content.

**Comment by tmeasday** [comment]
@owenoak did you see any errors in the javascript console.

@SachaG - doesn't happen for me locally - you?

**Comment by owenoak** [comment]
Sorry, I didn't think to check the console.

**Comment by SachaG** [comment]
Doesn't seem to be happening anymore.
