### ISSUE TITLE
Vestigal reference to Session.get("currentPostId") in Chapter 8

### ISSUE THREAD

**Issue by snowyote** [DiscoverMeteor/book#137]
Love the book, thanks so much!

I got about halfway through and am restarting now that you've released the Iron Router changes, so I have a little bit of memory of how things were before.  In the chapter "Editing Posts", the provided post_edit.js snippet is still calling Session.get('currentPostId') to get currentPostId, which is unfortunately no longer set anywhere.  However, the link to github luckily shows the correct commit, which uses this._id.

**Comment by SachaG** [comment]
Thanks for the heads up!

**Comment by snowyote** [comment]
Ack, I just realized this was a dupe - sorry about that!  I'm collecting some other minor errata, I'll scan the closed issues first next time.

**Comment by SachaG** [comment]
Oh don't worry, I hadn't actually fixed all the mistakes :)
