### ISSUE TITLE
Link to download Pdf not working

### ISSUE THREAD

**Issue by indy7** [DiscoverMeteor/book#139]
hi guys,
The link to download Pdf of the book is not working.
It is not that important but would be nice if it is available.

thx.
Indy

**Comment by SachaG** [comment]
Are you sure? I just tried again and it seemed to work. What is the URL of the broken link?

**Comment by indy7** [comment]
Hi Sasha,
Thanks for your quick response.I got ERR_SSL_PROTOCOL_ERROR  when I click the book pdf link https://s3.amazonaws.com/DiscoverMeteor/Discover+Meteor+%E2%80%93+Building+Real-Time+JavaScript+Web+Apps+%E2%80%93+Sacha+Greif+%26+Tom+Coleman.pdf

FYI: I have SSL 2.0 & 3.0 plus TLS 1.0, 1.1, 1.2 enabled on both my Chrome and IE browsers.

It looks like a problem w/ the client-certificate (missing or expired) to establish the SSL connection.I'll look more into it when I have the time.In the mean time, I'm fine w/out the book pdf. It is not a major thing.
Cheers,Indy

Date: Tue, 3 Dec 2013 19:54:14 -0800

**Comment by SachaG** [comment]
We haven't heard about any issues with this recently so I'll close it for now.
