### ISSUE TITLE
"next" link should go to top of page

### ISSUE THREAD

**Issue by eostrom** [DiscoverMeteor/book#14]
When I get to the end of one chapter and click the link to the next, it loads new text, but (in Firefox 21) I'm scrolled to the end of the chapter or somewhere in the middle. It would be nice if the page automatically scrolled to the top so I could continue reading.

**Comment by GiraffeSlacks** [comment]
It happens in both IE 10 and Firefox in Windows and Firefox on Ubuntu. Chrome doesn't seem to have this behavior though.

**Comment by SachaG** [comment]
Fixed in in Firefox at least :)
