### ISSUE TITLE
Edit Posts currentPostId incorrect

### ISSUE THREAD

**Issue by pfafman** [DiscoverMeteor/book#140]
Looks like the github code for the postEdit page did not make it into the book correctly in 'Editing Posts' chapter.  The book is trying to use Sessions to get the currentPostID but you have not set the currentPostId is not set in the Sessions object.  The code in github is correct using the this._id.  I think this is just a change that was missed in the IR update.

**Comment by SachaG** [comment]
Yes, sorry about that. This should already be fixed in the online version, are you using one of the static versions by any chance?

**Comment by pfafman** [comment]
Sacha,

No I just went through the new release online the last 2 days to see what had changed and see how close my IR implementation of telescope was off from what you guys came up with.
Somebody else posted most of the other errors I found.  Most of them were just differences between what was in the book and what was in github for the code.  Github seemed to have
all the correct entrees and they just seemed to have been missed getting into the text of the book.  No big deal just wanted to make sure you could clean it up for I would have been
totally confused if it was the first time I used the book.

Thanks and a really nice book,
Tim
