### ISSUE TITLE
Multiple errata

### ISSUE THREAD

**Issue by snowyote** [DiscoverMeteor/book#141]
Okay, I went through recently-closed issues as well as a few that were posted this morning and removed duplicates from my list.  I apologize if there are any duplicates remaining.  Thanks for writing such an awesome book, folks, it _really_ helped me get on my feet with Meteor and I'm so excited to start working on my site. =)

In chapter 'Routing', subheading 'Named Routes', in "our template would've been accessible at URL `/postLists by` default."  : `postLists` should be `postsList`

In chapter 'The Session', subheading 'Changing the Session', the first Template.layout.helpers call doesn't have a filename indicator (should probably be `client/views/application/layout.js`)

In chapter 'Creating a Meteorite Package', the snippet shown for editing router.js doesn't make sense or match up with the github link:

``` js
  'clearErrors': function(page) {
    Errors.clearSeen();
    return page;
  }
```

It should be:

``` js
  Router.before(function() { Errors.clearSeen(); });
```

Typo in chapter 'Comments', there's a `lib/router.js.js` that should just be `lib/router.js`.

In chapter 'Comments', under the subheading 'Submitting Comments', the snippet for the new `client/views/comments/comment_submit.js` is calling `throwError()` - but we've already converted the error system to a package, so this should be `Errors.throw()`.

In chapter 'Pagination', subheading 'Adding A Load More Link', snippet for client/views/posts/posts_list.js: `Router.current().limit()` should actually be `Router.current().postsLimit()`, or the `postsLimit` method on `PostsListController`should be renamed to `limit` (which is what it looks like was done in the git link).

In chapter 'Pagination', subheading 'Adding A Load More Link', snippet for `client/views/posts/posts_list.js`: There appears to be a spurious `this.posts.rewind()` in the book, but not in the linked git source.

In chapter 'Voting', when we're doing the pluralization thing, the snippet of `client/views/posts/post_item.html` doesn't actually show the new pluralization - it has a line highlighted as changed, but it's still showing the old code: `{{votes}} Votes,`

In chapter 'Voting', when we're adding the newPosts and bestPosts routes, the snippet for `client/views/include/header.html` should mark the `{{pathFor 'home'}}` line as changed.

**Comment by SachaG** [comment]
Thanks, that's a big help! I'll get to work on fixing these :)

Just a note, the Errors package is part of an optional sidebar, not part of the main chapters. So that's why we don't use its code later on in the book.

**Comment by snowyote** [comment]
Ah, that makes perfect sense now.  Thanks!

**Comment by tmeasday** [comment]
Thanks so much @snowyote - I think you deserve a free upgrade for this comprehensive list of fixes. Do you want to send me an email at tom@thesnail.org and I'll hook you up?

**Comment by snowyote** [comment]
Thank you very much, that's quite generous!
