### ISSUE TITLE
a couple suggestions

### ISSUE THREAD

**Issue by snowyote** [DiscoverMeteor/book#142]
None of these are actually bugs so feel free to disregard, this is just a few specific points of feedback.

You may want to have a sidebar for users of coffeescript when first introducing subscriptions that you can use @ to access the global object when at the top level.  So in JS, when we use `Posts =` instead of `var Posts =`, in coffeescript we use `@Posts =`.  I got sidetracked by this a bit at first despite understanding what coffeescript was doing; I just didn't understand how Meteor exposed the global object through `this`.

In chapter 'Routing', you may want to put an inline patch showing the deletion of the body tag instead of just saying 'remove our HTML `<body>` tag', I was skimming and was confused for a bit as to why I was seeing two copies of the site content.

In chapter 'Creating Posts', subheading 'Securing Access To The New Post Form', the part about "You might notice that the access denied template flashes up for a brief moment before the new post page appears."  Before Iron Router, this definitely happened (verified it myself) but it doesn't seem to happen anymore.  Additionally, would it be cleaner to have a waitOn configuration for postSubmit?  It seems like it would be nicer to somehow convert `Meteor.loggingIn()` from a reactive boolean to a handle.

In chapter 'Comments', under the subheading 'Submitting Comments', in the method definition for comment, we have `var post = Posts.findOne(commentAttributes.postId)` but post isn't referred to afterward.  There is a check afterwards to ensure that `commentAttributes.postId` is truthy; should that be a check on the truthiness of post instead?

**Comment by SachaG** [comment]
I'll have to think about this more and get back to you on each point, but I just wanted to first of all say thanks for the great feedback :)

**Comment by phillyslick** [comment]
I would like to put a vote in for the second suggestion.  For clarity's sake.

**Comment by SachaG** [comment]
Just took care of the second suggestion :)

**Comment by snowyote** [comment]
Thank you! =)

**Comment by SachaG** [comment]
I think we fixed most of these. For the CoffeeScript thing, I think the best approach would be to find someone to write a CoffeeScript sidebar or blog post. 

We don't really have the time or knowledge to do it ourselves, but if you'd like to take a shot at it (either as a paid project for the book, or a free guest post for the blog) let us know :)
