### ISSUE TITLE
pathFor postsList doesn't work in header.html

### ISSUE THREAD

**Issue by edyu** [DiscoverMeteor/book#147]
If you click on the Discuss button on the main list page and after you go to the individual post page, the link would point to the same post page instead going back to the main list page.

**Comment by tmeasday** [comment]
Are you writing it ``{{pathFor 'postsList'}}`?

**Comment by edyu** [comment]
Hello @tmeasday yes. As in the other issue I filed, the problem exists in the chapter 12 code, so if you launch instance and then click on the Discuss button from the front page and then put your mouse over the branding 'Microscope', you'll see the link back to the same post page not the post list page.

**Comment by tmeasday** [comment]
Hmm, you are right. This is an odd issue. I'll have to look into it further. It's cleared up by the end of the book however (somehow).

**Comment by tmeasday** [comment]
Ok, you were right it is an issue with IR. I'll try to get it fixed soon: https://github.com/EventedMind/iron-router/issues/328
