### ISSUE TITLE
Update to Iron Router issue - Session.get() remains in Chapter 8 - Editing Posts

### ISSUE THREAD

**Issue by krishnaff** [DiscoverMeteor/book#149]
I think Session.get('currentPostId') remained from the previous version of the book. 

'submit form': function(e) {
    e.preventDefault();
    var currentPostId = Session.get('currentPostId');

I checked the code of the project, and the project shows: 
var currentPostId = this._id;
So it seems its just got left behind in the book.

**Comment by tmeasday** [comment]
Thanks very much @insaneinc01 . Fixed this up.
