### ISSUE TITLE
Click behaviour on Microscope title in IE9

### ISSUE THREAD

**Issue by lzwaan** [DiscoverMeteor/book#151]
I need to get this baby to work on IE9.

When i tried the examples below, bij clicking on the Microscope title, both reject different in Internet Explorer 9. (which is i still want to use)
1. http://meteor-book-chapter6-1.meteor.com/  will not refresh the whole page by clicking on the title. Perfect !!!
2. http://meteor-book-chapter5-1.meteor.com/ will refresh the page, which i not want...because i am already on the page, but  it will  refresh the browser page and after a second i see the posts..

Could it be that option 1 is still using the old meteor router and option 2 is using iron-router package.??

Kind regards,

Lars

**Comment by tmeasday** [comment]
Hi @lzwaan - perhaps try this again with Iron Router 1.0 -- which includes built in support for IE9+
