### ISSUE TITLE
code snippet in Session missing footer

### ISSUE THREAD

**Issue by charliemagee** [DiscoverMeteor/book#153]
This snippet is missing the footer telling us to put it in posts_list.js

Template.layout.helpers({
  pageTitle: function() { return Session.get('pageTitle'); }
});

Also in Session: (not sure this is a problem really, because now I see this is how you're formatting things. But this example and other like it will make some people think they need to type in the last line in the snippet box.)

Deps.autorun(function() {
  console.log('Value is: ' + Session.get('pageTitle'));
});
Value is: A brand new title

Suggest this:

Deps.autorun(function() {
  console.log('Value is: ' + Session.get('pageTitle'));
});

(Outside of gray box.)
As you might expect, the block of code provided inside the autorun runs once, outputting its data to the console: "Value is: A brand new title" Now, let's try changing the title:

**Comment by tmeasday** [comment]
Thanks @charliemagee
