### ISSUE TITLE
Adding Users: accounts ui different than in book

### ISSUE THREAD

**Issue by charliemagee** [DiscoverMeteor/book#154]
![microscope_user_ui_chrome](https://f.cloud.github.com/assets/897319/1688725/3b3b28ec-5e0e-11e3-9d50-2024e11a7076.png)

**Comment by charliemagee** [comment]
I know the functionality hasn't changed. Just not sure you know.

**Comment by snowyote** [comment]
That's part of Bootstrap, it's just being responsive - it's entirely dependent on the width of your browser window (i.e. if you widen your window, it ends up looking more like what's in the book).  I noticed the same thing when I was trying to do the two-account side-by-side update stuff.

**Comment by charliemagee** [comment]
Ah, I just discovered that and was going to come back and mention it. Duh. Yeah, I've got a window with Microscope side by side with a window showing the book. This minor detail took me back to when I was trying to learn Rails and I was a year or two behind the tutorial I was working on. I was never sure if I did something wrong or if the world changed out from under me (again).

**Comment by tmeasday** [comment]
Don't worry @charliemagee -- you are not the first to be tripped up by this :)

I wonder if we should make a note of it or something.
