### ISSUE TITLE
directory location for router.js inconsistent

### ISSUE THREAD

**Issue by charliemagee** [DiscoverMeteor/book#155]
Snippet footer for router.js says this:
client/helpers/router.js

The Routing chapter has us create it and put it in:

lib/router.js

**Comment by grsmith1943** [comment]
I have been putting all in lib/router.js. I figured that the git account would be correct and the book was just not updated.

**Comment by tmeasday** [comment]
Thanks @charliemagee . As @grsmith1943  suggested `lib/router.js` is the correct location
