### ISSUE TITLE
Router.current().limit() doesn't work

### ISSUE THREAD

**Issue by yytina** [DiscoverMeteor/book#156]
It doesn't seem to work in the below. Would you advise on this? 

Template.postsList.helpers({
  hasMorePosts: function(){
    this.posts.rewind();
    return Router.current().limit() == this.posts.fetch().length;
  }
});
client/views/posts/posts_list.js

**Comment by tmeasday** [comment]
Apologies. This is an typo in the controller section of the code. It should have a function called `limit()` but it was listed as `postsLimit()`. It's fixed now.
