### ISSUE TITLE
Building The New Post Page

### ISSUE THREAD

**Issue by galenking** [DiscoverMeteor/book#157]
Is the **Building The New Post Page** section really supposed to change the Router.configure section from:

```
Router.configure({
  layoutTemplate: 'layout',
  loadingTemplate: 'loading',
  waitOn: function() { return Meteor.subscribe('posts'); }
});
```

To: 

```
Router.configure({
  layoutTemplate: 'layout'
});
```

It doesn't seem to work as `return Meteor.subscribe('posts');` is no longer being called.

Or have I missed a step somewhere?

**Comment by tmeasday** [comment]
Not at all. Thanks for picking this up.
