### ISSUE TITLE
bootstrap for header

### ISSUE THREAD

**Issue by yytina** [DiscoverMeteor/book#160]
Hi, my header links in header.html stopped working. Would you give instructions for that?  i think the order of adding package by "mrt add" matters. Thank you in advance.

FYI, this is my smart.json

{
  "packages": {
    "iron-router": {},
    "spin": {},
    "accounts-ui-bootstrap-dropdown": {},
    "iron-router-progress": {},
    "bootstrap3-less": {}
  }
}

**Comment by SachaG** [comment]
I don't think the order in which you added packages should matter. At what point of the book are you? Do the links still point to the right URL, or do they just show no URL at all?

**Comment by yytina** [comment]
Hi,

I was on the chapter of voting. The links were working before. But I did
some mrt add/ remove bootstrap and the header menus don't show up other
than 'Microscope' and after going to individual post page, 'Microsocpe'
link doesn't work either showing the current individual post page as url.
Please find attached snapshots FYI.

It would be great if you let me know what i can do to fix this problem.
Thank you in advance.

Best Regards,

Jin

**Comment by SachaG** [comment]
Sorry, I don't think the screenshots were uploaded. Could you maybe upload them somewhere else and link to them here? Also, it would help if you could upload your repository to your own GitHub account and link to the problem files directly.

**Comment by isAlmogK** [comment]
It might be your bootstrap version, try removing it and just installing the default version mrt add bootstrap

**Comment by SachaG** [comment]
Closing this for now.
