### ISSUE TITLE
Question: populate select box selected value from mongoDB

### ISSUE THREAD

**Issue by ronenyurik** [DiscoverMeteor/book#161]
Hi All,

I'm trying to populate a form (user configuration form) with the user first setup (saved in the DB), not sure why but it's not working (I can see that handlers got the correct value)
added the handlers to the label to make sure they got something inside.
(already found that I can't control the type=file component, so you can ignore it)

Thanks
Ronen

This is my code:
<template name="userSettings">
  <form class="main">
    <div class="control-group">
        <label class="control-label" for="interval"><strong>Run Interval - {{interval}}</strong></label>
        <div class="select">
            <select name="interval">
                <option>Please Select...</option>
                <option>15 Min.</option>
                <option>30 Min.</option>
                <option>60 Min.</option>
                <option>120 Min.</option>
                <option>180 Min.</option>
            </select>
        </div>
    </div>

```
<div class="control-group">
    <label class="control-label" for="notification"><strong>Notification Method</strong></label>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="email" checked="{{email}}"/> Email - {{email}}
        </label>
        <label>
            <input type="checkbox" name="sms" checked="{{sms}}"/> SMS - {{sms}}
        </label>
    </div>
</div>

<div class="control-group">
    <label for="avatar"><strong>Avatar image - {{avatar}}</strong></label>
    <input type="file" name="avatar" value="{{avatar}}"/>
</div> 

<div class="control-group">
    <div class="controls">
        <input type="submit" value="Submit" class="btn btn-primary"/>
    </div>
</div>
```

  </form>
</template>

**Comment by SachaG** [comment]
Can you point us to the files inside a GitHub repo? It'll be easier for us to understand what you're trying to do. 

But it sounds like maybe the problem is that you're using an `{{#each}}` block where you shouldn't? They don't always work everywhere, so I would suggest trying out a few different things first (i.e. populate a regular <ul>, populate a set of radio buttons, etc.) to isolate the problem.

**Comment by ronenyurik** [comment]
Hi Sacha,

since I’m new in github could you explain how can I share my repo ? is it just the link ?
https://github.com/ronenyurik/autojedi

anyway, I’m not using {{#each}} attaching the code again,
as you can see I’m trying to populate the components using {{<value from DB>}}
in order to make sure I got something in {{…}} I added them also to the label of each component,
and I can see that indeed I got the values from the DB.

Thanks
Ronen

<template name="userSettings">
  <form class="main">
    <div class="control-group">
        <label class="control-label" for="interval"><strong>Run Interval - {{interval}}</strong></label>
        <div class="select">
            <select name="interval">
                <option>Please Select...</option>
                <option>15 Min.</option>
                <option>30 Min.</option>
                <option>60 Min.</option>
                <option>120 Min.</option>
                <option>180 Min.</option>
            </select>
        </div>
    </div>

```
<div class="control-group">
    <label class="control-label" for="notification"><strong>Notification Method</strong></label>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="email" checked="{{email}}"/> Email - {{email}}
        </label>
        <label>
            <input type="checkbox" name="sms" checked="{{sms}}"/> SMS - {{sms}}
        </label>
    </div>
</div>

<!-- <div class="control-group">
    <label for="avatar"><strong>Avatar image - {{avatar}}</strong></label>
    <input type="file" name="avatar" value="{{avatar}}"/>
</div> 
```

 -->
    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Submit" class="btn btn-primary"/>
        </div>
    </div>
  </form>
</template>

Thanks
Ronen Yurik

Site: www.autojedi.com | Cell: +972.52.6122.632 | Skype: ronen.autojedi

**Comment by SachaG** [comment]
Oh, got it, sorry. At this time you can't use helpers as attributes… So you can't do something like `checked="{{email}}"`. Instead, you can do something like this (from the code of Telescope):

```
   <div class="controls">
              <input type="checkbox" name="sticky" id="sticky" {{isSticky}} />
            </div>
```

Where `{{isSticky}}` could be `checked="checked"`

Does that make sense?

**Comment by ronenyurik** [comment]
Thanks, just to populate {{isSticky}} I will need to create helper in my user_settings.js right ?
something like this

<div class="checkbox">
            <label class="checkbox">
                <input id="email" type="checkbox" name="email" {{emailChk}}/> Email
            </label>
            <label class="checkbox">
                <input id="sms" type="checkbox" name="sms" {{smsChk}}/> SMS
            </label>
        </div>

Template.user_settings.helpers({
  emailChk : function(){
    return getUserSetting('settings.email', '', this) ? 'checked' : '';
  },

  smsChk : function(){
    return getUserSetting('settings.sms', '', this) ? 'checked' : '';
  }

});

?

**Comment by SachaG** [comment]
Yes, exactly :)

**Comment by ronenyurik** [comment]
last question :-) at least for today,

this is a good structure ? cause when I added the new code the “helpers” my post is not working anymore

Template.user_settings.helpers({
  emailChk : function(){
    return getUserSetting('settings.email', '', this) ? 'checked' : '';
  },

  smsChk : function(){
    return getUserSetting('settings.sms', '', this) ? 'checked' : '';
  }

});

Template.userSettings.events({
  'submit form': function(e) {
    e.preventDefault();

```
var userId = this._id;

var settings = {
  interval: $(e.target).find('[name=interval]').val(),
  email: $(e.target).find('[name=email]:checked').length,
  sms: $(e.target).find('[name=sms]:checked').length 
  // avatar: $(e.target).find('[name=avatar]').val()
}


if (!userId){

    Meteor.call('post', settings, function(error, id) {
      if (error)
```

Thanks
Ronen Yurik

Site: www.autojedi.com | Cell: +972.52.6122.632 | Skype: ronen.autojedi

**Comment by SachaG** [comment]
The structure seems ok to me… I'm not sure what the problem is, sorry.
