### ISSUE TITLE
Meteor and Swagger ?

### ISSUE THREAD

**Issue by ronenyurik** [DiscoverMeteor/book#162]
Hi All,

I'm new with Meteor so any help will be great :-)

I'm trying to trigger Jenkis job/build by clicking on a button in a portal I build using Meteor, I searched w/o success how can I trigger a post request from Meteor ?
the curl command I'm using looks like this:

curl --user <user name>:<token> http://<ip>:8080/view/<project>/job/<job name>/build

Thanks
ROnen

**Comment by tmeasday** [comment]
Hey ronen,

You should be able to use the http package for that. 

We have an extra chapter on integrating with 3rd party services that might be informative too. 

Cheers, 
Tom

**Comment by SachaG** [comment]
The HTTP package: http://docs.meteor.com/#http
