### ISSUE TITLE
Routing Chapter Missing Key Point

### ISSUE THREAD

**Issue by thatgibbyguy** [DiscoverMeteor/book#163]
In Chapter 5: Routing, we start our project with two files inside of the views directory:

```
main.html
main.js
```

We should either use 

```
main.html 
```

or 

```
application/layout.html 
```

as our master template, but we do not need both.

However, we absolutely do need the content of main.js, 

```
Meteor.subscribe('posts');
```

but we could put it inside of our posts_list.js instead of main.js.

Either way, this needs to be clarified in the book.

**Comment by thatgibbyguy** [comment]
Nevermind, I skipped over the part that talked about removing the body from main.html. 

I still feel that this could be clarified a bit more, in particular talking about how we can make the master layout work for us better.

For instance main.html could include our head data, header, and any other constants in our head document. And main.js could hold all of our subscriptions.

**Comment by SachaG** [comment]
Thanks, I'll try to clarify that part.
