### ISSUE TITLE
Could not login to book.discovermeteor.com via iPad

### ISSUE THREAD

**Issue by rick-golden-healthagen** [DiscoverMeteor/book#165]
I tried registering and logging in to book.discovermeteor.com via Safari and via Chrome.

The whole registration process was slow. I was left a number of times with a pop up that would not go away on its own. Both Enter new password, and Login pop ups. 

Finally connected via an iPhone and a Mac after resetting password.

**Comment by SachaG** [comment]
We changed the whole registration process, hopefully it'll work better now :)
