### ISSUE TITLE
Chapter 12: Template error introduced after commit 12-1

### ISSUE THREAD

**Issue by pkaushik** [DiscoverMeteor/book#169]
The `{{pathFor}}` helper in the header crashes when the optional `postsLimit` parameter is added to the `postsList` path, resulting in the following rendered markup

``` html
<a class="brand" href>Microscope</a>
```

This is right after commit 12-1. Linking directly to `"/"` in the header template fixes it.

**Comment by SachaG** [comment]
I think this is probably the same as #147.

**Comment by pkaushik** [comment]
Looks like it, but there's another bug in this section of the book, that also seems to be related to iron router. I will file it separately. It's similar to https://github.com/DiscoverMeteor/book/issues/146
