### ISSUE TITLE
Make a book version without any routing. It unnecessary complicates beautiful Meteor

### ISSUE THREAD

**Issue by talalav** [DiscoverMeteor/book#173]
Routing is not so important to make an introductory book difficult to understand.

**Comment by talalav** [comment]
I would be happy to read " Pagination" chapter without admixture of routing. Just want to understand meteor.

**Comment by jgcartland** [comment]
That's one reason I bought the book, for a good introduction to routing. ;D

**Comment by SachaG** [comment]
To be honest, I personally think Routing is one of the most important components of any app, especially now with Iron Router. So I'm afraid it's here to stay :)

**Comment by talalav** [comment]
I agree about app. First of all Meteor addresses ease of development on which the very existence of an app (even in a form of a prototype) depends;-) It's much more powerful social issue.
