### ISSUE TITLE
Node installation suggestion

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#181]
From my experience, you should really not suggest that people install their own version of node, but you should rather suggest that they configure their `PATH` so that the node from Meteor is used. Otherwise you could get different versions of node installed on your system and as a consequence for smart packages which use npm packages that have native code to compile, Meteorite packages will not work. Because at compile time system node will be used, but at run time Meteor node will be used and compiled parts versions will not match. It is really painful to debug that.

So I would suggest that you add Meteor bin directory to user's PATH, it already contains both `node` and `npm` binaries. Additionally, because Meteor is installed into user home directory, you do not even have to use `sudo` at any point. And this is again a good suggestion. You should never be able to use `sudo` while developing with Meteor. If you do, then you can get to the issues when some packages are installed with `sudo` and have root permissions and cannot be upgraded later on when running Meteor as normal user. And then people start using `sudo` to run Meteor itself. And this is a really bad practice.

Which can all be addressed by simply using node bundled with Meteor for everything Meteor related.

cc @avital

**Comment by mitar** [comment]
And you have then issues in EC2 instructions. You can solve that by simply asking users to add one line to their profile file:

```
echo 'export PATH=~/.meteor/tools/latest/bin:$PATH' >> ~/.bash_profile
```

**Comment by tmeasday** [comment]
Hey @mitar,

I'm probably inclined to agree that this is a simpler and less bug free way to go, but I think it might lead to other issues (involved with with editing `.bash_profile`), and given that Meteorite should be retired in a few weeks (for 1.0), I think we'll just leave this for now.

I appreciate the concern thoguh.
