### ISSUE TITLE
Modifying .meteor/packages

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#182]
I would not really suggest that people modify `.meteor/packages` directly. They are commands in `meteor` to modify that. You should not have to modify `.meteor/packages` directly. Everything in `.meteor` should really be private and not touched by user. Because there is no reason that in the future Meteor would not change the way how it deals with packages and maybe when you will call `meteor add` it will not just add a line to the `.meteor/packages`. This is really just current implementation.

**Comment by mitar** [comment]
I would rather suggest that you have in the book that users should not touch things there, but they are invited to explore it to get a better feeling how things are put together. For example, they should check `.meteor/packages` and `.meteor/release` files.

**Comment by tmeasday** [comment]
Do we suggest at some point that people should change that file?

**Comment by mitar** [comment]
"This is where Meteor stores its own code, and modifying things in there is usually a very bad idea. The only exceptions to this are the .meteor/packages and .meteor/release files, which are respectively used to list your smart packages and the version of Meteor to use."

Exception to modifying is for me suggesting that they can change. So yes. :-)

**Comment by SachaG** [comment]
Agree for the `packages` file, but is there a way to change the release without modifying `.meteor/release` though?

P.S. thanks so much for all the help. Shoot us an email at hello@discovermeteor.com :)

**Comment by mitar** [comment]
I do not know about `.meteor/release`, I am using Meteorite and I lock down Meteor version through `smart.json`.

And no problem for the help. I am TAing today at the workshop and I am reading the book through to be prepared. :-)

**Comment by mitar** [comment]
(I think `meteor update` modifies `.meteor/release`.)

**Comment by tmeasday** [comment]
I think @mitar is right on this. Users shouldn't as a rule touch those files although it's usually pretty important to understand what they do and how they change as your project develops.

**Comment by tmeasday** [comment]
Ok, fixed.
