### ISSUE TITLE
It is "changed" not "updated"

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#183]
When you talk about `_publishCursor()`, you mention that:

> Whenever a document is added, removed or changed, it sends those changes down to the client-side collection. (It uses .observe() on the cursor and .added(), .updated() and removed() to do this).

It is not `.updated()`, but `.changed()`. [See](http://docs.meteor.com/#publish_changed).

**Comment by SachaG** [comment]
You're right, thanks!
