### ISSUE TITLE
You use underscore without adding a package

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#186]
In whitelisting keys in the `post` sever method, you are using underscore without adding the underscore package. From [Meteor documentation](http://docs.meteor.com/#underscore):

"Currently, underscore is included in all projects, as the Meteor core depends on it. _ is available in the global namespace on both the client and the server even if you do not include this package. However if you do use underscore in your application, you should still add the package as we will remove the default underscore in the future."

**Comment by SachaG** [comment]
Good point. We'll probably end up adding it at the start of the book.
