### ISSUE TITLE
Local collection?

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#187]
In the latency compensation section, you are mentioning "local collections". In Meteor word this are special kind of collections (not synced to the data store) and I am not sure if this is correct to name a client version of server collection a "local collection".

> If you pass null as the name, then you're creating a local collection. It's not synchronized anywhere; it's just a local scratchpad that supports Mongo-style find, insert, update, and remove operations. (On both the client and the server, this scratchpad is implemented using Minimongo.)

That part is a bit confusing. So if you are talking about client side collections, then it is untrue that allow and deny callbacks are called on the client at all. They are run only on the server side. If you are talking about the server side there, then why are you calling server side collections "local collections"?

**Comment by mitar** [comment]
I would like to add that I got a question at the workshop exactly about this section. Person said he has troubles understanding it.

**Comment by tmeasday** [comment]
Thanks, fixed this. Appreciate it.
