### ISSUE TITLE
Chapter 8, Editing posts. pdf is fubar. 

### ISSUE THREAD

**Issue by jgcartland** [DiscoverMeteor/book#188]
edit_post.html, as displayed in pdf, wraps the form in a {{#with post}}. No joy. 

The on-line and github version are significantly different, and seem to contain a workable version. I'm learning to debug my own code, but am exasperated by having to reconcile incompatible example code. 

Is there a current and coherent version of the book? What is most recent? 
At this moment, I'm considering the pdf unusable.

**Comment by SachaG** [comment]
You're right, the PDF is out of date. Sorry about that! We'll update it shortly, but in the meantime I would recommend using the online version.
