### ISSUE TITLE
Taking Care of CSS Section

### ISSUE THREAD

**Issue by sbefort** [DiscoverMeteor/book#19]
Early in the book it says, "CSS automatically gets loaded and minified by Meteor, so unlike other static assets it goes into /client, not /public. Go ahead and create a client/stylesheets/ directory now, and put this style.css file inside..."

After completing this task and running mrt, my code is not minified.  I clicked on launch instance to view your code, and yours is minified.  Why the difference?

**Comment by SachaG** [comment]
CSS code is only minified in production, not in your local development environment.
