### ISSUE TITLE
Using deny as a callback

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#190]
For `deny` to really work as a callback to change a document before insertion, you also have to make sure no `transform` is defined on the document. So I would suggest you use the following example in the book:

```
Posts.deny({
  update: function(userId, doc) {
    doc.lastModified = +(new Date());
    return false;
  },
  transform: null
});
```

**Comment by tmeasday** [comment]
I didn't know you needed to set `transform: null`. Any hints as to why?

**Comment by mitar** [comment]
You need `transform: null` if you have a transform defined on the collection. Otherwise Meteor makes a copy before passing in a document so any changes (like `doc.lastModified`) are done on the copy and not original. See [here](https://github.com/meteor/meteor/blob/devel/packages/mongo-livedata/collection.js#L701).

**Comment by mitar** [comment]
So I think it is useful in a book to use this always, so that it will work for people trying this approach even after they add `transform`.
