### ISSUE TITLE
The error notification pattern

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#191]
(Sorry for opening so many tickets, feel free to just ignore them.)

I think that the pattern with `Meteor.defer()` is not the best one. I would rather suggest that you use `Meteor.setTimeout` with for example 1 second timeout and assign the returned timeout to template object. And then in `destroyed` you clear the timeout. So with that you would require that notification is really displayed for 1 second to the user. This is a generalization of your pattern which is not just a workaround for the redirect, but also requires that notification was displayed for some time to the user before it got removed.

Untested, but I have something like this in mind:

```
Template.error.created = function () {
  this._timeout = null;
  this._rendered = false;
};

Template.error.rendered = function () {
  if (!this._rendered && !this._timeout) {
    this._rendered = true;
    var error = this.data;
    this._timeout = Meteor.setTimeout(function () {
      this._timeout = null;
      Errors.update(error._id, {$set: {seen: true}});
    }, 1000);
  }
};

Template.error.destroyed = function () {
  if (this._timeout) {
    Meteor.clearTimeout(this._timeout);
    this._timeout = null;
  }
}
```

BTW, why do you set `seen` flag at all and clear it between routing, why not simply directly remove the document from local collection?

**Comment by mitar** [comment]
Additionally, "This means that the redirection will kick in before the defer callback, which will never have a chance to be executed." is not really true. Defer callback will get executed, just after the redirect. It is not cleared.

BTW, `Meteor.defer` is not documented!

**Comment by tmeasday** [comment]
Yeah, you are probably right. We've never loved this hacky way of dealing with the problem.

We'll revisit this when we next do an update.
