### ISSUE TITLE
Security considerations - check all input arguments to methods and publish functions

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#193]
I think that you should really always in all examples from very beginning use input [arguments checking framework provided by Meteor](http://docs.meteor.com/#match) to verify and validate any arguments. People really have to think about that from the very beginning and you cannot just assume they will add security later. Security is not something you add later on. Also all official Meteor examples have those checks now.

So add all those checks around, explain them and reasoning. Mention `audit-argument-checks` package as well.

To show the issue, see `comments` publish. If I pass for `postId` something like `{$ne: null}` I get access to all comments. You should really check that `postId` is string, in this example.

**Comment by tmeasday** [comment]
You are right. We'll get this in the next update.
