### ISSUE TITLE
Unclear sentence

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#194]
It is unclear what you mean here, if somebody does not already know: "Denormalizing data means not storing that data in a "normal" form -- in other words, having multiple copies of the same piece of data hanging about."

Is normal form that you have multiple copies of the same piece of data hanging about. Or is it this denormalized data? So are other words for "normal form" or for "denormalizing data"?

**Comment by SachaG** [comment]
Good point :)
