### ISSUE TITLE
Elements cannot be moved

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#199]
"The crucial point to keep in mind is that elements cannot be moved. They can only be deleted and created (note that this is a limitation of the DOM itself, not of Meteor). So to give the illusion of elements A and B switching place, Meteor will actually delete element B and insert a brand new copy (B') before element A."

Not completely true. You can [detach](http://api.jquery.com/detach/) and then insert back. In this way you are not doing a brand new copy. (Meteor of course can delete elements and do other things at will.)

**Comment by tmeasday** [comment]
True. We'll get this in the next update.
