### ISSUE TITLE
Diagram inconsistency

### ISSUE THREAD

**Issue by matb33** [DiscoverMeteor/book#2]
Correct me if I'm wrong, but the diagram that illustrates autopublish might be incorrect:

http://book.discovermeteor.com/images/diagrams/autopublish@2x.png

The server "comments" collection holds 7 documents, whereas the client "comments" collection only holds 5. Shouldn't the client have 7 too?

http://book.discovermeteor.com/chapter/publications-and-subscriptions/

**Comment by SachaG** [comment]
You're right, thanks for noticing!
