### ISSUE TITLE
postsWithRank and optimizations

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#200]
Earlier in the book you mention that Meteor optimizes helpers if you return a cursor, but then in `postsWithRank:` you are returning an array. I think you should mention the point about optimization again. (Or is it still optimized because you are using `.map`?)

**Comment by tmeasday** [comment]
No, it's not still optimized. 

We aren't using the cursor because we need to add the rank field. I think maybe we can get the field on there via using a transform though. I'll look into this for the next update.

**Comment by mitar** [comment]
Or you could do `observeChanges` and add the field manually.
