### ISSUE TITLE
Use of # in load more links

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#201]
By using `#` in load more links you might accidentally override anchors in the URL. You could simply use `href=""` instead.

**Comment by SachaG** [comment]
I don't think we use `#` in load more links? We do use it on upvote buttons, but since we're not using anchors otherwise I think we'll probably leave it like this for now.

**Comment by mitar** [comment]
The point is that it is good to not teach people to use `#` for `href`.

**Comment by SachaG** [comment]
Yes, we'll try and fix it when we have time :)
