### ISSUE TITLE
Why this.posts.fetch().length?

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#204]
Why not `this.posts.count()`? In `hasMorePosts` helper?

**Comment by mitar** [comment]
Ignore. :-) I should read first. :-)

BTW, I see fix for this in master branch of Meteor. It seems it was fixed.

**Comment by tmeasday** [comment]
Oh, any idea which release of Meteor the fix appeared in? I think microscope is still running a few point releases back at the moment..

**Comment by mitar** [comment]
I think 0.6.5.

**Comment by tmeasday** [comment]
Hmm, no we aren't that far back..
