### ISSUE TITLE
Quick Question about Discover Meteor

### ISSUE THREAD

**Issue by JakePrasad** [DiscoverMeteor/book#205]
Hello, 

Firstly I want to say that the Discover Meteor book is fantastic! I was wondering though, if a chapter on Meteor mobile apps is currently under development and, if so, what the ETA for the new chapter would be.

Also, I have the Premium Edition of Discover Meteor and was wondering if there are any plans to update the Atmosphere Package screencast? A mobile app chapter is more pressing imo, however.

Thanks, 
Jake

**Comment by SachaG** [comment]
Sorry, we don't currently have plans to add a chapter about mobile apps. It's definitely something we are conscious of, and might do down the road.

And I'm afraid we're probably not going to update the screencast. But if it gets too out of date we might replace it with something else entirely.
