### ISSUE TITLE
In Template chapter Handlebar not working

### ISSUE THREAD

**Issue by mayi12345** [DiscoverMeteor/book#206]
Hi all,

I followed all the steps up to building posts_list.js, but when I open localhost:3000, nothing showed up. 

I know the main.html and style.css works because i can see the title and background color are what expected. It just that there are no content, which means main.html is unlikely to connect to {{>postsList}} since nothing is retrieved. 

I also tried to move all other documents from /views/posts directory just under /client (cus I suspected it might be a pointer issue), but it still does not work Do I miss installing anything?

Here is my path structure:

-ls microscope:
client      lib     server      smart.lock
collections public      smart.json

-ls client
main.html        main.js        stylesheets views

-ls views
posts

-ls posts
post_item.html  posts_list.html posts_list.js

I have checked several times and all codes inside each html/js are the same as the examples.

Thank you so much for your help!

**Comment by tmeasday** [comment]
Hi @mayi12345 

Sorry we missed this for a couple of days.

Can you give us some more information about any errors that you see in the browser console?

**Comment by mayi12345** [comment]
Great you guys are finally here :)

Here is the error browser console keeps giving me (regardless of using Mongo db or js array):

Uncaught Error: {{#each}} only accepts arrays, cursors, or falsey values. You passed: function (data) {                                                        // 284
        // don't create spurious annotations when data is same                       // 285
        // as before (or when transitioning between e.g. `window` and                // 286
        // `undefined`)                                                              // 287
        if ((data || Handlebars._defaultThis) ===                                    // 288
            (old_data || Handlebars._defaultThis))                                   // 289
          return fn(data);                                                           // 290
        else                                                                         // 291
          return Spark.setDataContext(data, fn(data));                               // 292
      } deftemplate.js:24
event.returnValue is deprecated. Please use the standard event.preventDefault() instead. jquery.js:3259

Thank you so much for your help!

**Comment by tmeasday** [comment]
Which commit of the book are you up to?

**Comment by mayi12345** [comment]
Stuck in "Templates" and "Collection" and was not able to move on because I could not see anything on 3000...

**Comment by tmeasday** [comment]
If it's not working properly in the Templates chapter:
1. Are you writing the `{{#each posts}}` correctly?
2. Have you written the `posts` helper correctly? If you just make it very simple (like `Template.postsLists.helpers({posts: []});`) you should at least avoid the error if everything is written right.

**Comment by mayi12345** [comment]
I copied and pasted the codes directly from the Templates chapter.. And checked it quite a few times and still did not know why such an error occurred.

Here is the code stored in my laptop: 

pwd: client/views/posts/posts_list.html
<code>
template name="postsList" </code> (<--get rid of "<" and ">" so that it shows as code...)
<code>div class="posts"
    {{#each posts}}
      {{> postItem}}
    {{/each}}
  /div
/template

</code>

pwd: client/views/posts/posts_list.js
<code>Template.postsList.helpers({
  posts:function(){
    return Posts.find();
  }
});</code>

I used Mongo for now because I was at "Collection" chapter. But originally it was:

<code>var PostData = [...]
Template.postsList.helpers({
  posts:PostData
}); </code>

I really have no idea what could have gone wrong.. both cases are arrays and neither works.
Thank you for your help!

**Comment by tmeasday** [comment]
The code you have written there seems right to me.

The error you pasted implies you've written something like `{{#each with X}}` somewhere. Is that possible?

It might be worth restarting Meteor and if it's still not working, starting from scratch. Sometimes it can be hard to spot weird mistakes that you've made.

(You can paste code in by surrounding it by triple - backticks btw).

**Comment by mayi12345** [comment]
I restarted from scratch and now it works... Still did not know what went wrong in the previous code... but at least i typed more codes and have better understanding on handlebars.

Thank you so much!!!
