### ISSUE TITLE
Animations Chapter: posts_list.html template code is different in book

### ISSUE THREAD

**Issue by lb-** [DiscoverMeteor/book#207]
The embedded code still has the originally set up...

```
{{#if postsReady}}
  {{#unless allPostsLoaded}}
    <a class="load-more" href="#">Load more</a>
  {{/unless}}
{{else}}
  <div>{{> spinner}}</div>
{{/if}}
```

  </div>

However, that part was removed when the loading smart package was added & later superseded by the iron-router-progress package.

The code in the book should look like it is in github here:
https://github.com/DiscoverMeteor/Microscope/blob/cfe0ef952e60cbefc9934fe9f77e1d3e8a890e96/client/views/posts/posts_list.html

Not a big deal, just a bit confusing, had to double check I had not missed something.

**Comment by SachaG** [comment]
You're right, sorry about the inconsistency.
