### ISSUE TITLE
Deploying (Chapter 2.5) - git clone repo to my own server

### ISSUE THREAD

**Issue by edbrad** [DiscoverMeteor/book#208]
I'm following the example steps to deploy on my own server (Ubuntu Server 12.04 - VMware Workstation 9). I having trouble cloning the Microscope Git repository from github.com:

COMMAND
sudo git clone https://github.com/DiscoverMeteor/microscope.git /home/meteor

RESULTS
error: The requested URL returned error: 403 while accessing https://github.com/DiscoverMeteor/microscope.git/info/refs
fatal: HTTP request failed

Am I doing something wrong?

**Comment by SachaG** [comment]
Maybe try

`sudo git clone git@github.com:DiscoverMeteor/Microscope.git /home/meteor` ?

**Comment by SachaG** [comment]
Closing this as we've updated the chapter with different workflows altogether.
