### ISSUE TITLE
Commit 5-3 instance link broken and 5-2 seems to go to 5-3 code

### ISSUE THREAD

**Issue by jcohoon** [DiscoverMeteor/book#209]
When I click on the link (http://meteor-book-chapter5-3.meteor.com/) I get a message stating, "There is no site deployed at this address."

Also, 5-2 (http://meteor-book-chapter5-2.meteor.com/) shows the "Discuss" button, making me think it must be the 5-3 code.

**Comment by tmeasday** [comment]
Thanks, we'll do a re-deploy to fix this up.
