### ISSUE TITLE
Commit 7-4 router.js code change is highlighted incorrectly

### ISSUE THREAD

**Issue by jcohoon** [DiscoverMeteor/book#211]
In the router.js code in the book right before the 7-4 commit, the last four lines are highlighted in green but those lines have only moved down to make room for the additions/changes just above them.

By the way, there's another code section earlier that I found confusing for a moment because (if I'm remembering correctly) it doesn't include all of the code that should be in the file at that point, only the new/changed part. Up to that point I had thought that the files were being included in their entirety. I can submit this separately and figure out exactly where I'm talking about if it's helpful/this is something that needs fixing. I think it was in header.html, in the vicinity of chapter 4.

**Comment by SachaG** [comment]
Thanks for the heads up!
