### ISSUE TITLE
Chapter 12 different between Web and PDF versions

### ISSUE THREAD

**Issue by freakingid** [DiscoverMeteor/book#213]
I was working through Chapter 14 from the web version of the book, and posts_list.html references "postsReady" and "allPostsLoaded," which have never been created.

Searching through the PDF version of the book, I find both of those, first in Chapter 12.

Please update -- probably the web version? Thanks.

**Comment by SachaG** [comment]
The PDF version can be a little out of date sometimes, sorry about that. We'll update it soon. In the meantime, we recommend using the web version as reference.

**Comment by freakingid** [comment]
I understand. However, I was using the web version. In Chapter 14, there are helpers that I could find only in Chapter 12 of the PDF. It seems like in the web version, Chapter 12, subscriptions are moved to the router, but in Chapter 14 web version it has not been updated appropriately. Hope that makes sense. Thank you.
