### ISSUE TITLE
Error Redirect Functionality Broken

### ISSUE THREAD

**Issue by jacksondc** [DiscoverMeteor/book#214]
The functionality added in commit 9-3 that causes an error to appear on the page even after we are redirected seems to be broken later in the book. It seems to go wrong at commit 10-4, where we subscribe to the comments collection. Does anyone know what the problem could be?

**Comment by tmeasday** [comment]
@jacksondc 

Apologies for the extreme delay in responding to this :)

The reason this happens is that now the post page has to wait for the comments, and thus doesn't render for a moment while they load. The net effect of this is that the errors render twice -- once with the loading page, then _again_ when the post is loaded. And the notification goes away.

A solution is to wrap the errors in a ready if:

```
<template name="errors">
  <div class="errors row-fluid">    
    {{#if ready}}
      {{#each errors}}
        {{> error}}
      {{/each}}
    {{/if}}
  </div>
</template>
```

Where

```
Template.errors.helpers({
  ready: function() {
    return Router.current() && Router.current().ready();
  }
});
```

We need to try to figure out a way to make this better I think.
