### ISSUE TITLE
inconsistent usage of mrt and meteor

### ISSUE THREAD

**Issue by fsalbrechter** [DiscoverMeteor/book#215]
In the book the code to create an example is 
mrt create microscope
vs the documentation http://docs.meteor.com/ states
meteor create myapp

**Comment by SachaG** [comment]
Good catch, thanks!

**Comment by daveit** [comment]
The explanation for this difference is explained in the 'getting started' section
Dave

**Comment by SachaG** [comment]
True, but even when using Meteorite you can use `meteor create` instead of `mrt create`.

**Comment by fsalbrechter** [comment]
It also creates different files...one creates smart.json the other does
not...
I'm still confused which one to use...?

**Comment by SachaG** [comment]
I'll confirm with Tom if there's any reason to use `mrt` over `meteor` in the context of the book. But in the meantime you can use either one really.

**Comment by tmeasday** [comment]
It doesn't really matter which you choose. As @fsalbrechter said, `mrt` creates the `smart.json` too, which is what the git commit on the microscope project includes. So for consistency we should probably leave it as `mrt create` for now -- we should probably change the commit in the long term.

**Comment by fsalbrechter** [comment]
Thanks a lot for your quick and helpful response! I know it's minor but I
think it can still confuse beginners.
keep up the awesome work!

**Comment by SachaG** [comment]
OK, so just to confirm we do recommend you use `mrt create` for the reasons outlined by Tom.
