### ISSUE TITLE
Pub/sub images seem to be broken

### ISSUE THREAD

**Issue by hackerfriendly** [DiscoverMeteor/book#216]
All of the images in chapter 4.5 seem to be broken today. The links are returning an empty template instead of images:

http://book.discovermeteor.com/images/diagrams/client-server@2x.png
http://book.discovermeteor.com/images/diagrams/collections-1@2x.png
http://book.discovermeteor.com/images/diagrams/collections-2@2x.png

Other chapters seem unaffected.

**Comment by SachaG** [comment]
That was a very weird bug related to some kind of problem with AWS. Should be better now :)
