### ISSUE TITLE
book.discovermeteor.com // Arbitrary account creation

### ISSUE THREAD

**Issue by johnnycrab** [DiscoverMeteor/book#217]
Hey,
I just wanted to let you know that on the website you can arbitrarily create user accounts. With a simple for-loop it's possible to create as many accounts as you like. Not that you can do anything with it, it simply clutters your db ;)
Maybe you'd like to change that with a simple `Accounts.config({forbidClientAccountCreation: true});` ?

Cheers,
Johnny

**Comment by SachaG** [comment]
I guess we could, we'll think about it. Although this is kind of a common problem for all Meteor apps I guess.

**Comment by johnnycrab** [comment]
It doesn't have to be. As far as I understand, an account is only created when purchasing the book.
You could use `Accounts.config({forbidClientAccountCreation: true})` and only create accounts when someone has bought the book...

**Comment by SachaG** [comment]
You're right, we do it. But so far it hasn't really been a problem so it's just not our top priority to address this right now.
