### ISSUE TITLE
404 for Extra Chapters is unclear; improvement suggestion

### ISSUE THREAD

**Issue by paulmolluzzo** [DiscoverMeteor/book#219]
There are a few chapters that are reserved for the higher-level packages (Migrations, RSS & API, et al), and if you visit the chapters pages _while logged in_ you hit a 404 page. You should consider adding something to that page to upsell the higher package that allows access, or instead, you can include some copy that indicates it's not actually "missing" it's just inaccessible for the User.

This issue isn't present if you're logged out since you show the login prompt.

**Comment by SachaG** [comment]
That's a great point, but how exactly did you end up on the extra chapter pages? You shouldn't see any link to them unless you have access?

**Comment by paulmolluzzo** [comment]
Via the [changelog](http://book.discovermeteor.com/changelog) or the [announcement post](https://www.discovermeteor.com/2014/01/15/the-discover-meteor-new-year-update/).

**Comment by SachaG** [comment]
Oh right. I'll definitely fix that.

**Comment by SachaG** [comment]
Fixed :)
