### ISSUE TITLE
Adding User Section

### ISSUE THREAD

**Issue by lowjumpingfrog** [DiscoverMeteor/book#220]
After adding the second user Meteor.users.find().count() = 2 not 1 as described.
![screen shot 2014-01-20 at 9 26 09 am](https://f.cloud.github.com/assets/235826/1955924/a6775900-81ef-11e3-9d89-c1215a73cef0.png)

**Comment by SachaG** [comment]
That's strange. Did you remove the `autopublish` package?

**Comment by lowjumpingfrog** [comment]
No the state of the code was exactly as the book suggests up to that point. Well, with the exception of the onWait cursor return in Router.configure as that did not work so that method was commented out.

**Comment by lowjumpingfrog** [comment]
OK, My bad I reviewed the lead up to this point and I see I neglected to turn off the auto publish package and put in the pub/subs and move main.js into the client folder. All behaviors described in the book are good for me now.
Too much caffeine I guess. Thanks!
