### ISSUE TITLE
meteor deploy ... -p vs. meteor deploy ... -P

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#224]
on page 19-20 of the PDF version the Password Protection section list the command:
$ meteor deploy myapp.meteor.com -p

I think the case on the option is wrong and should be -P (capital P)

**Comment by dwlf** [comment]
$ meteor --version
Release 0.7.2

Is the pdf version of the book versioned?

It doesn't look like:
deploy -p
or
deploy -P
are supported any more. Meteor immediately recommends setting a password on my account.

**Comment by tmeasday** [comment]
Good point. We should change the text of this section to better match the 0.7.1+ user experience.

**Comment by SachaG** [comment]
Updated.
