### ISSUE TITLE
Update to bootstrap 3 

### ISSUE THREAD

**Issue by isAlmogK** [DiscoverMeteor/book#229]
The book and code uses bootstrap 2, I suggest upgrading everything to bootstrap 3. Bootstrap 2 is a bit outdated and if someone uses 3 they will run into issues with the header and UI accounts. 

The update is pretty simple 
mrt add bootstrap-3 
mrt add meteor-accounts-ui-bootstrap-3 

You need to update the main navigation html I can send you what I have if you like

**Comment by SachaG** [comment]
You're right that bootstrap 3 is better, but upgrading would break a few things and require some work. We might do it later on when we revisit the code, but for now we'll probably stay with 2.0.
