### ISSUE TITLE
Request: Section on IDE setup for use with Meteor (WebStorm, Sublime, ...)

### ISSUE THREAD

**Issue by dgolds** [DiscoverMeteor/book#230]
You cover so many other 'getting started' areas, but setting up a good IDE would be much appreciated as a sidebar

**Comment by SachaG** [comment]
That's a good topic for a sidebar or a blog post, but I'm not really sure if there's much you can do in terms of setup, apart maybe from using [Tern-Meteor](https://github.com/Slava/tern-meteor).
