### ISSUE TITLE
router.js in Editing Post chapter missing loading template and requireLogin function

### ISSUE THREAD

**Issue by covingtondoan** [DiscoverMeteor/book#236]
I noticed that the router.js code was missing the loading template added in the Routing chapter and the requireLogin function changed from what we created in the Creating Posts chapter.

Changing router.js to match what's shown in the Editing Posts chapter breaks the app.

**Comment by SachaG** [comment]
Good point, I added the missing lines of code. 

And the requireLogin function changes in commit 7-4: https://github.com/DiscoverMeteor/Microscope/commit/chapter7-4
