### ISSUE TITLE
posts function missing from initial PostsListController code snippet

### ISSUE THREAD

**Issue by covingtondoan** [DiscoverMeteor/book#238]
The posts function missing from the initial PostsListController code snippet.

It appears in subsequent snippets.

**Comment by SachaG** [comment]
Can you clarify this? Do you mean in the Pagination chapter? Can you paste in the missing code?

**Comment by covingtondoan** [comment]
Yes, in the Pagination chapter > Creating a Route Controller

> lib/router.js snippet.

posts: function() {    return Posts.find({}, this.findOptions());  },

ᐧ
is missing after the waitOn function. It appears in the subsequent
lib/router.js snippet in the Adding A Load More Link section.

PostsListController = RouteController.extend({  template: 'postsList',
 increment: 5,   limit: function() {     return
parseInt(this.params.postsLimit) || this.increment;   },  findOptions:
function() {    return {sort: {submitted: -1}, limit: this.limit()};
},  waitOn: function() {    return Meteor.subscribe('posts',
this.findOptions());  },  posts: function() {    return Posts.find({},
this.findOptions());  },  data: function() {    var hasMore =
this.posts().count() === this.limit();    var nextPath =
this.route.path({postsLimit: this.limit() + this.increment});
return {      posts: this.posts(),      nextPath: hasMore ? nextPath :
null    };  }});

 lib/router.js

Covington

## 

[image: Follow @covingtondoan] http://twitter.com/covingtondoan [image:
View my LinkedIn profile] http://linkedin.com/in/covingtondoan [image:
Add +CovingtonDoan] http://plus.google.com/+CovingtonDoan

**Comment by SachaG** [comment]
Oh, got it. The code was right, but the highlighting was off. That function is actually created at the next step.
