### ISSUE TITLE
Text does not mention deleting the old postsList route from lib/router.js

### ISSUE THREAD

**Issue by covingtondoan** [DiscoverMeteor/book#240]
The text from the Voting chapter does not mention deleting the old postsList route from lib/router.js as seen on GitHub commit 3ae99fb.

**Comment by covingtondoan** [comment]
The delete callback in client/views/posts/post_edit.js should be updated too:

```
Template.postEdit.events({
  // ..

  'click .delete': function(e) {
    e.preventDefault();

    if (confirm("Delete this post?")) {
      // ..
      Router.go('home');
    }
  }
});
```

**Comment by SachaG** [comment]
Thanks for the heads up.
