### ISSUE TITLE
Can't see the interviews

### ISSUE THREAD

**Issue by isAlmogK** [DiscoverMeteor/book#241]
None of the interviews are showing up on the sidebar

**Comment by tmeasday** [comment]
Oh! You're right. Thanks for the report, fixed.

**Comment by isAlmogK** [comment]
Glad to help to help, by the way can we expect more content or extra chapters it would be cool to see more integration or examples. I would be up contributing

**Comment by tmeasday** [comment]
Right now we're focussing on getting things ready for the 0.8/blaze release and in general 1.0, but once things are settled there we'll probably look at some more extra chapters..

**Comment by isAlmogK** [comment]
Thanks for the info, looking forward to the update.
