### ISSUE TITLE
copy and paste from PDF loses formatting

### ISSUE THREAD

**Issue by dwlf** [DiscoverMeteor/book#243]
Example:

```
Meteor.publish('posts', function() { return Posts.find();
});
```

**Comment by dwlf** [comment]
I notice now this isn't true for all code examples.
Example:

```
<template name="loading">
  {{>spinner}}
</template>
```

**Comment by SachaG** [comment]
Not sure what's going on, I'm not that familiar with the intricacies of the PDF format. I would suggest just copy/pasting from the online version instead if possible.
