### ISSUE TITLE
atmosphere v2 brings new log in

### ISSUE THREAD

**Issue by dwlf** [DiscoverMeteor/book#244]
See https://github.com/percolatestudio/atmosphere-beta/issues/104

Current PDF text reads:
"Second Note: You'll need to login at http://atmosphere.meteor.com and create a username and password which you'll enter on the command line when you call mrt release .."

But visiting http://atmosphere.meteor.com automatically redirects you to https://atmospherejs.com/ and as atmosphere-beta 104 describes sign up and log in is currently a little buried and awkward.

**Comment by tmeasday** [comment]
Let's just point the link at http://atmosphere.meteor.com/accounts. I'll work to make that page more informative (https://github.com/percolatestudio/atmosphere-beta/issues/104#issuecomment-38693080) , and it'll have to do for now.

A MD account is what you'll use very soon..
