### ISSUE TITLE
could cover process.env

### ISSUE THREAD

**Issue by dwlf** [DiscoverMeteor/book#246]
could cover process.env, which also isn't explicitly covered at http://docs.meteor.com/

And looks like it won't be anytime soon, see https://github.com/meteor/meteor/issues/1961.

**Comment by gadicc** [comment]
Hope I addressed this adequately now on Meteorpedia:
http://meteorpedia.com/read/Environment_Variables

**Comment by dwlf** [comment]
@gadicc wow, meteorpedia.com is a treasure and the information you added on environment variables is the mother load!

**Comment by gadicc** [comment]
mother loads for the win haha.  thanks.

**Comment by SachaG** [comment]
That's outside of the scope of the book for now, so I'm glad to see that Meteorpedia covers it :)
