### ISSUE TITLE
Change Log - [13 – Voting]: Small change to the activeRouteClass helper.

### ISSUE THREAD

**Issue by isAlmogK** [DiscoverMeteor/book#248]
I can't see the following change, it looks the same can you explain a bit 

[13 – Voting]: Small change to the activeRouteClass helper.

**Comment by tmeasday** [comment]
From memory the change was just to put `Router.current() &&` in front.

**Comment by isAlmogK** [comment]
Thanks everything seems to be good, I do have an error with the rewind method for the voting controller but this might be something on my end. I'm currently checking this. 

Great update and glad there is support until version 1.0
