### ISSUE TITLE
Getting started: nitrous.io blog post gone

### ISSUE THREAD

**Issue by tknapstad** [DiscoverMeteor/book#250]
The section on using Nitrous.io in the Getting Started section references a blog post on how this is done, but the url returns a 404.

https://www.discovermeteor.com/2013/10/04/meteor-nitrous/
https://www.discovermeteor.com/blog/meteor-nitrous

Please restore the blog post (can still be accessed via Googles cache at http://goo.gl/yEh88b)

**Comment by daveit** [comment]
The correct URL is the same but without the month/day - so it should be
https://www.discovermeteor.com/blog/2013/meteor-nitrous/

**Comment by dwlf** [comment]
@daveit https://www.discovermeteor.com/blog/2013/meteor-nitrous/ -> 404 for me, though https://www.discovermeteor.com/blog/meteor-nitrous/ seems to work (again?)

**Comment by SachaG** [comment]
Fixed.
