### ISSUE TITLE
"Target" audience should be better articulated

### ISSUE THREAD

**Issue by dwlf** [DiscoverMeteor/book#252]
"Target" audience should be better articulated. The book should describe the pre-requisites and offer suggestions on how to fulfill them.

In "Why Meteor?" the pre-reqs are hinted at:
"More so than any other framework, Meteor makes it possible to get a real-time web app up and running on the web in a matter of hours. And if you've ever done front-end development before, you'll already be familiar with JavaScript and won't even need to learn a new language."

"Chapters & Sidebars" suggests "We wanted this book to be useful both for the novice Meteor user ..."

Not having any real experience with JavaScript, I'm regularly taking some deep breathes as I continue to try to learn by example.

I think https://www.meteor.com/learn-meteor has it right when it reads "The book is appropriate for Meteorites of all levels, though it does assume prior familiarity with JavaScript."

**Comment by SachaG** [comment]
Good point, in fact I thought we had a section like that.
