### ISSUE TITLE
It's node.js

### ISSUE THREAD

**Issue by dwlf** [DiscoverMeteor/book#254]
The meta issue hinted at in https://github.com/DiscoverMeteor/book/issues/246 is that the book would benefit from a section demonstrating that it is Node, what that means -- aka the benefits of that.

**Comment by SachaG** [comment]
Well, the book doesn't assume that people are familiar with Node (and in fact I myself am not). So although we might cover this in a sidebar one day, it's not really our main focus.

**Comment by dwlf** [comment]
I also don't know anything about Node.js, but to be successful -- at least today -- at Meteor, it looks like I need to know about Node aspects like process.env. As a newbie I wonder if because the mention of Node.js is so light that my vision was narrowed.

**Comment by SachaG** [comment]
I don't disagree, but it's not really the audience we're targeting with Discover Meteor, at least for now. Maybe in a second book? :)
