### ISSUE TITLE
PDF generation hangs in Safari

### ISSUE THREAD

**Issue by neuronsong** [DiscoverMeteor/book#259]
Just wanted to make you aware of the following issue:

I clicked the PDF link on the right to download a pdf version of the book.  Safari v 7.0.2 (9537.74.9) opens a new tab and attempts to load the pdf but never finishes.

Chrome v 33.0.1750.152, no problems.
Firefox v 26.0, no problems.

**Comment by SachaG** [comment]
Weird. Just tested it in 7.0.3 and it seemed to work. I'll close this for now, but we'll see if anybody else reports the same problem.
