### ISSUE TITLE
Include book version and reference to compatible Meteor version

### ISSUE THREAD

**Issue by jschulenklopper** [DiscoverMeteor/book#260]
I just downloaded the PDF of Discover Meteor with the updates for Meteor v0.8. The file download (title) nor the book contents contain a reference to 1) a version identification of the book, and 2) a reference to the Meteor version the book is compatible with. Also, the PDF download does not contain the changelog that could fulfill that need as well.

Wouldn't it be nice if the book (download) contains some note on page 2 like: "This is version x.y.z of the book, generated on April 8, 2014. The text and code examples are compatible with Meteor 0.8."?

**Comment by SachaG** [comment]
That's a good suggestion, we'll think about how to do it.

**Comment by SachaG** [comment]
Done :)

**Comment by jschulenklopper** [comment]
+1, excellent, thanks. Can't wait for the next update.
