### ISSUE TITLE
isolate and constant blocks?

### ISSUE THREAD

**Issue by rainbough** [DiscoverMeteor/book#261]
I noticed you have a discussion of the isolate and constant blocks in the chapter 11.5 sidebar. Are they still usable after the 0.8 update? It appears that they have been deprecated. 

https://github.com/meteor/meteor/wiki/Using-Blaze#no-more-constant-isolate-or-preserve

**Comment by SachaG** [comment]
You're right, we should remove this part. Good catch, Thanks :)
