### ISSUE TITLE
Discover Meteor code for 14-1 post_item.js doesn't agree with github commit

### ISSUE THREAD

**Issue by Cheerazar** [DiscoverMeteor/book#265]
In the book the /client/views/posts/post_item.js helpers function attributes uses the var offset, whereas the github 14-1 commit uses the variable delta on line 27.

![screen shot 2014-04-17 at 4 09 46 pm](https://cloud.githubusercontent.com/assets/5581107/2736378/72d8d35a-c66c-11e3-9d74-7866ae7c70c1.png)
![screen shot 2014-04-17 at 4 10 57 pm](https://cloud.githubusercontent.com/assets/5581107/2736380/74ba9708-c66c-11e3-9af2-6f2db87692d4.png)

**Comment by SachaG** [comment]
Sorry about that, I thought `offset` was a more explicit term. But we do need to change it in the code, too.
