### ISSUE TITLE
Template.rendered in Blaze?

### ISSUE THREAD

**Issue by a-vikulin** [DiscoverMeteor/book#266]
At the end of Chapter 9 - Errors the book says:
"A template's rendered callback triggers every time it's rendered in the browser. This of course includes the first time it pops up on the screen, but it's important to remember that the callback will also fire every time the template is re-rendered, e.g. every time any of its data changes.

Rendered callbacks will typically fire at least twice: first when the app initially loads, and a second time once collection data has been loaded. So you should be careful when putting any code that shouldn't fire twice (such as an alert, or analytics event tracking code) in them."

Is it still relevant in Blaze?

**Comment by a-vikulin** [comment]
From here: https://github.com/meteor/meteor/wiki/Using-Blaze#rendered-callback-only-fires-once
The rendered callback now only fires once per template instance, when the template is first rendered into the DOM. Template instances are never re-rendered in the new rendering model. We expect this to greatly simplify dealing with the rendered callback!

**Comment by SachaG** [comment]
You're right, I'll just remove this part altogether.
