### ISSUE TITLE
postAttributes.url being empty would not seem to imply "This link has already been posted"

### ISSUE THREAD

**Issue by dwlf** [DiscoverMeteor/book#268]
postAttributes.url being empty would not seem to imply "This link has already been posted"

The "Meteor Method: Better Abstraction and Security" section code looks to have a logic error, or at the least distracting code.
https://github.com/DiscoverMeteor/Microscope/commit/chapter7-6#commitcomment-6116296

My comment there is "Why is postAttributes.url checked here? You've already used postAttributes.url to Posts.findOne() and if it is empty here then you are returning the wrong error message."

**Comment by SachaG** [comment]
Sorry for the (very) delayed reply! I think the thinking behind this is that we let you submit posts with no URLs as well. Maybe we shouldn't do that though.
