### ISSUE TITLE
first one (error) will be 302 (the meaning of life)

### ISSUE THREAD

**Issue by dwlf** [DiscoverMeteor/book#269]
"Meteor Method: Better Abstraction and Security" section introduces errors with:

> Next, if there’s another post with the same URL, we throw a 302 error (which means redirect) telling the user that they should just go and look at that previously created post.
> 
> Meteor’s Error class takes three arguments. The first one (error) will be the 302 numeric code, the second one (reason) is a short human-readable explanation of the error, and the last one (details) can be any useful additional information.

Your description of Meteor's Error class oddly starts by saying it is a 302 numeric code and then after is general as expected. The first one (error) can be an arbitrary integer. 

It would be great if this section described why 401 and 422 are used as the other error codes.

**Comment by SachaG** [comment]
Do you mean that the book makes it sound like it _has_ to be "302"? You can put in any number you want, so if that's how it comes across I'll change it.

**Comment by dwlf** [comment]
Yes, the book makes it sound like to me the error codes are prescriptive and have special meaning, "302 error (which means redirect)". I looked it up to be sure and the official docs "likely" seems like the essential details, "A numeric error code, likely similar to an HTTP code (eg, 404, 500)." 

The second paragraph should be general throughout and as you say something like, "Meteor’s Error class takes three arguments. The first one (error) is any number you want, ..."

**Comment by dwlf** [comment]
Aside, after looking at the official docs, I'm not sure if they need to be unique error numbers, but my guess would be not though I don't have any need to confirm.
