### ISSUE TITLE
Animations: post_item.js code block nit

### ISSUE THREAD

**Issue by CreatingAdam** [DiscoverMeteor/book#275]
This is very minor and didn't snag me, but I could see it potentially impacting the casual copy-paster. In the first code block for post_item.js in this chapter, we are adding a the new attributes helper to the existing list of postItem helpers. It might be nice to show that we must also add a comma to the previous closing bracket for the upvotedClass helper so that the code block reads:

``` js
var POST_HEIGHT = 80;
var Positions = new Meteor.Collection(null);
Template.postItem.helpers({
  //..
  },
  attributes: function() {
    var post = _.extend({}, Positions.findOne({postId: this._id}), this);
    var newPosition = post._rank * POST_HEIGHT;
    var attributes = {};
    if (! _.isUndefined(post.position)) {
      var offset = post.position - newPosition;      
      attributes.style = "top: " + offset + "px";
      if (offset === 0)
        attributes.class = "post animate"
    }
    Meteor.setTimeout(function() {
      Positions.upsert({postId: post._id}, {$set: {position: newPosition}})
    });
    return attributes;
  }
});
//..
```

This is a big comment for a tiny comma, but I thought it might be helpful since you do go through the trouble of highlighting all new code changes. Cheers.

**Comment by SachaG** [comment]
Good idea, thanks.
