### ISSUE TITLE
chapter/comments 'Controlling the Comments Subscription' lib/router.js

### ISSUE THREAD

**Issue by pdavidow** [DiscoverMeteor/book#276]
It seems that in chapter/comments 'Controlling the Comments Subscription' lib/router.js, the top part of the method also needs to be modified:

Router.configure({
  layoutTemplate: 'layout',
  loadingTemplate: 'loading',
  waitOn: function() {
    //return [Meteor.subscribe('posts'), Meteor.subscribe('comments')];
    return [Meteor.subscribe('posts')];
  }
});

**Comment by SachaG** [comment]
Good point :)
