### ISSUE TITLE
Chapter 2: missing dependency (MongoDB)

### ISSUE THREAD

**Issue by elegos** [DiscoverMeteor/book#278]
The very first time you start microscope via the `meteor` command, if you haven't installed MongoDB yet, Meteorjs will stall trying to execute it. You don't mention anywhere in the chapter about installing it. I took one second to understand the issue, maybe other people may be less-practised resolving this kind of problems.

**Comment by tmeasday** [comment]
@elegos - I'm not sure I've experienced the issue you are describing. Can you provide a little more detail?

**Comment by elegos** [comment]
Under the subsection 'Creating a Simple App', you ask the user to start the microscope app (entering the directory and executing meteor). It requires MongoDB to be installed, otherwise it will hang trying to start it.

**Comment by tmeasday** [comment]
Meteor comes bundled with Mongo. Which OS is this on?

**Comment by elegos** [comment]
I've tried running it under Debian "wheezy". Maybe the first time it takes longer to load (I waited for around 30 seconds before killing (CTRL+C) the app) and I installed the indipendent MongoDB uselessy.

**Comment by tmeasday** [comment]
Yeah sometimes it can take a long time to start the first time you run it. We should perhaps put something in about this..

**Comment by elegos** [comment]
Yep. Thanks for the support :)
