### ISSUE TITLE
[Chapter 5 - Routing] Loading template is not being shown

### ISSUE THREAD

**Issue by elegos** [DiscoverMeteor/book#281]
Hello!

I've noticed that neither the local version neither the online instance show the loader before the contents being actually loaded: what I see is the same webpage with no contents as before (before loading the contents). Is this a bug, or am I missing anything?

Thanks :)

**Comment by SachaG** [comment]
I just tested locally and I do see the loader. Which commit specifically are you talking about?

**Comment by elegos** [comment]
chapter5-3. Strange though, now I can too see the spinner...
