### ISSUE TITLE
Ch. 5, Routing - Typo

### ISSUE THREAD

**Issue by DerekParrySLC** [DiscoverMeteor/book#283]
I believe the paranthetical "(as a convention, we'll designate this special template as the "route templates" from now on)" has a typo. "route templates" should be singular--"route template"--to match its singular predecessor. Alternatively, it should read "we'll designate these special templates as "route templates" from now on)".

Hopefully this helps. You've written a fantastically helpful book.

**Comment by SachaG** [comment]
Thanks!
