### ISSUE TITLE
[Disqus] Threads are not being updated from chapter to chapter

### ISSUE THREAD

**Issue by elegos** [DiscoverMeteor/book#286]
Hello!

I've noticed that if you click on the next/previous chapter buttons, the Disqus thread won't update, pointing to the one you've accessed first.

i.e.

You navigate to chapter 5, then the Disqus [chapter 5] will load. If you finish reading the chapter and follow the book going to chapter 6, the Disquss thread will still point to chapter 5.

**Comment by Nauzer** [comment]
Noted the same... already made some mistakes in posting a thread in the wrong part of the website due to that

**Comment by SachaG** [comment]
Fixed :)
