### ISSUE TITLE
Link to Spacebars Documentation has no href url

### ISSUE THREAD

**Issue by hellobrian** [DiscoverMeteor/book#287]
In Chapter 3 (Templates), there's a link that reads Spacebars documentation. 
Inspecting the element shows there's no url provided for that anchor tag. 
Here's a link to the chapter: http://book.discovermeteor.com/chapter/templates

I'm guessing the following link is the Spacebars documentation you wanted us to refer to? https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md

Cheers

**Comment by SachaG** [comment]
Good catch, thanks!
