### ISSUE TITLE
Chapter 9 - Clearing Errors

### ISSUE THREAD

**Issue by Nauzer** [DiscoverMeteor/book#288]
Hi all,

Been playing around with the statements made in the beginning of this section a bit:

"Now you might have tried clicking the error's close button. If you did, you would see the error disappear, only to return as soon as you loaded another page. What's going on?" 

However it seems that the behavior locally is a bit different from the behavior on the books instance with 9-2 chapter.

If I launch the 9-2 GitHub instance (http://meteor-book-chapter9-2.meteor.com) I see that when I perform the following steps:
- add a duplicate URL (which throws an error)
- I close that error (removing it from DOM only)
- do another duplicate URL post (throwing another error)
  Result: I see 2 errors according to expectations as explained in the chapter. 

However with my local codebase and also and when I download and run the 9-2 GitHub commit code, the behavior is that the 'closed' alert is not reappearing when generating the 2nd alert... 

Any suggestions on where this difference comes from in the usage of Local Collections?

I have reproduced the above behavior on Meteor 0.8.0 and 0.8.1.2.

Thanks in advance for any leads...

**Comment by SachaG** [comment]
I think you're right, this might be due to the new UI engine in 0.8. I'll update the book, thanks for the heads up!
