### ISSUE TITLE
{{#if currentUser}} should be high lighted in green bc it is new code. 

### ISSUE THREAD

**Issue by jdbrown371** [DiscoverMeteor/book#295]
http://book.discovermeteor.com/chapter/comments
![discover_meteor](https://cloud.githubusercontent.com/assets/2693033/3149769/69439b92-ea6e-11e3-9fd6-b496f288a95b.jpg)

<template name="postPage">
  {{> postItem}}
  <ul class="comments">
    {{#each comments}}
      {{> comment}}
    {{/each}}
  </ul>
  {{#if currentUser}}
    {{> commentSubmit}}
  {{else}}
    <p>Please log in to leave a comment.</p>
  {{/if}}
</template>
client/views/posts/post_page.html

**Comment by SachaG** [comment]
Thanks :)
