### ISSUE TITLE
Advanced Publication Code

### ISSUE THREAD

**Issue by calirails** [DiscoverMeteor/book#299]
Hi, I purchased the book and try to work through each sidebar and encountered what I believe are 2 discrepancies with sidebar13-5 code for the solution for publishing multiple collections with a single publication.

First the code based on the version of the book I have: 
Meteor.publish('topPosts', function(limit) {
var sub = this, commentHandles = [], postHandle = null;
  // send over the top two comments attached to a single post
function publishPostComments(postId) {
var commentsCursor = Comments.find({postId: postId}, {limit: 2}); commentHandles[post._id] =
      Meteor.Collection._publishCursor(commentsCursor, sub, 'comments');
  }
postHandle = Posts.find({}, {limit: limit}).observeChanges({ added: function(id, post) {
      publishPostComments(post._id);
      sub.added('posts', id, post);
    },
changed: function(id, fields) { sub.changed('posts', id, fields);
},
removed: function(id) {
      // stop observing changes on the post's comments
commentHandles[id] && commentHandles[id].stop(); // delete the post
sub.removed('posts', id);
} });
  sub.ready();
// make sure we clean everything up (note `_publishCursor` // does this for us with the comment observers) sub.onStop(function() { postsHandle.stop(); });
});

Potential errors
1. Using meteor 0.8.2, I found errors that resulted in errors in the publication that suggested the first parameter being passed into the added function was the 'post' instance itself rather than the id, then the post. Will you confirm or clarify if I am mistaken?

I changed this block from:
added: function(id, post) {
      publishPostComments(post._id);
      sub.added('posts', id, post);
    },
to:
added: function(post) {
            publishPostComments(post);
            sub.added('posts', post, post._id);
        },
1. The function seems to reference a local variable by the wrong name, so I changed
   sub.onStop(function() { postsHandle.stop(); });
   to
   sub.onStop(function() { postHandle.stop(); });
2. I am having troubles putting it all together even after the code fixes and could really use specific pointers on understanding how to reference the 'added' or 'joined comments collection' from the client side code to display the comments on the main post item template. 

Please tell me where I should post this question if this is the wrong forum. I couldn't find the location of what the book refers to in this comment: 'Finally, for every other question you can also just leave us a comment in this app’s side panel.'

After I got the 'topPosts' publication corrected and modified my controller (formerly code in router), I wasn't able to show my 'comments collection' in my view template. Here is what I tried: 
1. in publications.js, I fixed publication code
2. in posts_list_controller.js, I modified PostsListController (base) waitOn function to use new publication
PostsListController = RouteController.extend({
    template: 'postsList',
    increment: 5,
    limit: function() { 
        // console.log('postLimit param is: ' + parseInt(this.params.postLimit));
        return parseInt(this.params.postLimit) || this.increment;
    },
    sort: {submittedAt: -1},
    waitOn: function() { 
        return Meteor.subscribe('topPosts', this.sort, 3); 
    },
3. in post_item.js, I added custom helper on post-item view to add the 'joined' comments with this code:
Template.postItem.helpers({
    domain: function(){
        var a = document.createElement('a');
        a.href = this.url
        return a.hostname;
    },
    ownPost: function() {
        return this.userId && Meteor.user() ? Meteor.user()._id === this.userId : false;
    },
    upVoteAllowed: function() {
        var userId = Meteor.userId();
        if (userId) {//&& !_.include(this.upVoters, userId)) {
            return 'btn-primary upVoteable';
        } else {
            return 'disabled';
        }
    },
    joinedComments: function() {
        return Comments.find({postId: this._id});
    }
});
4. in post_item.html template, I added code to try and iterate over the 'joinedComments' but I don't get any objects even for the posts I indeed have comments for if I go to the post_page.html view. Here is that entire source file with the added unordered list:
<template name="postItem">
    <div class='post'>
        <a href='#' class='upvote btn {{upVoteAllowed}}'>⬆</a>
        <div class='post-content'>
            <h3>
                <a href='{{url}}'>{{title}}</a><span>{{domain}}</span>
            </h3>
            <div class='edit-post'>  
                {{#if ownPost}}
                    <a href={{pathFor 'postEdit'}}>Edit</a>
                {{/if}}
            </div>
            <p>
                
                {{pluralize votes 'vote'}},
                submitted by {{author}}, 
                <a href={{pathFor 'postPage'}}>{{pluralize commentsCount 'comment'}}</a>
            </p>
            <ul class='recent-comments'>
                {{#each joinedComments}}
                    {{> comment}}
                {{/each}}
            </ul>
        </div>
        <a href="{{pathFor 'postPage'}}" class='discuss btn'>Discuss</a> 
    </div>
</template>

**Comment by tmeasday** [comment]
Hi @calirails 
1. It's possible the code in the advanced publications chapter doesn't exactly work as written -- it is intended more as indicative psuedo-code -- there are a few cases that it doesn't cover (like items being deleted etc). But I'm glad you managed to get it working.
2. I'm not sure about the second question as I can't really read the code you posted. Try wrapping your code blocks in triple backticks (`) to make it format better.

**Comment by calirails** [comment]
Thanks for reply. I've wrapped code blocks in the triple backticks now. Hopefully the triple backticks  allows me to wrap entire functions and blocks rather than a single line. My question is repeated at the end.

step 0. I changed publication.js to following code to also include the associated comments
'''
Meteor.publish('topPosts', function(sort, limit) {
    var sub = this, commentHandles = [], postHandle = null;

```
// send over the top two comments attached to a single post
function publishPostComments(post) {
    var commentsCursor = Comments.find({postId: post._id}, {limit: 2}); 
    commentHandles[post._id] = Meteor.Collection._publishCursor(commentsCursor, sub, 'comments');
}

postHandle = Posts.find({}, {sort: sort, limit: limit}).observeChanges({ 
    added: function(post) {
        publishPostComments(post);
        sub.added('posts', post, post._id);
    },

    changed: function(id, fields) { 
        sub.changed('posts', id, fields);
    },

    removed: function(id) {
        // stop observing changes on the post's comments
        commentHandles[id] && commentHandles[id].stop(); // delete the post
        sub.removed('posts', id);
    }
});

sub.ready();
// make sure we clean everything up (note `_publishCursor` // does this for us with the comment observers) 
sub.onStop(function() { postHandle.stop(); });
```

});
'''
step 1. In posts_list_constroller.js, I've subscribed to the new publication
'''
PostsListController = RouteController.extend({
    template: 'postsList',
    increment: 5,
    limit: function() { 
        // console.log('postLimit param is: ' + parseInt(this.params.postLimit));
        return parseInt(this.params.postLimit) || this.increment;
    },
    sort: {submittedAt: -1},
    waitOn: function() { 
        return Meteor.subscribe('topPosts', this.sort, 3); 
    },
    posts: function() {
        return Posts.find({}, {sort: this.sort, limit: this.limit()});
    },
    data: function() {  
        var hasMore = (this.posts().count() === this.limit()) ? true : false;
        // var nextPath = this.route.path({postLimit: this.limit() + this.limit()});

```
    return { 
        posts: this.posts(),
        nextPath: hasMore ? this.nextPath() : null
    };
}
```

});
'''

step 2. I've added a helper method in post_item.js named 'joinedComments' to return the associated comments for the 'current' post:
'''
Template.postItem.helpers({
    domain: function(){
        var a = document.createElement('a');
        a.href = this.url
        return a.hostname;
    },
    ownPost: function() {
        return this.userId && Meteor.user() ? Meteor.user()._id === this.userId : false;
    },
    upVoteAllowed: function() {
        var userId = Meteor.userId();
        if (userId) {//&& !_.include(this.upVoters, userId)) {
            return 'btn-primary upVoteable';
        } else {
            return 'disabled';
        }
    },
    joinedComments: function() {
        return Comments.find({postId: this._id});
    }
});
'''
step 3. I modified the template file, post_item.html by adding the unordered list that attempts to iterate over the 'joinedComments' to display the 'top' 2 comments.
'''
<template name="postItem">
    <div class='post'>
        <a href='#' class='upvote btn {{upVoteAllowed}}'>⬆</a>
        <div class='post-content'>
            <h3>
                <a href='{{url}}'>{{title}}</a><span>{{domain}}</span>
            </h3>
            <div class='edit-post'>  
                {{#if ownPost}}
                    <a href={{pathFor 'postEdit'}}>Edit</a>
                {{/if}}
            </div>
            <p>
                
                {{pluralize votes 'vote'}},
                submitted by {{author}}, 
                <a href={{pathFor 'postPage'}}>{{pluralize commentsCount 'comment'}}</a>
            </p>
            <ul class='recent-comments'>
                {{#each joinedComments}}
                    {{> comment}}
                {{/each}}
            </ul>
        </div>
        <a href="{{pathFor 'postPage'}}" class='discuss btn'>Discuss</a> 
    </div>
</template>
'''

I can inspect the page and see the <ul class='recent-comments'></ul> and it appears the 'joinedComments' is either null or empty. What is the right way to retrieve and access the comments collection in the context of the 'topPosts' publication?

**Comment by calirails** [comment]
I got mixed results with code formatting and will try adding the helper and template code only again:
helper code: 
'''
joinedComments: function() {
        return Comments.find({postId: this._id});
    }
'''
template code:
'''

<ul class='recent-comments'>
                {{#each joinedComments}}
                    {{> comment}}
                {{/each}}
            </ul>

'''

**Comment by tmeasday** [comment]
Hi @calirails -- you need to use the backtick (the "`" -- usually combined with the tilde (~) key).

**Comment by calirails** [comment]
OK, my bad. Thanks for clarifying. Third time should be the charm.
// publications.js: added 'topPosts' publication code

```
Meteor.publish('topPosts', function(sort, limit) {
    var sub = this, commentHandles = [], postHandle = null;

    // send over the top two comments attached to a single post
    function publishPostComments(post) {
        var commentsCursor = Comments.find({postId: post._id}, {limit: 2}); 
        commentHandles[post._id] = Meteor.Collection._publishCursor(commentsCursor, sub, 'comments');
    }

    postHandle = Posts.find({}, {sort: sort, limit: limit}).observeChanges({ 
        added: function(post) {
            publishPostComments(post);
            sub.added('posts', post, post._id);
        },

        changed: function(id, fields) { 
            sub.changed('posts', id, fields);
        },

        removed: function(id) {
            // stop observing changes on the post's comments
            commentHandles[id] && commentHandles[id].stop(); // delete the post
            sub.removed('posts', id);
        }
    });

    sub.ready();
    // make sure we clean everything up (note `_publishCursor` // does this for us with the comment observers) 
    sub.onStop(function() { postHandle.stop(); });
});
```

// posts_list_controller: code that subscribes to 'topPosts' publication

```
PostsListController = RouteController.extend({
    template: 'postsList',
    increment: 5,
    limit: function() { 
        // console.log('postLimit param is: ' + parseInt(this.params.postLimit));
        return parseInt(this.params.postLimit) || this.increment;
    },
    sort: {submittedAt: -1},
    waitOn: function() { 
        return Meteor.subscribe('topPosts', this.sort, 3); 
    },
    posts: function() {
        return Posts.find({}, {sort: this.sort, limit: this.limit()});
    },
    data: function() {      
        var hasMore = (this.posts().count() === this.limit()) ? true : false;
        // var nextPath = this.route.path({postLimit: this.limit() + this.limit()});

        return { 
            posts: this.posts(),
            nextPath: hasMore ? this.nextPath() : null
        };
    }
});
```

// post_item.js: template helper code with added 'joinedComments' method that returns last 2 comments

```
Template.postItem.helpers({
    domain: function(){
        var a = document.createElement('a');
        a.href = this.url
        return a.hostname;
    },
    ownPost: function() {
        return this.userId && Meteor.user() ? Meteor.user()._id === this.userId : false;
    },
    upVoteAllowed: function() {
        var userId = Meteor.userId();
        if (userId) {//&& !_.include(this.upVoters, userId)) {
            return 'btn-primary upVoteable';
        } else {
            return 'disabled';
        }
    },
    joinedComments: function() {
        return Comments.find({postId: this._id});
    }
});
```

//post_item.html: the template code with attempt to add the <ul> that renders most recent 2 comments
```<template name="postItem">
    <div class='post'>
        <a href='#' class='upvote btn {{upVoteAllowed}}'>⬆</a>
        <div class='post-content'>
            <h3>
                <a href='{{url}}'>{{title}}</a><span>{{domain}}</span>
            </h3>
            <div class='edit-post'>  
                {{#if ownPost}}
                    <a href={{pathFor 'postEdit'}}>Edit</a>
                {{/if}}
            </div>
            <p>
                <!-- Note we don't use () and don't have a comma to separate arguments in method call -->
                {{pluralize votes 'vote'}},
                submitted by {{author}}, 
                <a href={{pathFor 'postPage'}}>{{pluralize commentsCount 'comment'}}</a>
            </p>
            <ul class='recent-comments'>
                {{#each joinedComments}}
                    {{> comment}}
                {{/each}}
            </ul>
        </div>
        <a href="{{pathFor 'postPage'}}" class='discuss btn'>Discuss</a> 
    </div>
</template>

```
```

**Comment by calirails** [comment]
The template file with html file is garbled. Giving that file one more try.

```
<template name="postItem">
    <div class='post'>
        <a href='#' class='upvote btn {{upVoteAllowed}}'>⬆</a>
        <div class='post-content'>
            <h3>
                <a href='{{url}}'>{{title}}</a><span>{{domain}}</span>
            </h3>
            <div class='edit-post'>             
                {{#if ownPost}}
                    <a href={{pathFor 'postEdit'}}>Edit</a>
                {{/if}}
            </div>
            <p>
                <!-- Note we don't use () and don't have a comma to separate arguments in method call -->
                {{pluralize votes 'vote'}},
                submitted by {{author}}, 
                <a href={{pathFor 'postPage'}}>{{pluralize commentsCount 'comment'}}</a>
            </p>
            <ul class='recent-comments'>
                {{#each joinedComments}}
                    {{> comment}}
                {{/each}}
            </ul>
        </div>
        <a href="{{pathFor 'postPage'}}" class='discuss btn'>Discuss</a> 
    </div>
</template>
```

**Comment by tmeasday** [comment]
Hey @calirails - perhaps if you edit your original question (or maybe just open a new issue?) and fix up the formatting, it might be clearer for those who find this issue in the future.

I think the question you are asking is why you are seeing no comments in the `{{#each joinedComments}}` block? I would try the following things:
1. What do you see if you do `Comments.find().fetch()` in the browser console?
2. If they aren't there, are you sure this post has comments?
3. If it does, perhaps put some logging in the publication to see if it finds them (e.g. do `console.log(Comments.find({postId: post._id}, {limit: 2}).count())` inside `publishPostComments()`.

**Comment by calirails** [comment]
Yes, great suggestion. I will clean up code and repost question after trying your suggestions in case it helps refine my question and make it more concise. Thank you!
