### ISSUE TITLE
Variable names: e vs event

### ISSUE THREAD

**Issue by matb33** [DiscoverMeteor/book#3]
Very minor, and likely comes from having two different authors! But for the sake of consistency, probably a good idea to pick one and go with it. I see `event` being used:
http://book.discovermeteor.com/chapter/creating-posts/

And then, just `e`:
http://book.discovermeteor.com/chapter/editing-posts/

Personally, I like the short `e`. It holds a special place in my heart, like the `i` variable in for loops ;-)

**Comment by SachaG** [comment]
Good point. We'll probably batch all those changes together because every time we change the app's actual code we have to re-do all git tags manually, so I'll keep this open for now.

**Comment by SachaG** [comment]
We've decided to use `e` everywhere from now on.
