### ISSUE TITLE
Advanced Publications: unable to access and display Comments

### ISSUE THREAD

**Issue by calirails** [DiscoverMeteor/book#301]
I am working through code with sidebar13-5 that publishes both the Posts and Comments collections with a single publication named 'topPosts' and need some pointers on what I am doing wrong and how I can successfully display associated comments with the post on the route that uses the custom 'topPosts' publication.

Here are my observations:
1. Of the first page of posts, there are some posts that have 1 comment and another that has 5 comments. 
2. Comments are empty as Comments.find().fetch() returns an empty array
3. Adding `console.log('Inside publishPostComments, for the current post comment count is: ' + Comments.find({postId: post._id}, {limit: 2}).count());` shows that the associated comments count is empty. Screenshot is attached towards the end.

Here is the associated source code:
// publications.js: added 'topPosts' custom publication

```
Meteor.publish('topPosts', function(sort, limit) {
    var sub = this, commentHandles = [], postHandle = null;

    // send over the top two comments attached to a single post
    function publishPostComments(post) {
        var commentsCursor = Comments.find({postId: post._id}, {limit: 2}); 
        commentHandles[post._id] = Meteor.Collection._publishCursor(commentsCursor, sub, 'comments');
    }

    postHandle = Posts.find({}, {sort: sort, limit: limit}).observeChanges({ 
        added: function(post) {
            publishPostComments(post);
            sub.added('posts', post, post._id);
        },

        changed: function(id, fields) { 
            sub.changed('posts', id, fields);
        },

        removed: function(id) {
            // stop observing changes on the post's comments
            commentHandles[id] && commentHandles[id].stop(); // delete the post
            sub.removed('posts', id);
        }
    });

    sub.ready();
    // make sure we clean everything up (note `_publishCursor` // does this for us with the comment observers) 
    sub.onStop(function() { postHandle.stop(); });
});
```

// posts_list_controller: code that subscribes to 'topPosts' publication

```
PostsListController = RouteController.extend({
    template: 'postsList',
    increment: 5,
    limit: function() { 
        // console.log('postLimit param is: ' + parseInt(this.params.postLimit));
        return parseInt(this.params.postLimit) || this.increment;
    },
    sort: {submittedAt: -1},
    waitOn: function() { 
        return Meteor.subscribe('topPosts', this.sort, 3); 
    },
    posts: function() {
        return Posts.find({}, {sort: this.sort, limit: this.limit()});
    },
    data: function() {      
        var hasMore = (this.posts().count() === this.limit()) ? true : false;
        // var nextPath = this.route.path({postLimit: this.limit() + this.limit()});

        return { 
            posts: this.posts(),
            nextPath: hasMore ? this.nextPath() : null
        };
    }
});
```

// post_item.js: template helper code with added 'joinedComments' method that returns last 2 comments

```
Template.postItem.helpers({
    domain: function(){
        var a = document.createElement('a');
        a.href = this.url
        return a.hostname;
    },
    ownPost: function() {
        return this.userId && Meteor.user() ? Meteor.user()._id === this.userId : false;
    },
    upVoteAllowed: function() {
        var userId = Meteor.userId();
        if (userId) {//&& !_.include(this.upVoters, userId)) {
            return 'btn-primary upVoteable';
        } else {
            return 'disabled';
        }
    },
    joinedComments: function() {
        return Comments.find({postId: this._id});
    }
});
```

//post_item.html: the template code with attempt to add the <ul> that renders most recent 2 comments

```
<template name="postItem">
    <div class='post'>
        <a href='#' class='upvote btn {{upVoteAllowed}}'>⬆</a>
        <div class='post-content'>
            <h3>
                <a href='{{url}}'>{{title}}</a><span>{{domain}}</span>
            </h3>
            <div class='edit-post'>             
                {{#if ownPost}}
                    <a href={{pathFor 'postEdit'}}>Edit</a>
                {{/if}}
            </div>
            <p>
                <!-- Note we don't use () and don't have a comma to separate arguments in method call -->
                {{pluralize votes 'vote'}},
                submitted by {{author}}, 
                <a href={{pathFor 'postPage'}}>{{pluralize commentsCount 'comment'}}</a>
            </p>
            <ul class='recent-comments'>
                {{#each joinedComments}}
                    {{> comment}}
                {{/each}}
            </ul>
        </div>
        <a href="{{pathFor 'postPage'}}" class='discuss btn'>Discuss</a> 
    </div>
</template>
```

Here is the screenshot of the first page that has 5 posts, of which 2 have comments that I cannot display but yet the denormalized comments count shows and confirms their existence if I go to the detailed (post_page.html) post route.
![image](https://cloud.githubusercontent.com/assets/942698/3425929/3d9a5768-0014-11e4-80fb-151aea298e29.png)

Here is the screenshot of the meteor server console that logs inside the 'publishPostComments' function as part of the new publication.
![image](https://cloud.githubusercontent.com/assets/942698/3425937/69364ac6-0014-11e4-8727-14c63433701c.png)

If I click on the link with the 'comments count' and go to the post page, I see the comments for the 3rd and 5th post. The comments data in the publication doesn't seem to reconcile with the persisted data and need help identifying my mistake.

**Comment by tmeasday** [comment]
Hi @calirails - I think the issue is that the api to `observeChanges` is slightly different to what you have here (http://docs.meteor.com/#observe_changes) and the added callback looks like `added(id, doc)`

**Comment by calirails** [comment]
I get errors (attached below) when I change the publication code to match the documenation.

```
Meteor.publish('topPosts', function(sort, limit) {
    var sub = this, commentHandles = [], postHandle = null;

    // send over the top two comments attached to a single post
    function publishPostComments(postId) {
        var commentsCursor = Comments.find({postId: postId}, {limit: 2}); 
        commentHandles[postId] = Meteor.Collection._publishCursor(commentsCursor, sub, 'comments');
        console.log('Inside publishPostComments, for the current post comment count is: ' + Comments.find({postId: postId}, {limit: 2}).count());
    }

    postHandle = Posts.find({}, {sort: sort, limit: limit}).observeChanges({ 
        added: function(id, post) {
            publishPostComments(id);
            sub.added('posts', post, id);
        },

        changed: function(id, fields) { 
            sub.changed('posts', id, fields);
        },

        removed: function(id) {
            // stop observing changes on the post's comments
            commentHandles[id] && commentHandles[id].stop(); // delete the post
            sub.removed('posts', id);
        }
    });

    sub.ready();
    // make sure we clean everything up (note `_publishCursor` // does this for us with the comment observers) 
    sub.onStop(function() { postHandle.stop(); });
});
```

These are the errors that led me to changes the code.
![image](https://cloud.githubusercontent.com/assets/942698/3426024/6c0ad57a-0017-11e4-9a6b-099693e7c0ce.png)

**Comment by tmeasday** [comment]
You have the arguments in the wrong order to `sub.added`: (it should be `sub.added('posts', id, post)`)

**Comment by calirails** [comment]
Changing the parameters on both the function and method call seems to help but the Comments on the client are still empty even thought the server log says it finds some comments as evident by the count.

```
Meteor.publish('topPosts', function(sort, limit) {
    var sub = this, commentHandles = [], postHandle = null;

    // send over the top two comments attached to a single post
    function publishPostComments(postId) {
        var commentsCursor = Comments.find({postId: postId}, {limit: 2}); 
        commentHandles[postId] = Meteor.Collection._publishCursor(commentsCursor, sub, 'comments');
        console.log('Inside publishPostComments, for the current post comment count is: ' + Comments.find({postId: postId}, {limit: 2}).count());
    }

    postHandle = Posts.find({}, {sort: sort, limit: limit}).observeChanges({ 
        added: function(id, post) {
            publishPostComments(id);
            sub.added('posts', id, post);
        },

        changed: function(id, fields) { 
            sub.changed('posts', id, fields);
        },

        removed: function(id) {
            // stop observing changes on the post's comments
            commentHandles[id] && commentHandles[id].stop(); // delete the post
            sub.removed('posts', id);
        }
    });

    sub.ready();
    // make sure we clean everything up (note `_publishCursor` // does this for us with the comment observers) 
    sub.onStop(function() { postHandle.stop(); });
});
```

![image](https://cloud.githubusercontent.com/assets/942698/3426047/2a90e4ee-0018-11e4-943c-805b0ad042b5.png)

**Comment by tmeasday** [comment]
That looks like it should be working to me. Are you seeing any comments come over via DDP? (if you inspect the websocket in developer tools, or use ddp-analyzer-proxy ?)

**Comment by calirails** [comment]
hi Tom, I followed both of your recommendations with running ddp-analyzer-proxy and ran node-inspector and discovered my embarrassing mistake. I had a typo in my subscription created as:
`Comments = new Meteor.Collection('commnents');`
rather than `Comments = new Meteor.Collection('comments');`

I 'believe' I introduced this when I attempted to type command+N to create a new file and missed the command key altogether. I learned something new here but apologize for the churn on this. I will close this issue now.

**Comment by tmeasday** [comment]
No worries @calirails. Glad that you learned something useful. We should probably add a sidebar on debugging and mention ddp-analyzer-proxy :)

**Comment by calirails** [comment]
Yes, I agree that a sidebar ddp-analyzer-proxy would be super helpful. I now know that watching ddp-analyzer-proxy would have indicated to me that the server wasn't publishing Comments because of my typo. Is it correct to infer that publications are effetively idle declarations until a valid subscription is initiated by a client?

As a side note to the sidebar. Including a reference to node-inspector would also help those that didn't know server side JS debugging is possible via Chrome Inspector.

**Comment by calirails** [comment]
Let me know if I you'd like me to help with that sidebar content provided you're comfortable with my very lightweight knowledge.
