### ISSUE TITLE
What happened to the English version?

### ISSUE THREAD

**Issue by JMerrill** [DiscoverMeteor/book#315]
Another issue referenced this URL --

https://github.com/DiscoverMeteor/DiscoverMeteor_En/blob/master/16-bitly.md.erb

but it's 404, because there's no more DiscoverMeteor_En -- and there doesn't seem to be something else (like just plain DiscoverMeteor w/out a language tag) that takes its place.

What am I missing?

**Comment by SachaG** [comment]
That repo is private, it's for translators only, sorry!
