### ISSUE TITLE
Typo: sachag instead of sacha

### ISSUE THREAD

**Issue by GeorgeStrakhov** [DiscoverMeteor/book#317]
http://book.discovermeteor.com/chapter/routing

Actual:
"sachag:spin"

Should be:
"sacha:spin"

**Comment by evolross** [comment]
I ran into this too.  The sacha:spin atmosphere package also says it's incompatible with Meteor 0.9.0 but it appears to be working for me with 0.9.0.

**Comment by SachaG** [comment]
You're right. Also, just updated the package: https://atmospherejs.com/sacha/spin
