### ISSUE TITLE
why do I get this message during mrt add bootstrap?

### ISSUE THREAD

**Issue by maheshbvv** [DiscoverMeteor/book#318]
MAHESHs-MacBook-Pro:microscope MAVERICK$ mrt add bootstrap

/usr/local/lib/node_modules/meteorite/lib/project.js:225
          throw("Package named " + pkgName + " doesn't exist in your meteor in
                                           ^
Package named bootstrap doesn't exist in your meteor installation, smart.json, or on atmosphere
MAHESHs-MacBook-Pro:microscope MAVERICK$

**Comment by SachaG** [comment]
With the latest version of Meteor, we're not using Meteorite anymore. You're probably reading an older version of the book?

**Comment by maheshbvv** [comment]
Thank You So much for the reply

**Comment by calirails** [comment]
I'm noticing several if not more of the previously working microscope packages such as rss, and others that are not recognized with meteor 0.9.0 and some others I plan to use that are not successfully built or published. Is there a page or CLI command to know what's been successfully migrated to the new meteor packaging registry?

**Comment by calirails** [comment]
While it doesn't answer all questions, this was helpful to read: http://blog.percolatestudio.com/engineering/meteor-packaging-questions/

Also running meteor search <package> will tell you if the 0.9.0 knows about the package you may have been previously using.
