### ISSUE TITLE
Remarks for "Collections > Client-Server Communication"

### ISSUE THREAD

**Issue by jeroentbt** [DiscoverMeteor/book#32]
In the `First browser console` where we insert a new entry on the client, the console on chrome returns the ID in double quotes, not single as on the page.
I have no idea whether other consoles would return ' or ". Just thought I'd mention.

Below that in the `Mongo console` where we de db.posts.find();
I get this:

```

> db.posts.find();
{ "_id" : ObjectId("51c0df802028e556265cc60f"), "title" : "A new post" }
{ "title" : "A second post", "_id" : "aRB8CTXjndcNMDNrC" }
```

It might be a good idea to explain here that the order of the attributes in the objects doesn't matter.
A short explanation (or a "we'll get back to this") on the difference between the _id in entries created through Mongo or the browser would also be nice (I for one am curious :)).

**Comment by jeroentbt** [comment]
Looks like meteor uses its own ID generating system and inserts the generated ID together with the rest of the data. My javascript fu is not practiced enough to make full sense of the code (yet, I hope), but it seems that the system to create ID's in meteor is even different for code running on the server and in the browser.
When no ID is specified mongo takes care of generating an ID with the `ObjectId("51c0df802028e556265cc60f")` syntax.

It's probably beyond the scope of the book to dig in to this but touching the subject might help as more people will see the difference.

**Comment by tmeasday** [comment]
1. Regarding the different quotes + object property ordering--I guess this is standard Javascript stuff and we are assuming that people are aware of this.
2. Re: mongo ids --- I don't think we ever insert a document directly using mongo, so you shouldn't see such a mongo id if you are just following the text. 

Regarding the difference : Meteor uses it's own ids because it doesn't want to rely on Mongo, but it supports mongo ids in case objects are inserted externally.

**Comment by jeroentbt** [comment]
@tmeasday 

> Then, run the command meteor mongo to initiate a Mongo shell, into which you can type standard Mongo commands (and as usual, you can quit it with the ctrl+c keyboard shortcut). **For example, let's insert a new post**
> :)

Thank you for explaining the difference!

**Comment by tmeasday** [comment]
Oh! You are right! My bad..

**Comment by tmeasday** [comment]
Ok, made this much clearer, thanks!
