### ISSUE TITLE
A Note on CoffeeScript (chapter 2): Link to Microscope-CoffeeScript

### ISSUE THREAD

**Issue by Yaakov-Belch** [DiscoverMeteor/book#321]
It may be helpful for CoffeeScript users to know that a [CoffeeScript version of Microscope](https://github.com/DiscoverMeteor/Microscope-CoffeeScript) is available.  Please add the link to the book.

**Comment by SachaG** [comment]
That version isn't quite up to date yet, so for now we don't really want to
point people to it…
