### ISSUE TITLE
The code is sensitive to the order of file execution

### ISSUE THREAD

**Issue by Yaakov-Belch** [DiscoverMeteor/book#322]
The file `collections/posts.js` contains this line:

```
Posts = new Meteor.Collection('posts');
```

The file `server/fixtures.js` contains this code:

```
if (Posts.find().count() === 0) {
  Posts.insert({...}
  ...
}
```

Of course, this works if the files are executed in the presented order but fails if their order is reversed.
As explained in the [Meteor documentation](http://docs.meteor.com/#structuringyourapp), the directory `collections` is processed before `server` --- but only because of their lexicographical order.

If we rename `collections` to `zcollections`, the `meteor` command will fail to start the application because of this problem.

I believe the correct solution is to put the fixtures into `Meteor.startup`:

```
Meteor.starup(function(){
  if (Posts.find().count() === 0) {
    Posts.insert({...}
    ...
  }
}); 
```

This will delay their execution until all server code has been loaded and executed.

Using collections in templates or helpers is OK because they are executed only after all code has been read.

**Comment by tmeasday** [comment]
Good pickup. Thanks @Yaakov-Belch

**Comment by Yaakov-Belch** [comment]
FYI, the function `ownsDocument` defined in `lib/permissions.js` is used in `collections/posts.js` in a way that would break if the files were loaded in the wrong order.  But because the `lib/` directory is executed before all other files, this is correct.

But maybe it's right to draw the readers attention to this issue here also.

**Comment by tmeasday** [comment]
I think perhaps the better solution here is to put collections in `lib/`. I tend to end up doing this in projects as you tend to want to just reference the collections outside of `Meteor.startup` in general.

Of course @Yaakov-Belch's second point will come in that case. Will discuss.
