### ISSUE TITLE
Chapter 5.5: 'The Session is available everywhere as Session' -- except on the server

### ISSUE THREAD

**Issue by Yaakov-Belch** [DiscoverMeteor/book#325]
The word **everywhere** in the statement _'The Session is available everywhere as Session'_  may mislead the reader to think that the session is also present on the server.  It needs to be qualified/clarified in order to avoid misunderstanding.

At one hand, after reading the previous paragraphs, it may be logical to assume that the session is applicable only to the client.  At the other hand, there are valid arguments to think otherwise:
- In meteor 'javascript/database **everywhere**' means 'on the client and on the server'.
- Sometimes, it makes sense to have session data on the server.
- Traditional web frameworks keep session data on the server.

After consulting the documentation, it is clear that `Session` is client-only.  Can we clarify this in the tutorial as well?

**Comment by SachaG** [comment]
Good point :)
