### ISSUE TITLE
Roll back changes in chapter 5.5 'The Session'

### ISSUE THREAD

**Issue by Yaakov-Belch** [DiscoverMeteor/book#326]
The side bar chapter 5.5 'The Session' demonstrates reactivity by changing the current Microscope program.  Unlike the normal source changes ---  the changes made in this chapter do not serve to develop a new, usable feature of the application.  We just use the application to explore a new meteor feature.

Consequently, at the end of the chapter, the reader should be instructed to roll back all changes made during our experiments.

**Comment by tmeasday** [comment]
Ahh, yes this is what we intended for all sidebars. Perhaps we needed to make this clearer earlier on.

**Comment by SachaG** [comment]
Good point.
