### ISSUE TITLE
Unused and unexplained code in template 'header' -- chapter 6

### ISSUE THREAD

**Issue by Yaakov-Belch** [DiscoverMeteor/book#327]
In chapter 6, we define the 'header' template to include the following lines:

```
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
```

As far as I see, this link does not produce a visible output in the page (except for some space).  Its usage is also not explained within this chapter.

This is confusing: As a reader of the tutorial, I try to understand every line of the code --- just as if I were to write the application myself.  

If the link is used at some point in the future --- let's add it then, when it is motivated.  If it is not used at all --- let's just delete it.  But if it is needed right now, please explain why.

**Comment by tmeasday** [comment]
I think this is part of the "hamburger menu" at smaller resolutions. @SachaG ?

**Comment by SachaG** [comment]
Yes, this is just Boostrap's code. Maybe I'll add a note about it.
