### ISSUE TITLE
Your opinion on client db access vs. server methods changed ==> update the book.

### ISSUE THREAD

**Issue by Yaakov-Belch** [DiscoverMeteor/book#329]
In chapter 8, you give this advise:

> When things are relatively straightforward and you can adequately express your rules via allow and deny, it's usually simpler to do things directly from the client.
> 
> Directly manipulating the database from the client creates the perception of immediacy, and can make for a better user experience...
> 
> However, as soon as ..., it's probably better to use a Method.

This advice leaves the impression that client data base access is simpler, has a faster feedback (latency compensation) but Methods are more powerful and more precise for control.

In your [great blog post](https://www.discovermeteor.com/blog/meteor-methods-client-side-operations/), you re-evaluate the trade offs and find:

**Calling a Method is as simple as modifying the data base on the client:** First of all, you can skip all `.allow` and `.deny` rules: just remove the `insecure package`  and always work with methods.  Second, instead of scattering insert, update and remove calls inside callbacks and hooks, it is good design to put them all into some API for collections and call the API from your callbacks and hooks.  Finally, instead of calling a API javascript function, call an API meteor method.

**Latency compensation works for Methods:** Make your Method code available to the client and the server:  The client will use the code as a stub to immediately show changes on the screen.  The server will make the canonical changes to the data base.

**Its secure:** Even if an attacker can convince the method on the client to do something incorrect, the server will do the right thing on the real data base and override any false client decisions.

Note: There may be cases where the method uses and needs access to data that is only on the server and not on the client. 

One example is checking URL uniqueness: The method stub on the client may think that an URL is unique while the server will find that there is another post (not published to this client) with the same URL.  In this example, meteor still does the best thing automatically: The stub function is the **best guess** that the client can do: If there is an obvious URL repetition, it appears immediately.  If the client guesses wrong, it takes one round-trip to correct the result.

For strictly server-side computations, just put the method code into the `/server/` directory and always get the correct result after one round-trip.

I suggest to adjust the advice in the book accordingly.

**Comment by SachaG** [comment]
Thanks, we might revisit this section. For now I'll add a link to the blog post in the book.
