### ISSUE TITLE
Chapter 12: limit vs postsLimit

### ISSUE THREAD

**Issue by neur0manc** [DiscoverMeteor/book#334]
Hi,

in `lib/router.js` you start with this line:

``` javascript
var postsLimit = parseInt(this.params.postsLimit) || 5;
```

But later your rename the var to just `limit`.

**Comment by SachaG** [comment]
I agree that can be a little confusing, but I think the code itself is correct, since we do define the `limit` variable:

``` js
var limit = parseInt(this.params.postsLimit) || 5; 
```

Maybe we'll call it `postsLimit` as well though.
