### ISSUE TITLE
Clarity issues in chapter 5

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#344]
I'm not sure if it's ok to report non-technical issues, but here goes:

I feel like some explanation is needed on `Router.onBeforeAction()`. It's being passed strings like `"loading"` and `"dataNotFound"`. What are those, exactly? Are they internal functions somewhere in Meteor? What does `Router.onBeforeAction('loading')` _actually_ do? What if I call `Router.onBeforeAction('blahblah')`?

**Comment by SachaG** [comment]
You're right! Sorry for leaving that out, fixing it soon :)
