### ISSUE TITLE
Chapter 8 - "$set" is not explained

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#345]
Referring to this block of code:

```
    Posts.update(currentPostId, {$set: postProperties}, function(error) {
      if (error) {
        // display the error to the user
        alert(error.reason);
      } else {
        Router.go('postPage', {_id: currentPostId});
      }
    });
```

What is `$set` exactly? It's not explained in the chapter.

**Comment by ghost** [comment]
After a little digging, I found this:

http://docs.mongodb.org/manual/reference/operator/update/set/

But I'm still confused, because the MongoDB reference says the syntax should be `{ $set: { <field1>: <value1>, ... } }` and in the Meteor book example, `$set` is only being passed a field, not a value.

**Comment by SachaG** [comment]
We're actually passing a JavaScript object (`postProperties`), not a field. I guess we should probably take the time to point it out :)

**Comment by ghost** [comment]
Much appreciated!! The book said that HTML, CSS, and some JavaScript experience was enough. We don't know much (or maybe nothing) about MongoDB. :)

**Comment by SachaG** [comment]
You really don't need to know much about MongoDB, don't worry :)
