### ISSUE TITLE
Chapter 8 - "post" method to create posts?

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#346]
The chapter states:

> To create posts, we are using a `post` Method...

I'm still a Meteor newbie, but I'm pretty sure that should say "we are using an `insert` Method," since the code to create a new post is:

```
var user = Meteor.user();
var post = _.extend(postAttributes, {
  userId: user._id,
  author: user.username,
  submitted: new Date()
});
var postId = Posts.insert(post);
```

But if I'm wrong, please let me know so I fully understand this. :) Thanks.

**Comment by SachaG** [comment]
Actually we meant `postInsert`, not `post` (since that's the name of the method we're using). Fixing it now :)
