### ISSUE TITLE
typo: should be .js not .html

### ISSUE THREAD

**Issue by hughhopkins** [DiscoverMeteor/book#347]
In https://book.discovermeteor.com/chapter/errors

One or the code snippets is labelled twice. It should be post_edit.js and not post_edit.html

![screen shot 2014-10-25 at 13 08 27](https://cloud.githubusercontent.com/assets/2920542/4779678/cacc887c-5c3f-11e4-81bb-eb68fae48536.png)

Loving the book by the way. thanks

**Comment by tmeasday** [comment]
Thanks @hughhopkins
