### ISSUE TITLE
get value from template

### ISSUE THREAD

**Issue by Thomas-Lohrum** [DiscoverMeteor/book#349]
May i suggest to use "template.find(<selector>).value" to retrieve elements?

For example on page 123 (book version 1.6) the code can be rewritten such as:
# jquery

$(e.target).find('[name=url]').val() 
# Meteor style

template.find('#url').value

It is the Meteor style and also ensures that a null value is returned instead of undefined.

**Comment by SachaG** [comment]
That's a good point, we should probably change it.

**Comment by tmeasday** [comment]
Closing this as we are tracking it in the microscope repo. Thanks @Thomas-Lohrum
