### ISSUE TITLE
Editing Posts and methods

### ISSUE THREAD

**Issue by Thomas-Lohrum** [DiscoverMeteor/book#350]
The chapter "Editing Posts" uses Posts.update(). Since Meteor.methods were introduced in the chapter before to increase security, this chapter should also use methods to reflect the better coding style.

**Comment by tmeasday** [comment]
Hi @Thomas-Lohrum,

We actually recently debated this at length. The reason we did it this way is that we wanted to talk more about allow/deny and to make the book more useful/interesting (two chapters in a row that do basically the same thing for submit/edit wouldn't teach you much). In a real app you'd probably be more consistent.

**Comment by Thomas-Lohrum** [comment]
Understood. That's a point. In that case i suggest to add a highlighted info box and let users know about your decision. This strengthens your decision, rather than leaving readers alone with something that looks like an inconsistency.

**Comment by tmeasday** [comment]
I think you're right. We'll add something. Thanks.
