### ISSUE TITLE
HTML <span> tags in JS listing (Templates Chapter)

### ISSUE THREAD

**Issue by vise890** [DiscoverMeteor/book#353]
The code in `client/templates/posts/posts_list.js` in the  [templates chapter](https://book.discovermeteor.com/chapter/templates) contains `<span>` and `</span>` tags. They shouldn't be there.

**Comment by tmeasday** [comment]
Hi @vise890 - thanks for the report. I'm not quite sure what you mean though?

**Comment by vise890** [comment]
Hi @tmeasday 

So, to reproduce:
1. go here: https://book.discovermeteor.com/chapter/templates
2. scroll halfway, to the code listing: `client/templates/posts/posts_list.js`
3. It looks like this:
    ![screenshot 2014-11-03 10 00 53](https://cloud.githubusercontent.com/assets/1628760/4880192/213551d6-6338-11e4-8acc-6f499f886384.png)

You can see it has `<span>`  HTML tags at the beginning and the end of the JS code listing...

There's similar issues in subsequent chapters BTW..

**Comment by tmeasday** [comment]
Thanks for getting back to me @vise890 .

I see this though:

![screen shot 2014-11-03 at 8 43 30 pm](https://cloud.githubusercontent.com/assets/132554/4880628/f3b13882-633d-11e4-8bb5-6d30992a01bb.png)

I wonder which browser/OS you are on?

**Comment by vise890** [comment]
Ok I've isolated the issue. It's actually just the [clickable links](https://chrome.google.com/webstore/detail/clickable-links/mgamelhnfokapndfdodnmfiningckjia) extension in Chrome. I've closed this, as it doesn't seem to be worth worrying about.
