### ISSUE TITLE
Router.map() should be replaced by Router.route()

### ISSUE THREAD

**Issue by Thomas-Lohrum** [DiscoverMeteor/book#356]
With v1.7 of the book most of the code has been reworked. However, there are three references left which should be updated. The call to Router.map() is confusing to readers. It has been marked deprecated and is no longer referenced in the guide either.

**Comment by tmeasday** [comment]
Hey @Thomas-Lohrum - where do we call `Router.map`? I thought we got them all..

**Comment by Thomas-Lohrum** [comment]
- book version 1.7
- pdf file
- reference "Controlling the Comments Subscription" -> inside Code on p. 187 
- Infinite Pagination -> within sentence on p. 215 (...) and our postsList route should be moved to the bottom of the **Router.map()** block since it pretty much matches everything, (...)

**Comment by tmeasday** [comment]
Thanks @Thomas-Lohrum
