### ISSUE TITLE
Router.current().route.getName() is undefined

### ISSUE THREAD

**Issue by lugaru90** [DiscoverMeteor/book#357]
Chapter Voting:
Router.current().route.getName() returns undefined

**Comment by lugaru90** [comment]
Meteor updates automatically to Version 1.0, Iron Route needed a manual "meteor update" call for me

**Comment by tmeasday** [comment]
Sorry @lugaru90 - I'm glad you figured out what you needed to do. It's kind of difficult for us to gracefully handle it when we update for people who are halfway through the book :/

**Comment by lugaru90** [comment]
Hi tmeasday,

just as an suggestion, which would make your book even more helpful: Make another Section with Version changes. And Display a Notification to the User when the Version Number changes. Tell the User to get the latest changes from Github and make a reference in a extra Chapter.
So for example just: Swap this.route... to Router.route.... and give an example for it.

And a question beside: Is there any kind of Function documentation? For example for Router.route.*CONTROLLERNAME.path() i haven't found anything. So if i recognize a Problem i don't really know where i can check back. So maybe even make a link to the used Functions (if there is any reference)

Cheers
