### ISSUE TITLE
Ambiguous wording in "Publications and Subscriptions > Autopublish"

### ISSUE THREAD

**Issue by jeroentbt** [DiscoverMeteor/book#36]
> How does this work? Suppose you have a collection called 'posts' on the server. Then autopublish will automatically send every post that it finds in the Mongo posts collection into a collection called 'posts' on the client **(assuming there is one)**.

Could be read as "assuming there is a collection called 'posts' on the client".
I think you mean to say "assuming there is a client", because making sure the collection is available on the client is the point of autopublish.

**Comment by tmeasday** [comment]
Hi @jeroentbt, 

Actually the way you read it is correct. If you have no collection called `posts` on the client, then autopublish will not do anything with the posts.

**Comment by jeroentbt** [comment]
Hey,

Oh, ...
Still think it could be worded better though, or expanded on.
Above the image it says:

> What autopublish does is automatically mirrors all data from the server on the client.

It confused me.. but I've been known to be a bit slow sometimes :)

EDIT: and I do realise now that saying it will sync between client and server if there is a client sounds a bit stupid :/
