### ISSUE TITLE
Chapter 9.5 Creating a Meteor Package. Call of undefined method 'clearSeen'

### ISSUE THREAD

**Issue by marcusficner** [DiscoverMeteor/book#360]
You are proposing a call to `clearSeen`, which isn't declared anywhere. 

> One other thing we need to do is to make some minor updates to use the correct API:
> `Router.onBeforeAction(function() { Errors.clearSeen(); });`

Even if it would be defined in `errors.js` what would be the case here?
Seen messages are going to be removed in the `rendered` callback in `errors_list.js`, or was this meant as a refactoring here?

**Comment by tmeasday** [comment]
Hi @marcusficner - this is an old holdover from the previous way we implemented this. You can ignore it.

I'll remove it.
