### ISSUE TITLE
"mrt add bootstrap" does not work...

### ISSUE THREAD

**Issue by ttomek32** [DiscoverMeteor/book#361]
Hey, "mrt add bootstrap" does not work, it should be "meteor add bootstrap".

http://stackoverflow.com/questions/25880163/discover-meteor-mrt-add-bootstrap-install-error

**Comment by SachaG** [comment]
You might be reading from an older version of the book?

**Comment by ttomek32** [comment]
Currently I am reading from here: http://pl.discovermeteor.com/

**Comment by SachaG** [comment]
In that case you should leave an issue with the polish translation team, we
don't speak polish so we can't really maintain that translation :)
