### ISSUE TITLE
Small typo in PDF and web version in Chapter 12 (Pagination)

### ISSUE THREAD

**Issue by Nexus7** [DiscoverMeteor/book#363]
Page 223 says : 
"As before, we’ll add our pagination logic in our route. Remember when we **explicitely** named our
data context rather than just use an anonymous cursor?"

Should be:
"As before, we’ll add our pagination logic in our route. Remember when we **explicitly** named our
data context rather than just use an anonymous cursor?"

**Comment by SachaG** [comment]
Thanks :)
