### ISSUE TITLE
Instructions in Submitting Comments Section Ordered Slightly Confusingly

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#368]
Under "Submitting Comments" section on "Comments" chapter (https://book.discovermeteor.com/chapter/comments), the book suggests to create the comment form template, and then immediately after the code block for comment_submit.html, a screenshot of the postpage is shown with the submit form. This screenshot assumes that the errorClass has already been defined in commentSubmit helpers, but the instructions to write commentSubmit helpers come after the screenshot.

**Comment by SachaG** [comment]
Good point, I'll move the screenshot.
