### ISSUE TITLE
Route.map Clarification Needed

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#369]
Under "Controlling the Comments Subscription" section on "Comments" chapter (https://book.discovermeteor.com/chapter/comments), there was no mention of Router.map function before the code block for "lib/router.js". Comments chapter doesn't have any explanations as to what Router.map function is, and why exactly the previous routers needed to go from Router.route to this.route.

**Comment by SachaG** [comment]
Router.map is deprecated, sorry about that. We'll remove that mention.
