### ISSUE TITLE
Discrepancy in Notifications Chapter's Code

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#370]
Under "Creating Notifications" section, in code block "lib/collections/comments.js", the method is "comment", whereas the code on github (https://github.com/DiscoverMeteor/Microscope/blob/2bcd384297737b6eede14c920e1286115d73aa4a/lib/collections/comments.js) writes "commentInsert".

**Comment by SachaG** [comment]
Good catch, thanks!
