### ISSUE TITLE
Route Level or Router Level

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#373]
In the Pagination chapter, there's a sentence saying: "Now that we're subscribing at the route level, it would also make sense to set the data context in the same place." I'd expect that the same place means that data context would be set in the route level. If you scroll down just a little, and look at the sentence below the code block "lib/router.js", it says: "Now that we're setting the data context at the router level we can safely get rid of the posts template helper inside the posts_list.js file." I thought that we're setting the data context on the route level, not router level.

**Comment by SachaG** [comment]
Good call, it should be "route" both times.
