### ISSUE TITLE
Wrong Lines Highlighted in Voting Chapter

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#374]
In the Voting chapter (https://book.discovermeteor.com/chapter/voting), under Data Model section and in the code block "collections/posts.js", the lines are highlighting: commentsCount and upvoters, not upvoters and votes.

Also, on section "Ranking the Front Page Posts", in the "lib/router.js" code block, "ready: this.postsSub.ready," is highlighted, but this was already written back in Pagination chapter. Plus, the line for "});" code is not highlighted for BestPostsController.

In the code blocks for "client/templates/includes/header.html", the lines for the code:
span class='icon-bar' and div are not new and should not be highlighted. li class="{{activeRouteClass  'bestPosts'}}" is not highlighted and instead a href="{{pathFor 'bestPosts'}} which is not new code, is highlighted.

**Comment by SachaG** [comment]
Thanks!
