### ISSUE TITLE
Chapter 17 - Error in Book - not consistent with GitHub

### ISSUE THREAD

**Issue by Nexus7** [DiscoverMeteor/book#377]
In Chapter 17 the book says to add the subscription to currentUser in the router.js:

Router.configure({
  layoutTemplate: 'layout',
  loadingTemplate: 'loading',
  notFoundTemplate: 'notFound',
  waitOn: function() {
    Meteor.subscribe('currentUser'),  
    return [Meteor.subscribe('notifications')]
  }
});

However this code results in errors and the correct code (as in GitHub) should be :

Router.configure({
  layoutTemplate: 'layout',
  loadingTemplate: 'loading',
  notFoundTemplate: 'notFound',
  waitOn: function() { 
    return [
      Meteor.subscribe('currentUser'),
      Meteor.subscribe('notifications')
    ]
  }
});

**Comment by SachaG** [comment]
Thanks!
