### ISSUE TITLE
[typo] Chapter 5: Routing - Missing "to"

### ISSUE THREAD

**Issue by jasonpolito** [DiscoverMeteor/book#378]
Currently:

> What we are saying here is that for every route on the site (we only have one right now, but soon we'll have more!), we want subscribe to the posts subscription.

I believe it's supposed to read:

> What we are saying here is that for every route on the site (we only have one right now, but soon we'll have more!), we want [_**to**_] subscribe to the posts subscription.

**Comment by SachaG** [comment]
Thanks :)
