### ISSUE TITLE
HCR runs router "The session > Hot code reload"

### ISSUE THREAD

**Issue by jeroentbt** [DiscoverMeteor/book#38]
> So if we are using session variables to keep track of exactly what the user is doing, the HCR should be almost transparent to the user, as it will preserve the value of all session variables. 

Except for variables set by a router, apparently

**Comment by SachaG** [comment]
I don't think it should make any difference where the Sessions variable were set? Did you notice this happening?

That being said, Session variables set by the Router are usually set based on the URL, so they should get set again when the page reloads. But Tom can probably confirm this better than I can.

**Comment by tmeasday** [comment]
The only difference with session variables set by the router is that they'll "survive" proper reloads due to the fact that they'll be pulled out of the route.

Are you suggesting that the routing functions shouldn't re-run on HCR @jeroentbt? It's an interesting idea, although I'm not sure if it's feasible to implement..

**Comment by jeroentbt** [comment]
@SachaG indeed, when the app gets a HCR, session variables set in the router get reset to their value set by the router for that specific url.

@tmeasday I'm not suggesting anything :) Just a newbie trying to wrap my head around things. 
When I think about it though, given that a HCR != page reload, keeping all session vars might be more logical for the developer. Although one could probably also say that if you change a session variable set by a router, you could just as well request the correct url to reflect that. Which is more transparent to the user.
So a best practise would be to not touch session variables set by the router. Right?

In any case, I think this should be reflected in the text

> So if we are using session variables to keep track of exactly what the user is doing, the HCR should be almost transparent to the user, as it will preserve the value of all session variables **(except those set by the router)**.

But you'll probably be able to word it better :)

**Comment by SachaG** [comment]
I understand what you mean now, but I don't really think it's a problem. As you said, you shouldn't change something like the currentPostId Session variable without changing the URL too. 

What's more the HCR _is_ preserving Session variables values. It's just that they're getting rewritten immediately by the Router. 

So I think we can consider this an edge case for now, but if other people mention the same issue we'll definitely try to deal with it in the book.

**Comment by jeroentbt** [comment]
@SachaG
I did run in to it while following the book.
in "Changing the session"

> For instance, if we wanted to change the displayed post, we can simply do: [change `currentPostId` via browser console]

This is then followed by the part about "Hot code reload" where we set another session var, which is retained after a HCR, the page however does reload the original post because the router is run again.

So everybody who follows the examples will run in to it, I think.

But they probably won't nag about it like I do :)

**Comment by tmeasday** [comment]
@jeroentbt you are right of course :)

I appreciate your need to understand this completely, it's a sign of a good developer! 

We'll look at making this a bit clearer. (I knew that changing `currentPostId` like that wasn't a good idea ... )
