### ISSUE TITLE
Image does not match for Commit 7-3 - "Denied access to new posts page when not logged in."

### ISSUE THREAD

**Issue by bshewan** [DiscoverMeteor/book#380]
I think the image for this commit is outdated. It matches the "Launch Instance" live version, but not the book or GitHub version.

The "you should see this" image is currently this:

![7-3](https://cloud.githubusercontent.com/assets/653282/5058269/97f03f58-6cbf-11e4-98a1-b1c83efa249d.png)

But, when I tried the code it looked more like this:

![safariscreensnapz001](https://cloud.githubusercontent.com/assets/653282/5058267/70ddc6ec-6cbf-11e4-8d6b-3a5bc9cd6900.png)

**Comment by SachaG** [comment]
Yes, some screenshots are still using an older version of the app. It's basically the same page though.
