### ISSUE TITLE
Code for Commit 8-3

### ISSUE THREAD

**Issue by ylh888** [DiscoverMeteor/book#381]
These lines in the Book shows:
Posts.allow({
  update: ownsDocument,
  remove: ownsDocument
});
instead of 
Posts.allow({
  update: function(userId, post) { return ownsDocument(userId, post); },
  remove: function(userId, post) { return ownsDocument(userId, post); },
});

**Comment by neilborromeo** [comment]
Yes, just noticed this too. Please change to:

Posts.allow({
update: function(userId, post) { return ownsDocument(userId, post); },
remove: function(userId, post) { return ownsDocument(userId, post); },
});

**Comment by SachaG** [comment]
Thanks!
