### ISSUE TITLE
Chapter sequense is messed up

### ISSUE THREAD

**Issue by abooayoob** [DiscoverMeteor/book#383]
Don't know what happened, but chapter sequensed is not correct today....
![screen shot 2014-11-18 at 08 46 46](https://cloud.githubusercontent.com/assets/9134348/5084007/97f03976-6eff-11e4-81b8-ab2378f33dcb.png)

**Comment by SachaG** [comment]
Oh, that's a pretty funny bug! But I think I can guess what's going on… Let
me see :)

**Comment by abooayoob** [comment]
Thanks, now I don't have to be distracted by peeking at the funny looking
menu all the time ;) My mind is at ease again!
