### ISSUE TITLE
Chapter 9:  calling 'postInsert' from console fails

### ISSUE THREAD

**Issue by fulv** [DiscoverMeteor/book#387]
Where it says:

```
To test this out, open up the browser console and try entering a post with no URL:

Meteor.call('postInsert', {url: '', title: 'No URL here!'});
```

I tried that, and instead of the expected error _"You must set a title and URL for your post"_, I got something like:

```
Error invoking Method 'postInsert': Match failed [400]
...
r: Match error: Expected string, got object {message: "Match error: Expected string, got object"....
```

I tried it both on my own code, and on http://meteor-book-chapter9-4.meteor.com/.

**Comment by tmeasday** [comment]
Are you logged in @fulv ?

**Comment by fulv** [comment]
Thanks!  I probably was not when I encountered this issue.  I get the same error when I try to reproduce while not logged in, so that was probably the reason.  
Turns out I had another bug in the code preventing a successful post even when logged in, but it was probably unrelated.
