### ISSUE TITLE
Chapter Voting - post_item.html - invalid character for arrow up character

### ISSUE THREAD

**Issue by lazmeister** [DiscoverMeteor/book#388]
It seems to be a missing charact for the upvote button and its showing an invalid character on Windows 7 Latest Chrome/Nitrous.io:

a href="#" class="upvote btn btn-default {{upvotedClass}}">⬆</a

**Comment by lazmeister** [comment]
would I just use & uarr;? if so can you update the book?

**Comment by SachaG** [comment]
That shouldn't impact the rest of the book too much, feel free to just use any character you'd like :)
