### ISSUE TITLE
Modulus Deployment fails

### ISSUE THREAD

**Issue by linker-err0r** [DiscoverMeteor/book#389]
The current version of the book fails to deploy properly. According to Modulus docs, the following must be done after deploying the app and getting the project's URL from Modulus: 

> Set the ROOT_URL environment variable to your project's URL. This is displayed at the top of your 
> project dashboard and in the CLI at the end of the deploy.
> 
> $ modulus env set ROOT_URL http://my-meteor-project-9339.onmodulus.net
> These can also be set on the project dashboard's administration tab if desired.

After doing so, the project will successfully deploy upon `modulus project restart`.

**Comment by SachaG** [comment]
Actually we'll just reference their documentation, probably makes more sense that way.
