### ISSUE TITLE
Point to Bootstrap 3 official atmosphere repo

### ISSUE THREAD

**Issue by jonathanbardo** [DiscoverMeteor/book#391]
In the getting started section, we add the https://atmospherejs.com/mizzao/bootstrap-3 bootstrap package. On this atmosphere page, the author recommends using the official integration of Bootstrap 3 here https://atmospherejs.com/twbs/bootstrap.

**Comment by tmeasday** [comment]
Ah, yes. Good point. Thanks @jonathanbardo

**Comment by CaptSaltyJack** [comment]
Better yet:

    meteor add bootstrap

The package has been pulled into the official repo.
