### ISSUE TITLE
Accessing A Commit Locally - unexpected warning message

### ISSUE THREAD

**Issue by dtrimsd** [DiscoverMeteor/book#393]
Results of executing the 'git clone':

root@dev:~/src# git clone git@github.com:DiscoverMeteor/Microscope.git github_microscope
Cloning into 'github_microscope'...
The authenticity of host 'github.com (192.30.252.130)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? 

Why the message? Is it OK to continue?

FWIW - I'm a Windows person.Working with Linux is very new and I only have a fragile understanding. This might be a non-issue of experienced Linux users but is surprising/disturbing for Windows users.

**Comment by SachaG** [comment]
Yes, you can continue. It's just a standard SSH message.

**Comment by dtrimsd** [comment]
Sacha,

Thank your for the response. Unfortunately when I retry I now get a 
fatal error:

root@dev:~/src# git clone git@github.com:DiscoverMeteor/Microscope.git 
github_microscope
Cloning into 'github_microscope'...
Warning: Permanently added the RSA host key for IP address 
'192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
root@dev:~/src#

**Comment by SachaG** [comment]
Well, this is a git/ssh error, I'm afraid it's not really related to the book or Meteor at all. So I can't really help you with this, sorry :(

Maybe try using a Git app instead?

**Comment by dtrimsd** [comment]
Sacha,

Except for the following I'll drop the issue.

Yes, it is related to the book.

```
      Accessing A Commit Locally

We've just seen how to browse a commit's entire code online on
GitHub. But what if you want to do the same thing locally? For
example, you might want to run the app locally at a specific commit
to see how it's supposed to behave at this point in the process.

To do this, we'll take our first steps (well, in this book at least)
with the|git|command line utility. For starters,make sure you have
Git installed <http://git-scm.com/downloads>. Then*clone*(in other
words, download a copy locally) the Microscope repository with:

|git clone git@github.com:DiscoverMeteor/Microscope.git github_microscope
|

That|github_microscope|at the end is simply the name of the local
directory you'll be cloning the app into. Assuming you already have
a pre-existing|microscope|directory, just pick any different name
(it doesn't need to have the same name as the GitHub repo).

Let's|cd|into the repository so that we can start using
the|git|command line utility:

|cd github_microscope
|

Now when we cloned the repository from GitHub, we downloaded/all/the
code of the app, which means we're looking at the code for the last
ever commit.
```

The error I sent you is when I try to clone Microscope on a Digital 
Ocean Linux 'droplet'.

I've tried to do a clone on my Windows 7 pc using git in a command 
window and received the same error:

```
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

Identity added: /c/Users/worker/.ssh/id_rsa
(/c/Users/worker/.ssh/id_rsa)
C:\Users\worker\Documents\GitHub> git clone
git@github.com:DiscoverMeteor/Micros
cope.git github_microscope
Cloning into 'github_microscope'...
The authenticity of host 'github.com (192.30.252.128)' can't be
established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)?
```

I have successfully cloned the Meteor application itself from github on 
both the Digital Ocean droplet and on my Windows 7 pc so I know my git 
installs are ok. At least I can download the zip to look at your code.

Dave

**Comment by SachaG** [comment]
What I meant is that the scope of the book is Meteor. We do provide some additional indications about Git, but we're not Git experts and we're also not familiar with how you've set up your own system or Digital Ocean droplet. So it's hard to help, sorry :(

**Comment by dtrimsd** [comment]
fixed result

**Comment by dtrimsd** [comment]
444444444444444444

**Comment by sixbras** [comment]
Hi. I've the same issue using SSH terminal from Codeanywhere.com. 

Cloning into 'github_microscope'...  
Warning: Permanently added the RSA host key for IP address '192.30.252.130'
to the list of known hosts.  
Permission denied (publickey).  
fatal: Could not read from remote repository.  
Please make sure you have the correct access rights  
and the repository exists.                

How did you fix it ?

EDIT :+1: 
Fix it using https for cloning

git clone https://github.com/DiscoverMeteor/Microscope.git github_microscope

**Comment by dtrimsd** [comment]
I didn't really fix it. I just downloaded the zip file and installed it 
that way. I did find this link for a proper fix but never got around to 
try it out. Who knows...

https://help.github.com/articles/error-permission-denied-publickey/#verify-the-public-key-is-attached-to-your-github-account
