### ISSUE TITLE
Make re-login easier

### ISSUE THREAD

**Issue by SteveALee** [DiscoverMeteor/book#395]
When keeping the live HTML book open in a browser tab you get logged out and see the message about paid-for content. In order to login in again you need to navigate back to the contents.

Can this be made easier?

**Comment by SteveALee** [comment]
Now I discovered the Book title at the top of each chapter  is also a link it's not so bad.

**Comment by tmeasday** [comment]
Hi @SteveALee - why are you getting logged out?

**Comment by SteveALee** [comment]
It's due to leaving the book open in a tab and laptop is sleeping - perhaps it's a short term or session cookie?

**Comment by tmeasday** [comment]
Perhaps you are using private browsing / incognito mode?

**Comment by SteveALee** [comment]
No, just a normal session. I like to leave state in open tabs and having to login in is a pain but this isn't the only culprit. Even Gmail now needs re login.

I'll close the issue.
