### ISSUE TITLE
Fixed typo in spanish book

### ISSUE THREAD

**Issue by oihi08** [DiscoverMeteor/book#398]
In chapter "Añadir un paquete", appears some misspelled phrases:

"Esto no es distinto de añadir Bootstrap de **la** forma habitual incluyendo manualmente los ficheros CSS y JavaScript..."

"Fíjate que estamos añadiendo Bootstrap 3. Algunas de las capturas de este libro están tomadas con un**a** antigua versión de Microscope con Bootstrap 2, por lo que podrían parecer ligeramente diferente."

"Al contrario **de** la forma “tradicional” en la que incluimos recursos externos, no tenemos que agregar enlaces a ningún fichero CSS o JavaScript, ¡porque Meteor se preocupa **de** eso por nosotros! Esta es sólo una de las muchas ventajas de los paquetes Meteor.

Sorry for my english

Oihane

**Comment by SachaG** [comment]
The spanish version has its own repo: https://github.com/DiscoverMeteor/DiscoverMeteor_Es :)
