### ISSUE TITLE
Missing //... in errors chapter (minor)

### ISSUE THREAD

**Issue by hamoid** [DiscoverMeteor/book#399]
I got used to seeing //... in the source code when adding stuff to an existing file.
It's missing at https://book.discovermeteor.com/chapter/errors for the code of this file "client/templates/posts/post_submit.js", where "errorMessage:function" and "errorClass:function" are introduced.
So it felt like I was supposed to create a new file.

**Comment by SachaG** [comment]
Good catch, thanks!
