### ISSUE TITLE
em dash and smart quotes

### ISSUE THREAD

**Issue by matb33** [DiscoverMeteor/book#4]
I can't believe I'm reporting this... but it was hammered in to me from working with copywriters and QA... I wasn't going to report it, but this is a book after all!
1. Replace occurences of `--` with `&nbsp;—&nbsp;`
2. Add a `&nbsp;` between the penultimate and last word of every paragraph to avoid orphans
3. Replace quotes `"` with smart quotes: `“…”`
4. Replace apostrophes `'` with smart equivalent: `’`

I haven't yet encountered the use of en dashes in your copy, but will let you know if I do. These would be used for ranges, such as 1–5 documents.

In all these cases, this could be automated, where you continue to author using `--` etc (I'm assuming copy is in Markdown or other such format?), but a filter takes care of the cleanup.

**Comment by SachaG** [comment]
We'll try to keep this in mind, thanks for the tips!
