### ISSUE TITLE
Live instance not in sync with book (Adding users)

### ISSUE THREAD

**Issue by jeroentbt** [DiscoverMeteor/book#40]
The live instance lacks the `a.btn-navbar` fix for small windows.
http://meteor-book-chapter6-1.meteor.com/

It would be nice to also mention in the book that you're using a workaround here. 
I have my browser open next to my code editor on my 1440x900 display. (I keep my external 20" just to throw you guys issues on GitHub) 
Having to click twice to be able to login didn't feel right so I started looking around. One of my first stops was the live instance where I couldn't see a thing.

Also (related), once logged in on a small screen, you're unable to log out. Clicking the `a.btn-navbar` only briefly shows the dropdown.

(I was not exactly serious about the 20")

**Comment by tmeasday** [comment]
Thanks for the reminder!
