### ISSUE TITLE
Bootstrap 3.x class change for row-fluid

### ISSUE THREAD

**Issue by webkenny** [DiscoverMeteor/book#402]
In the example for `client/main.html` in Chapter 3 on Templates, you list `row-fluid` as the class on the `main` element.

In Bootstrap 3.x this has changed to simply `row`

See Major Class Changes in [Migrating to v3.x](http://getbootstrap.com/migration/)

**Comment by SachaG** [comment]
Actually it looks like we can just drop that class altogether. Thanks for the heads up :)
