### ISSUE TITLE
Accounts asks for email, not username, throws off "Submitted By"

### ISSUE THREAD

**Issue by BrooklynC** [DiscoverMeteor/book#404]
I added the same package as you have used (ian:accounts-ui-bootstrap-3). Most everything works fine when I run the app. However, my accounts layout (in the top right) is very different than the one in your instance, even though it is using the same package. First, it says Sign In/Join while yours reads Sign In/Up.  Mine also asks for an email address when creating a login, rather than a username. That wouldn't be a problem, however since {{author}} is calling for user.username, my posts only show "submitted by" without the name of the author. I tried changing the code in lib/collections/posts.js to user.email and that doesn't work.

How would the results appear different even if on the same package?

**Comment by tmeasday** [comment]
Hi @BrooklynC -- it's possible it looks different because the screen shots are a little out of date.

The more fundamental problem about username vs email is I'm guessing because you missed the line:

```
Accounts.ui.config({
  passwordSignupFields: 'USERNAME_ONLY'
});
```

**Comment by BrooklynC** [comment]
Tom, thanks so much...turns out I stupidly missed the "_" in the line you referenced.  Changed the whole result. 

Brendan
