### ISSUE TITLE
Deployment chapter possibly missing some steps

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#408]
https://book.discovermeteor.com/chapter/deploying

Nowhere does it say how to actually package up your meteor app for use with mup. Do we use `meteor build` or `meteor bundle`? Seems there are a few steps missing there.

**Comment by SachaG** [comment]
Meteor Up has its own readme, this is meant more as a quick intro. (And to answer your question, you don't need to bundle your app).

**Comment by ghost** [comment]
I meant before mup is even in the picture, what do we need to do? So, just copy the meteor directory over? No need to run `build` or `bundle`? Will everything be minified though? An answer here would be cool, _but_ I'm also pointing out that maybe this chapter should explain how to prep your meteor project before using mup.

Thanks Sacha!

**Comment by SachaG** [comment]
You don't need to do anything before using mup.
