### ISSUE TITLE
Deployment chapter - need clarification on server auth

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#409]
```
  //server authentication info
  "servers": [{
    "host": "hostname",
    "username": "root",
    "password": "password"
    //or pem file (ssh based authentication)
    //"pem": "~/.ssh/id_rsa"
  }],
```

What exactly is the server auth for? The chapter doesn't explain what this is. If mup is just going to run a web server, what is the username and password for exactly? What does one typically fill in for hostname? Where is this connecting to and why? It looks like it's going to ssh in somewhere, but I don't understand why.

**Comment by SachaG** [comment]
This is all related to Meteor Up, which isn't really the focus of the book. If you have questions about it I would suggest looking up the Meteor Up project and asking there directly :)

**Comment by ghost** [comment]
Fair enough! Plus it's a sidebar. :)
