### ISSUE TITLE
mrt add router hangs

### ISSUE THREAD

**Issue by johngrantuk** [DiscoverMeteor/book#41]
Using MAC OS X, when I try to run the command mrt add router, it just hangs. I've tried uninstalling and reinstalling Meteor and Meteorite but the issue persists. Meteorite version 0.6.5, Meteor release: 0.6.4 Any help/advice would be gratefully received.
Thanks,
John

**Comment by tmeasday** [comment]
Can you try `mrt add router --repoPort 443`?

**Comment by johngrantuk** [comment]
Wow, that works! Thanks for such a quick response!
