### ISSUE TITLE
meteor mongo emetodo does not work

### ISSUE THREAD

**Issue by Mattnificent** [DiscoverMeteor/book#410]
I am terribly sorry about posting this here, but I didn't know where else to post it, and expect a good response.

<qoutedText from="Chapter 4: Collections">
Note that when hosting your app on *.meteor.com, you can also access your deployed app's Mongo shell with meteor mongo myApp.
</qoutedText>

When I do this, I get a Username/Password prompt;  I've tried my meteor.com login credentials, but they do not work.  How can I get working credentials to my Mongodb server instance?  (End goal: I want to import my exported development Mongodb documents)

The prompt appears for the following commands (my app is called emetodo), and I can't login to any of them:
meteor mongo --url emetodo
meteor mongo emetodo
meteor logs emetodo

I've also tried with the .meteor.com domain; I always get the prompt, and my credentials always fail.

**Comment by Mattnificent** [comment]
The tag I used around 

"Note that when hosting your app on *.meteor.com, you can also access your deployed app's Mongo shell with meteor mongo myApp."

didn't work; I should have used quotes.  It's from Chapter 4; Collections.

**Comment by tmeasday** [comment]
Hi @Mattnificent - so your app is emetodo.meteor.com ? 

I think `meteor mongo emetodo` should work. 

Have you tried just running `meteor login`? Do your credentials work there?
