### ISSUE TITLE
Will the book be updated to reflect the new template-based subscriptions?

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#413]
Will the book soon be updated to cover `Template.<name>.subscribe`?

**Comment by SachaG** [comment]
Probably not. We covered something pretty close on our blog though: https://www.discovermeteor.com/blog/template-level-subscriptions/

**Comment by ghost** [comment]
Oh, that's kind of a bummer. I thought the idea was that the book would always be updated as Meteor updated and changed.

**Comment by SachaG** [comment]
It'll be updated if an API that we use in the book changes, but we can't really update it to cover every single new feature Meteor introduces…
