### ISSUE TITLE
Awkward mixing of single and plural pronouns and verbs

### ISSUE THREAD

**Issue by KarateCowboy** [DiscoverMeteor/book#415]
Hello. This is an elementary error and is  awkward and difficult to read:

> Right now in Microscope, the current state of **the user's** application is completely contained in the URL that **they are** looking at

The singular pronoun "the user" clashes noisily with the plural pronoun and verb "they" and "are". If you introduce a singular subject then you should remain with singular. So, the correct way of writing the sentence would be: 

> Right now in Microscope, the current state of the user's application is completely contained in the URL that he is looking at 

If you would like to use plural then it would be:

> Right now in Microscope, the current state of the users' application is completely contained in the URL that they are looking at

You can make a plural of "user" by adding "s" to make it plural. Then add an apostrophe at the end to make it possessive _users'_

This grammatical error is sprinkled throughout the book.

**Comment by SachaG** [comment]
It's called the [singular they](http://en.wikipedia.org/wiki/Singular_they)
