### ISSUE TITLE
Small error in animation chapter: animate class not mentioned.

### ISSUE THREAD

**Issue by tmeasday** [DiscoverMeteor/book#419]
From https://github.com/DiscoverMeteor/Microscope/issues/202, reported by @michaelober.

In the animation chapter, the style.css excerpt shows the class as

```
.post{
    position:relative;
    transition:all 300ms 0ms ease-in;
} 
```

When the source code actually has the transition in a post.animate class:

```
.post.animate{
    -webkit-transition: all 300ms 0ms;
    -moz-transition: all 300ms 0ms ease-in;
    -o-transition: all 300ms 0ms ease-in;
    transition: all 300ms 0ms ease-in; }
```

I think this is worth noting in the chapter because the animation logic that follows adds and removes this animation class, and the class isn't mentioned until then. This is something that might be obvious to most (especially those that have used the animate.css library), but I think it's best to include to clear up any possible confusion.

**Comment by SachaG** [comment]
Good point :)
