### ISSUE TITLE
Chapter 12 - Inconsistent References to limit() versus postsLimit()

### ISSUE THREAD

**Issue by jdlubrano** [DiscoverMeteor/book#420]
In the `PostsListController` code, the function that returns the limit parameter for the Mongo query is named `postsLimit`.  In the text of the book, the `postsLimit` function is later referred to as the `limit` function.  I do not believe that this was intended as the naming is inconsistent.

Occurrences:
- We then define a new `limit` function which will return the current limit, and a `findOptions` function which will return an options object. This might seem like an extra step, but we'll make use of it later on.
- We know that `this.limit()` returns the current number of posts we'd like to show, which can either be the value in the current URL, or our default value (5) if the URL doesn't contain any parameter.

**Comment by SachaG** [comment]
You're right, thanks!
