### ISSUE TITLE
text in lib/permissions.js appears to be smeared (strange)

### ISSUE THREAD

**Issue by rolfedh** [DiscoverMeteor/book#421]
![image](https://cloud.githubusercontent.com/assets/350907/7102740/593fb77c-e058-11e4-8143-88ff46714283.png)
Reloading the page doesn't help.

**Comment by SachaG** [comment]
Seems like that's probably a rendering bug? I can't think of anything we could do on our side to create that effect…

**Comment by rolfedh** [comment]
I thought so too. However, clearing the cache and reloading the page doesn't make it go away. It's a reproducible error. Maybe you could have someone else look at permissions.js in the Editing Posts chapter using Windows 8 and Chrome... If it shows up there, then a meaningful number of users might also have the same problem. Otherwise, I'd just close this report as non-reproducible.
