### ISSUE TITLE
Chapter 3.5 on git and GitHub - unclear example of checkout with hash

### ISSUE THREAD

**Issue by evilmeteor** [DiscoverMeteor/book#425]
Someone that doesn't know git will probably feel confused when running:

```
$ git checkout c7af59e425cd4e17c20cf99e51c8cd78f82c9932
```

As of Apr 24 2015 when trying to checkout the previous hash git will return an error.

I believe it would be better to avoid the former line to input in the console and specify in the code block that the reader should go to github and look for the hash of the commit they want to see.

**Comment by SachaG** [comment]
Good point.
