### ISSUE TITLE
Commit 12-2

### ISSUE THREAD

**Issue by redji** [DiscoverMeteor/book#428]
After moving posts subscription from router to route level '/posts/:_id' and '/posts/:_id/edit' routes stopped working for me. First one returned 404 and second one did not input the values to be edited. I fixed it by adding waitOn on each route for the post with the specified id. The problem is that in the live example of this commit everything works without this changes. What is odd Posts.find().fetch() for that page returns [], but the post is displayed despite that. How is it possible?

**Comment by SachaG** [comment]
Are you still experiencing that issue?

**Comment by redji** [comment]
TBH I've been using the other way around for some time now, so I don't know.
