### ISSUE TITLE
[fr.discovermeteor.com] erreurs typographiques

### ISSUE THREAD

**Issue by R2D222** [DiscoverMeteor/book#430]
---
## Chapitre 4 - Collections

Erreur : La clé de voûte de tout ça est comment la collection côté client synchonise
Correction : La clé de voûte de tout ça est comment la collection côté client synchronise

---
## Chapitre 4.5 - Publications et Souscriptions

Erreur : C’est dans ce cas de figure que “trouver” intervient.
Correction : C'est dans ce cas de figure que “find” intervient.

Erreur : Nous avons vu comment publiquer seulement certains articles, mais vous pouvons continuer à 
Correction : Nous avons vu comment publier seulement certains articles, mais nous pouvons continuer à

**Comment by hsolatges** [comment]
# Introduction

Erreur : En revanche, on attend un connaissance élémentaire de la syntaxe 
Correction : En revanche, on attend un**e** connaissance élémentaire de la syntaxe

# Chapitre 4

Erreur : sans qu'on ait besoin d'écrire une seule ligne de code d'envoi au serveur (bien, strictement parlant, nous avons écrit une seule ligne de code
Correction : sans qu'on ait besoin d'écrire une seule ligne de code d'envoi au serveur (bien **que**, strictement parlant, nous avons écrit une seule ligne de code

Erreur : C'est arrivé par magie – et instantanément aussi, bien que ça devienne plus évident plus tard.
Correction : C'est arrivé par magie – et instantanément aussi"**!**" 

Erreur : Ce qui est arrivé est que la collection côté serveur a été informé
Correction : Ce qui est arrivé**, c'**est que la collection côté serveur a été informé**e**

# Chapitre 4.5

Erreur : Bien que cette magie est d'une aide considérable, 
Correction : Bien que cette magie **soit** d'une aide considérable,

**Comment by SachaG** [comment]
The french version has its own repo for issues and corrections: https://github.com/DiscoverMeteor/DiscoverMeteor_fr
