### ISSUE TITLE
post vs. postInsert

### ISSUE THREAD

**Issue by cnewfeldt** [DiscoverMeteor/book#433]
Hi, 

I've noticed on the posting chapter: "Finally, we'll go back to our lib/collections/posts.js file and add a Meteor server-side Method that will upvote posts:" the code snippet below states:

<pre>
Meteor.methods({
  post: function(postAttributes) {
    //...
  },

  upvote: function(postId) {
</pre>

I'm pretty sure it should be:

<pre>
Meteor.methods({
  postInsert: function(postAttributes) {
    //...
  },

  upvote: function(postId) { 
</pre>

Cheers, 

Cary.

**Comment by cnewfeldt** [comment]
note; this is in the logged in area of the book on the web site.

**Comment by SachaG** [comment]
Good catch, thanks!
