### ISSUE TITLE
chapter - Creating a Meteor Package 

### ISSUE THREAD

**Issue by stinghz** [DiscoverMeteor/book#434]
In the book , the code for the two methods is wrong.  Seems the content for insert  method and content for update method is reversed. 

Meteor.call('postInsert', post, function(error, result) {
  if (error) {
    // display the error to the user
    Errors.throw(error.reason);

Posts.update(currentPostId, {$set: postProperties}, function(error) {
  if (error) {
    // display the error to the user
    Errors.throw(error.reason);

  // show this result but route anyway
  if (result.postExists)
    Errors.throw('This link has already been posted');

**Comment by SachaG** [comment]
Yep, thanks for letting us know!
