### ISSUE TITLE
Chapter 13 - Voting: Old server method name "post" should be "postInsert"

### ISSUE THREAD

**Issue by mynameiskyleok** [DiscoverMeteor/book#435]
![ch13-function-naming-error](https://cloud.githubusercontent.com/assets/4357572/8137080/cfabac90-110e-11e5-9977-02b957f94ec8.png)

I verified this error is only in the code block shown in the screenshot, and is not present in the actual 13-1 commit. This is a minor issue, but would help for those like myself who have typed out all the code in the book and use the nearby code as a reference point when making updates.

**Comment by SachaG** [comment]
Good catch, thanks!
