### ISSUE TITLE
Chapter 4 - Collections : Client and Server

### ISSUE THREAD

**Issue by jpollone** [DiscoverMeteor/book#436]
> “Code inside folders that are not client/ or server/ will run in both contexts. So the Posts collection is available to both client and server. However, what the collection does in each environment can be pretty different.”

Prior instructions (Chapter 3 - Templates : Meteor Templates) stated to create the posts collection under /client/template/posts, so the statement above is incorrect.

**Comment by tmeasday** [comment]
Hi @jpollone - I think you are confused by the two files both named `posts.js`. 

The _template_ file lives in the `client/` directory. The _collection_ file should not.

**Comment by jpollone** [comment]
Ah, yes.  Please close this issue.
