### ISSUE TITLE
Chapter 4 - Collections : Client-Server Communication

### ISSUE THREAD

**Issue by jpollone** [DiscoverMeteor/book#437]
> Let’s create a new post. In one of the browser windows, run an insert command:
> 
> ```
> ❯ Posts.find().count();
> 1
> ❯ Posts.insert({title: "A second post"});
> 'xxx'
> ❯ Posts.find().count();
> 2
> ```

The console reference should include the initialization of Posts, which I needed to do by creating a server/server.js file:

```
Posts = new Mongo.Collection('posts');
```

**Comment by tmeasday** [comment]
Hi @jpollone - sounds like a side-effect of your issue here: https://github.com/DiscoverMeteor/book/issues/436

**Comment by jpollone** [comment]
Yes, correct.  File should have been created at lib/collections/posts.js, which has this initialization.
