### ISSUE TITLE
Helper misnamed in pub/sub chapter

### ISSUE THREAD

**Issue by tmeasday** [DiscoverMeteor/book#440]
As reported by Chris:

In the publications and subscriptions chapter, it says to update to code as such:

```
Template.posts.helpers({
  posts: function(){
    return Posts.find({author: 'bob-smith', category: 'JavaScript'});
  }
});
```

However, after looking through my code and the GitHub repo, I could not find "Template.posts.helpers". Is there any chance it was meant to be "Template.postsList.helpers"?

**Comment by SachaG** [comment]
This is sidebar code, so it's not supposed to match Microscope's codebase. I'll add a note to clarify this.
