### ISSUE TITLE
[ru.discovermeteor.com] Old bootstrap package 

### ISSUE THREAD

**Issue by flakessp** [DiscoverMeteor/book#442]
http://ru.discovermeteor.com/chapters/getting-started/

The translation asks to install "meteor add mizzao:bootstrap-3" which is not official. Commit at github points to actual official TWBS package though.  

Had some issues with this later when i was reading book for the first time.

**Comment by SachaG** [comment]
The Russian translation has its own repo: https://github.com/DiscoverMeteor/DiscoverMeteor_Ru
