### ISSUE TITLE
Wrong green highlighting in 'Voting' Chapter (submit 13-5)

### ISSUE THREAD

**Issue by stevenjmarsh** [DiscoverMeteor/book#446]
for the "...add links in the header:" code, client/templates/includes/header.html

the highlighted line is...

```
</div>
```

but should be the line above... (where the code change is occurring)

```
<a href="{{pathFor 'home'}}" class="navbar-brand">Microscope</a>
```

**Comment by SachaG** [comment]
Thanks!
