### ISSUE TITLE
Getting Started section - Wrong Command for Adding Bootstrap ?

### ISSUE THREAD

**Issue by chnl** [DiscoverMeteor/book#45]
"$ mrt add bootstrap"
shouldn't it be...
"$ meteor add bootstrap"
?

**Comment by tmeasday** [comment]
Both commands should work, no?

**Comment by chnl** [comment]
I get the following error when I use mrt...
/usr/lib/node_modules/meteorite/lib/project.js:224
          throw("Package named " + pkgName + " doesn't exist in your meteor in
                                           ^
Package named boostrap doesn't exist in your meteor installation, smart.json, or on atmosphere

Meteor command works instead.  Could be my instance though.

**Comment by tmeasday** [comment]
Huh, so strange. What does `mrt list` report?

**Comment by chnl** [comment]
It's in mrt list  - I started installing / configuring on ec2 without using the Meteoric script.
