### ISSUE TITLE
Code Error in Advanced Publications Sidebar - Multiple Collections in a Single Subscription

### ISSUE THREAD

**Issue by evolross** [DiscoverMeteor/book#452]
When you get to the first code block in the section _Multiple Collections in a Single Subscription_  showing how you would need to write a publication to get all the comments for the `topPostIds`, your code block shows you querying Mongo as if `topPostIds` was a string.  To accurately execute what you're implying, shouldn't this code block use the `$in` operation? Like this:

```
Meteor.publish('topComments', function(topPostIds) {
    return Comments.find({postId: {$in: {topPostIds}});
});
```

**Comment by SachaG** [comment]
Good point!
