### ISSUE TITLE
Package.on_use() , add_files()  vs. onUse() , addFiles() - Chapter 17, Commit 17-1

### ISSUE THREAD

**Issue by stevenjmarsh** [DiscoverMeteor/book#453]
I noticed an inconsistency in method names. I 'expect' on_use() and add_files() may still work, but are deprecated?

onUse() and addFiles() are listed in the docs, and seemed to be used instead in other chapters. Note, I did not check source code to verify whether on_use and add_files are still supported.

```
   thanks.
```

**Comment by SachaG** [comment]
Thanks!
