### ISSUE TITLE
Wrong code highlighted

### ISSUE THREAD

**Issue by CBedzz** [DiscoverMeteor/book#454]
Just thought I would pass this along for book editing.

In the Adding a Link to the header section of the Creating Posts Chapter, the three highlighted lines of the header.html code need to be moved up one line so the whole new <ul> section is highlighted, not missing the first <ul> tag and instead highlighting the already coded beginning of the next <ul> (with class of nav navbar-nav navbar-right).

**Comment by SachaG** [comment]
Thanks, I'll fix it.
