### ISSUE TITLE
Bizarre syntax

### ISSUE THREAD

**Issue by dustincoates** [DiscoverMeteor/book#455]
First noticed in `Routing`. May be in other chapters but I haven't come across it yet.

See the screenshot below:

![screen shot 2015-09-24 at 4 42 58 pm](https://cloud.githubusercontent.com/assets/1909592/10086321/c70528fe-62db-11e5-840d-8bb236ae117e.png)

This isn't happening for all code snippets and not happening for, say, just JS snippets but happening seemingly at random.

**Comment by SachaG** [comment]
I haven't noticed this myself. Could this be a browser bug?

**Comment by dustincoates** [comment]
Possibly. I just went back and it's no longer happening (same browser), so not sure what was going on.
