### ISSUE TITLE
remark for creating posts/post_submit.js code block

### ISSUE THREAD

**Issue by jeroentbt** [DiscoverMeteor/book#46]
When rewriting the `submit form` event handler to use the post Method, the passed variable changes from `e` to `event` and the relevant changed code is not highlighted like in the other code blocks.

before:

``` javascript
Template.postSubmit.events({
  'submit form': function(e) {
    e.preventDefault();

    var post = {
      url: $(e.target).find('[name=url]').val(),
      title: $(e.target).find('[name=title]').val(),
      message: $(e.target).find('[name=message]').val()
    }

    post._id = Posts.insert(post);
    Meteor.Router.to('postPage',post);
  }
});
```

after:

``` javascript
Template.postSubmit.events({
  'submit form': function(event) {
    event.preventDefault();

    var post = {
      url: $(event.target).find('[name=url]').val(),
      title: $(event.target).find('[name=title]').val(),
      message: $(event.target).find('[name=message]').val()
    }

    // this should be highlighted
    Meteor.call('post', post, function(error, id) {
      if (error)
        return alert(error.reason);

      Meteor.Router.to('postPage', id);
    });
    // end highlight
  }
});
```

This book being an introduction, I'd prefer the more verbose `event`.

**Comment by EyeDreamt** [comment]
I didn't even catch that on my read through. It really doesn't matter, the code works either way as long as the two match and if you are just adding the highlighted code it'd work, but consistency would be good. What surprised me in the block of code was the shorthand if. I know a lot of newbies I teach JavaScript get caught up on the if statements and in a tutorial I'd expect to see them just in case.

**Comment by jeroentbt** [comment]
@EyeDreamt It is indeed for consistency's sake I posted this issue.
I have seen `if` statements in the code written both ways. It would indeed be nice for the book if all code rigorously followed a styleguide.

**Comment by SachaG** [comment]
We should be using "e" everywhere, thanks for catching this. 

As for the `if` statement, when there's only one line in the statement we use the short-hand, otherwise we use the regular syntax. See also the Meteor style guide: https://github.com/meteor/meteor/wiki/Meteor-Style-Guide
