### ISSUE TITLE
http://zh.discovermeteor.com/chapters/advanced-reactivity/

### ISSUE THREAD

**Issue by wangyueming** [DiscoverMeteor/book#462]
使用一些被称为 comptations 的代码
should be
使用一些被称为 computations 的代码

**Comment by SachaG** [comment]
中文版有自己的仓库，请不要在这里发帖子了。

https://github.com/DiscoverMeteor/DiscoverMeteor_zh

**Comment by wangyueming** [comment]
Sorry for being late to see your comment. I have re-issued them in Chinese version.
