### ISSUE TITLE
Minor error in chapter/creating-posts#adding-a-link-to-the-header

### ISSUE THREAD

**Issue by dhorner** [DiscoverMeteor/book#463]
The green highlight in the code for #adding-a-link-to-the-header is off by one line.  It needs to include the line above it and not the last line highlighted.  

it currently highlights:

```
      <li><a href="{{pathFor 'postSubmit'}}">Submit Post</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
```

and it should be highlighting: 

```
      <ul class="nav navbar-nav">
        <li><a href="{{pathFor 'postSubmit'}}">Submit Post</a></li>
      </ul>
```

**Comment by SachaG** [comment]
Good point, thanks!
