### ISSUE TITLE
“路由”章节一些重复操作和错误单词

### ISSUE THREAD

**Issue by nmgwddj** [DiscoverMeteor/book#465]
> 接下来，我们可以恢复之前的根路径 / URL 映射到 postsList 模板。然后我们在根目录创建一个 /lib 目录，并在里面创建 router.js 文件：

在“集合”一章种就已经创建了 lib 文件夹用来存放 Posts 集合，这里又让新建一次，会容易迷惑人。

> 默认情况下，Iron Router 会为这个路由规则，指定相同名字的模板。而如果路径（path 参数）没有指定，它也会根据路由规则的名字，去指定同样名字的路径。举个例子，在上面的设置中，如果我们不提供 path 参数，那么访问 /postsList 将会自动获取到 postList 模板。

后面应该是自动获取到 postsList，不是 postList，少写了一个字母 s。

**Comment by nmgwddj** [comment]
> 在路由规则的 data 方法里面，this 对应于当前匹配的路由对象，我们可以使用 this.params 去访问一个`比配项`（在 path 中通过 : 前缀去表示它们）。

`比配项` 应该是 `匹配项`

**Comment by hongbo-miao** [comment]
@nmgwddj English here only please. And I think you create the issue at wrong place... This is English book.
