### ISSUE TITLE
Table of Contents is in chaos

### ISSUE THREAD

**Issue by hongbo-miao** [DiscoverMeteor/book#466]
The order of Table of Contents in Discover Meteor website page is in chaos now. please fix. thanks!
![order](https://cloud.githubusercontent.com/assets/3375461/10713354/7d332ca2-7a88-11e5-8172-e2332d962c7e.png)

**Comment by SachaG** [comment]
Sorry, that happens sometimes when we deploy for an obscure reason… Just fixed it :)

**Comment by hongbo-miao** [comment]
Thanks!
