### ISSUE TITLE
remark for Chapter 7 "creating posts" ending paragraph, next chapter

### ISSUE THREAD

**Issue by jeroentbt** [DiscoverMeteor/book#47]
You wrote

> But any app that lets users create content also needs to give them a way to edit or delete it. That's what the next chapter will be all about.

But the next chapter is "Latency Compensation" (which is a 'sidebar')

**Comment by EyeDreamt** [comment]
Sidebars aren't considered chapters, but rather "deep-dives" into the features discussed in the chapter before. Hence why they are x.5. They are extensions of the current chapter. They also aren't required for the tutorial. The thought is a true beginner can read just the chapters and not the sidebars and follow along just fine.

**Comment by jeroentbt** [comment]
@EyeDreamt True.
Still, I just "next" my way through the book. Reading that sentence led me to believe I was going to read about post editing when I clicked on the next chapter link on the bottom of the page.
So either the sidebars need to be more (or less) prominently linked to, or the wording needs to change.

I'm just throwing these issues in here as I find things that don't seem to match my expectations, look wrong, etc. Just for the sake of making the book better. Sacha and Tom can choose to ignore these, no hard feelings :).

**Comment by jeroentbt** [comment]
Same remark for chapter 10, Comments.

**Comment by SachaG** [comment]
We'll try to make the wording clearer somehow :)
