### ISSUE TITLE
Getting Started - Adding a package

### ISSUE THREAD

**Issue by juancobe** [DiscoverMeteor/book#475]
This is a good time to check which packages we're running. It turns out that in addition to the one we just added, Meteor also comes with a few packages enabled out of the box. You can see the full list by opening the **versions** file inside the hidden .meteor directory:

Should read

This is a good time to check which packages we're running. It turns out that in addition to the one we just added, Meteor also comes with a few packages enabled out of the box. You can see the full list by opening the **packages** file inside the hidden .meteor directory:

**Comment by SachaG** [comment]
Yep.
