### ISSUE TITLE
"and den kellner"  | Chapter: templates 

### ISSUE THREAD

**Issue by phil3737** [DiscoverMeteor/book#478]
Chapter: http://de.discovermeteor.com/chapters/templates/
Is: **and** den Kellner übergeben
Should be: *_an den *_Kellner übergeben

**Comment by SachaG** [comment]
Sorry, this repo is only for the English version. You can find the German repo here: https://github.com/DiscoverMeteor/DiscoverMeteor_De

**Comment by phil3737** [comment]
sry - reposted it there, thanks.
