### ISSUE TITLE
Chapter: Templates | dasss vs dass

### ISSUE THREAD

**Issue by phil3737** [DiscoverMeteor/book#479]
Chapter: http://de.discovermeteor.com/chapters/templates/
Is: der das Array postsData zurückgibt, **dasss**
Should be: der das Array postsData zurückgibt, **dass**
Mistake: three "s" vs. two "s"

**Comment by SachaG** [comment]
Sorry, this repo is only for the English version. You can find the German repo here: https://github.com/DiscoverMeteor/DiscoverMeteor_De

**Comment by phil3737** [comment]
sry - reposted it there, thanks.
