### ISSUE TITLE
Probably forgot to update "Last updated on ..." https://www.discovermeteor.com/

### ISSUE THREAD

**Issue by yanisurbis** [DiscoverMeteor/book#481]
Since you've switched to React.

**Comment by SachaG** [comment]
Just to clarify, the book hasn't been updated to React, just the app that lets you read/access the book :)

**Comment by sferoze** [comment]
@SachaG Ahh ok, I think the message on the book discovermeteor website is confusing. 

When I logged in, I had thought that the app microscope and the tutorial was updated to use React. 

I learned the proper was to create a full user applications using the techniques from Discover Meteor with Blaze.

Now that I am switching to React, I need to relearn the proper patterns for React.

I really wish there was a version of Discover Meteor that used React. So I can learn the proper way to do all the things you did in Discover Meteor with Blaze.
