### ISSUE TITLE
Ru: Introduction

### ISSUE THREAD

**Issue by Evgeniya-Jane** [DiscoverMeteor/book#483]
Руссский перевод. Введение. абзац 3.

Вам вовсе не нужно проделывать эти шаги в реальности, чтобы понять, что он    **также** исчез.
->
Вам вовсе не нужно проделывать эти шаги в реальности, чтобы понять, что он _действительно_ также исчез.

**Comment by SachaG** [comment]
Sorry, this repo is only for the english version. See https://github.com/DiscoverMeteor/DiscoverMeteor_Ru
