### ISSUE TITLE
Chapter 8: commit 8.2 update and remove failed: access denied

### ISSUE THREAD

**Issue by jeroentbt** [DiscoverMeteor/book#49]
As has been mentioned in the comments of this chapter, commit 8.2 does not offer offer a functioning update or delete. 
In the next part of the chapter you state:

> This is the extent of our client-side code, and it works well.

But it doesn't, because at this point even a simulation will not complete due to an access denied.

Maybe add

``` javascript
Posts.allow({
  update: function(){return true},
  remove: function(){return true}
});
```

to posts.js and tell the reader you will get back to this part later?
Or just make it clear in the text it will not work :).

EDIT: allow update and remove must be a function

**Comment by tmeasday** [comment]
You're right! The chronology is a bit confused because once upon a time we didn't remove insecure until this point.

We'll fix this in the next update.

**Comment by izzetagoren** [comment]
thanks for pointing this out jeroenbtb - I thought I was going crazy. I have spent the last two hours spinning my wheels. 

I am working thru the book on and between flights so the pdf version of the book is important to my progress. Sounds like the discover team is updating the html version with greater accuracy.

**Comment by SachaG** [comment]
We just updated the HTML/PDF/ePub/mobi versions recently, so if you redownload the book now you should have the latest version.
