### ISSUE TITLE
CHAPTER 1: Newly spun up Meteor makes a server and client folder

### ISSUE THREAD

**Issue by jasonnmark** [DiscoverMeteor/book#490]
Book says:

This command will download Meteor, and set up a basic, ready to use Meteor project for you. When it's done, you should see a directory, microscope/, containing the following:

.meteor
microscope.css
microscope.html
microscope.js
#### 

Actually seeing a client and server folder...

**Comment by JeremyIglehart** [comment]
+1

Following the instructions:

`$ meteor create microscope` on the latest version of meteor (1.3) makes this:

https://github.com/JeremyIglehart/Basic-Meteor-Build-For-Microscope

Here's a copy paste from my `$ls -la`

```
$ ls -la
total 16
drwxr-xr-x   7 jeremy  staff  238 Apr 11 19:58 .
drwxr-xr-x  23 jeremy  staff  782 Apr 11 19:58 ..
-rw-r--r--   1 jeremy  staff   13 Apr 11 19:58 .gitignore
drwxr-xr-x  10 jeremy  staff  340 Apr 11 19:58 .meteor
drwxr-xr-x   5 jeremy  staff  170 Apr 11 19:58 client
-rw-r--r--   1 jeremy  staff  151 Apr 11 19:58 package.json
drwxr-xr-x   3 jeremy  staff  102 Apr 11 19:58 server
```

And copy paste from `$tree`

```
$ tree
.
├── client
│   ├── main.css
│   ├── main.html
│   └── main.js
├── package.json
└── server
    └── main.js

2 directories, 5 files
```

**Comment by jasonnmark** [comment]
The directions in Chapter 1 (sorry not Chapter 2) says:

https://book.discovermeteor.com/chapter/getting-started

> This command will download Meteor, and set up a basic, ready to use Meteor project for you. When it's done, you should see a directory, microscope/, containing the following:
> 
> ```
> .meteor
> microscope.css
> microscope.html
> microscope.js
> ```

Which was correct with an older version of Meteor... but the new version shows what you outlined above.

**Comment by SachaG** [comment]
Yes, the default file structure has changed. We'll update the book.
