### ISSUE TITLE
Meteor Free Tier is Gone - Broke the Live Instances

### ISSUE THREAD

**Issue by JeremyIglehart** [DiscoverMeteor/book#491]
Are there plans to switch to a different kind of hosting service for the live instances.

RIP Meteor Free Tier...

Example: [This live example is down -> http://meteor-book-chapter11-2.meteor.com/](http://meteor-book-chapter11-2.meteor.com/)

**Comment by darrellodonnell** [comment]
I would think that there is some cheap-as-heck service that could be used?

**Comment by JeremyIglehart** [comment]
I'm not sure if this will work or not, but the free tier of Heroku looks pretty good to me.

https://www.heroku.com/pricing

Of course, this would require someone to setup new links and then change them in the book.

I'd be happy to help set this up if the authors want some help.  (In other words, I'm volunteering to do the click time to setup Heroku instances for the chapters...)

**Comment by jmar42** [comment]
Can you post instructions here?

**Comment by SachaG** [comment]
I'm afraid we'll just have to remove links to the free instances altogether :(
