### ISSUE TITLE
Reference to the wrong file

### ISSUE THREAD

**Issue by JeremyIglehart** [DiscoverMeteor/book#492]
In chapter 2 you say

```
This is a good time to check which packages we're running. It turns out that in addition to the one we just added, Meteor also comes with a few packages enabled out of the box. You can see the full list by opening the versions file inside the hidden .meteor directory:
```

And then you show the contents of `.meteor/packages`

Maybe you should say the name of the actual file above the code pasted from `.meteor/packages`

I found this to be misleading.

**Comment by SachaG** [comment]
Good point, that's very confusing!
