### ISSUE TITLE
Chapter 2.5 - Meteor Deploy - No Free Tier

### ISSUE THREAD

**Issue by JeremyIglehart** [DiscoverMeteor/book#493]
Regarding: [Chapter 2.5 Meteor Deploy](https://book.discovermeteor.com/chapter/deploying)

[Meteor has shut down the free tier](https://forums.meteor.com/t/meteor-com-free-hosting-ends-march-25-2016/19308)

I feel like this is something worth mentioning here in this chapter.  Even though I'm sure meteor deploy still works if you're a paying customer - it's not as easy as having an account and deploying for free anymore.

Thanks for the book, love it so far.

**Comment by SachaG** [comment]
Yep, we'll update this.
