### ISSUE TITLE
Chapter 5.5 Session is not supported by default.

### ISSUE THREAD

**Issue by JeremyIglehart** [DiscoverMeteor/book#494]
Because the session is not supported by default, as of new versions of meteor one now must add it...

`$ meteor add session`

... for things to work in this chapter.  I've tested this and it works for me now.

You might want to make reference to this in the book in chapter 5.5 and later on if you make use of the Session variable.

I found this solution here: http://stackoverflow.com/questions/17092565/meteor-session-is-not-defined

**Comment by SachaG** [comment]
Good catch, thanks!
