### ISSUE TITLE
Update to Meteor 1.3 timeline?

### ISSUE THREAD

**Issue by philipmjohnson** [DiscoverMeteor/book#499]
I will be teaching 65 students about Meteor in Fall 2016 and would like to make Discover Meteor a required text if it is Meteor 1.3 compliant.

Do you have a timeline for a new version of the book? (I used it last Fall in my class and it was very, very helpful.)

Thanks.

**Comment by SachaG** [comment]
We have a small compatibility update in the works but at this point we're not planning on adapting the book for the 1.3 guidelines. I would suggest checking out our study plan instead: https://www.discovermeteor.com/blog/study-plan-meteor-1-3/
