### ISSUE TITLE
Broken Links when Launching instances.

### ISSUE THREAD

**Issue by pev115** [DiscoverMeteor/book#500]
Hello,

Following along with the book, I have found that the "Launch instance" links provided with the commits don't work.

For example for commit 5-2 : http://meteor-book-chapter5-2.meteor.com/ gives me a server not found error (like all the others).

Is that something expected or I'm I doing something wrong? I just want to make sure I didn't miss a step like actually launching the instance from somewhere before accessing it.

Thanks!

**Comment by SachaG** [comment]
Yes, Meteor's free hosting service has been discontinued so the instances are not up anymore, sorry.
