### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SamJWeissman** [DiscoverMeteor/book#506]
Had a quick opinion question. 

I'm looking to learn React in addition to Meteor. Would you recommend attempting to convert to React as I complete each chapter... or finish the entire book first, and then go through your Blaze to React articles?

Thank you in advance!

( I tried emailing this question to hello@discovermeteor.com but got an auto-response saying the email failed )

**Comment by SachaG** [comment]
I'm not sure you really need the book if you want to learn React, but in any case I'd probably recommend going through the whole book first and then focusing on React. 

And it's weird that this email doesn't work, I'll look into it, thanks.

**Comment by SamJWeissman** [comment]
@SachaG 

Thank you for such a quick response! ( more focused on learning Meteor  -- just want to use React instead of Blaze once I've got a grip on things )

Closing this.

--Sam
