### ISSUE TITLE
Chapter 13 - Voting minor typo

### ISSUE THREAD

**Issue by hackerfriendly** [DiscoverMeteor/book#51]
Minor typo in the book: Commit 13-2 uses "upvotable" in the upvotedClass definition, but "upvoteable" in the event definition (note the E). The code on Github correctly uses "upvotable" for both. Voting no longer works if the definitions don't match, and it's subtle.

Just a minor annoyance for those of us copying and pasting along at home.

**Comment by SachaG** [comment]
Good catch, thanks!
