### ISSUE TITLE
Videos should be downloadable

### ISSUE THREAD

**Issue by jamesdwilson** [DiscoverMeteor/book#56]
Hey, really love most of the screencasts, that is largely why I bought the PRO package, but I am disappointed you don't allow downloading of the original video files.

I of course, will have to manually find a way, but I shouldn't feel like I have to go out of my way to "hack" it, it should just be downloadable, and in the original video quality without vimeo compression.

It would be really nice to have a zip file that contains both sample code and the screencast in one bundle even, if not a-la-carte.

Thank you

**Comment by SachaG** [comment]
You can actually download them from Vimeo. Just click on the title of the video itself to access its Vimeo page, and you'll see a download link there. 

We'll think about how we can also provide the original quality video, that's a good idea.
