### ISSUE TITLE
Keep getting prompted to enter password (modal pop up) every time I try to access the content

### ISSUE THREAD

**Issue by booyaa** [DiscoverMeteor/book#58]
Now I'm being told the token has expired

**Comment by tmeasday** [comment]
Are you always visiting the link in gumroad's email?

You can just head to http://book.discovermeteor.com

**Comment by booyaa** [comment]
ah thanks for that will bookmark that instead. i've been a bit absent minded and kept forgeting to download the pdf (you'd have thought after 3 or 4th time i would've done it.

**Comment by tmeasday** [comment]
Oh, no worries. I'd consider reading it from the site instead, I think it's better that way myself (and more frequently updated).
