### ISSUE TITLE
Misleading screenshot?

### ISSUE THREAD

**Issue by danlourenco** [DiscoverMeteor/book#6]
In the chapter on latency compensation, the image under Commit 7-5-1 shows an "edit" option next to the "submitted by" information (see image below).  Correct me if I'm wrong, but I don't believe we've added in that edit functionality yet.  I've gone back through my code and skimmed previous chapters and don't see any reference to that.  It may throw off beginners such as myself to have a screenshot displaying functionality not currently implemented thus far.
![s5-1](https://f.cloud.github.com/assets/1965272/556849/14a5a376-c3e3-11e2-96e5-eefb5699585f.png)

Thanks!

**Comment by tmeasday** [comment]
Thanks Dan, you are completely right!

We'll make sure we fix this on our next run through the code.

**Comment by SachaG** [comment]
Good catch, I'm fixing it now.
