### ISSUE TITLE
ePub and Kindle downloads - permissions issue

### ISSUE THREAD

**Issue by dickiedyce** [DiscoverMeteor/book#63]
Hi,

Just bought the premium edition of the book - but can't download the ePub or Kindle edition :-( Unauthorised access?

Login: meteor@dyce.com

Kind regards,

R

**Comment by SachaG** [comment]
Sorry about that, there was a typo in the file name. It should work fine
now :)

**Comment by dickiedyce** [comment]
Sacha,

Thanks for that. 

Kind regards,

R

On 8 Aug 2013, at 09:31, Sacha Greif notifications@github.com wrote:

> Sorry about that, there was a typo in the file name. It should work fine 
> now :) 
> 
> On Thu, Aug 8, 2013 at 5:09 PM, dickiedyce notifications@github.com wrote: 
> 
> > Hi, 
> > 
> > Just bought the premium edition of the book - but can't download the ePub 
> > or Kindle edition :-( Unauthorised access? 
> > 
> > Login: meteor@dyce.com 
> > 
> > Kind regards, 
> > 
> > R 
> > 
> > — 
> > Reply to this email directly or view it on GitHubhttps://github.com/DiscoverMeteor/book/issues/63 
> > . 
> > 
> > —
> > Reply to this email directly or view it on GitHub.

Richard Dyce MA (Cantab.) MIET
Director, Dyce & Sons Ltd.

Registered Number: SC446474
VAT Number: 161 5030 49

Incorporated in Scotland.

Web:        http://dyce.com
Bio:          http://www.linkedin.com/in/rjdyce

Confidentiality Notice
The contents of this e-mail and any attachments are intended for the named addressee only and may be confidential. Unless you are the named addressee or authorised to receive the e-mail of the named addressee you may not disclose, use or copy the contents of the e-mail. If you received the e-mail in error, please contact the sender immediately and then delete the e-mail. Dyce & Sons Ltd. does not accept responsibility for this message and any views or opinions contained in this e-mail are solely those of the author unless expressly stated otherwise.
