### ISSUE TITLE
poor quality, even on HD

### ISSUE THREAD

**Issue by sihingkk** [DiscoverMeteor/book#65]
http://book.discovermeteor.com/video/the-router/

the quality of this video is really poor. Is impossible too read what is written in this screencast? Are you sure this is premium content? (eg. the testing screencast is working fine...)

**Comment by dickiedyce** [comment]
Yeah. It is quite poor. Looked at the repo, but only final code available :-( If you squint you can make most of it out, but zooming would have been really useful.

**Comment by tmeasday** [comment]
Apologies for this folks. I've been wanting to update the video for some time but have been holding out due to the impending (...) release of Iron Router, the new "super-router" that I've been working on with Chris Mather. 

See here: https://github.com/DiscoverMeteor/book/issues/9

**Comment by dickiedyce** [comment]
Thanks for this. Baited breath...
