### ISSUE TITLE
Taxonomy & Search example

### ISSUE THREAD

**Issue by dohomi** [DiscoverMeteor/book#67]
Hello,

I really like the content and the style of the book, its very informative and a very good step in into the world of Meteor. 

I would love to see one chapter for taxonomy and searching over the Posts object. I'm looking for a starting point but find myself a bit lost. Not sure if this should happen on the client or the server side - even how to handle the subscriptions in this matter.

Would be great if you guys could deliver one chapter about this or is there somewhere an example where I could have a look?

Regards,
Dominic

**Comment by SachaG** [comment]
Actually, we'd love to add search to Telescope, and we'd also write a chapter about it for the book. But as there is no "standard" way to do search in Meteor apps yet, we're still thinking about how best to tackle this…

**Comment by dohomi** [comment]
Hopefully by the time I am in need for this, you have it all sorted :)

**Comment by SachaG** [comment]
I've added search to [Telescope](https://github.com/SachaG/Telescope/). I'll probably write a chapter about it in the near future, but for now I'll close this :)
