### ISSUE TITLE
Meteor 0.6.5

### ISSUE THREAD

**Issue by chaodoze** [DiscoverMeteor/book#68]
Getting an error:
While building package `accounts-ui-bootstrap-dropdown`:
error: no such package: 'accounts-urls'

when upgrading to the latest Meteor 0.6.5.

Hope you can let us know a fix soon!

**Comment by interfaith** [comment]
yes when daring to use the new meteor , exactly the same error 
how now ?

**Comment by tmeasday** [comment]
The package was just updated and it should be fixed now. Let us know.

**Comment by SachaG** [comment]
I'm closing this to avoid duplicate threads. You can use this one instead: https://github.com/DiscoverMeteor/Microscope/issues/25
