### ISSUE TITLE
Updated to meteor 0.6.5

### ISSUE THREAD

**Issue by philgoebel** [DiscoverMeteor/book#69]
Ubuntu 13.04
Node -v 11.6-pre
Hi, I updated meteor to 0.6.5 and am now getting this error when starting the meteor server:

Your app is crashing. Here's the latest log.

=> Errors prevented startup:

While building package `accounts-ui-bootstrap-dropdown`:
error: no such package: 'accounts-urls'

=> Your application has errors. Waiting for file change.

**Comment by philgoebel** [comment]
Oops didn't see the already opened issue on this topic, I will follow that thread.

**Comment by naturalprogrammer** [comment]
Me too am facing the same issue while creating a new project and doing 
"mrt add accounts-ui-bootstrap-dropdown":

=> Errors while scanning packages:

While building package `accounts-ui-bootstrap-dropdown`:
error: no such package: 'accounts-urls'

**Comment by scottmagdalein** [comment]
Confirming this as well. Same error. When I remove the `accounts-ui-bootstrap-dropdown` package and attempt with just the `accounts-ui` package, I get the same error.

**Comment by tmeasday** [comment]
The package was just updated and it should be fixed now. Let us know.

**Comment by SachaG** [comment]
I'm closing this to avoid duplicate threads. You can use this one instead: https://github.com/DiscoverMeteor/Microscope/issues/25
