### ISSUE TITLE
Changed code not being highlighted properly

### ISSUE THREAD

**Issue by GiraffeSlacks** [DiscoverMeteor/book#7]
I may be missing something but on http://book.discovermeteor.com/chapter/errors/ there is a codeblock for 'client/views/posts/post_submit.js'. In this codeblock there is only a single line being highlighted but when compared to my version of 'client/views/posts/post_submit.js' there are many more changes.

I have not skipped any of the regular chapters though I have skipped every .5 chapter so maybe that's where the problem lies.

Below is my code up to this point.

``` javascript
Template.postSubmit.events({
    'submit form': function(event) {
        event.preventDefault();

        var post = {
            url: $(event.target).find('[name=url]').val(),
            title: $(event.target).find('[name=title]').val(),
            message: $(event.target).find('[name=message]').val()
        }

        Meteor.call('post', post, function(error, id) {
            if (error)
                return alert(error.reason);

            Meteor.Router.to('postPage', id);
        });
    }
});
```

**Comment by SachaG** [comment]
You're right, that's a mistake on our part. Thanks for pointing it out!
