### ISSUE TITLE
commentsCount helper not removed from code snippet on page 134 of pdf

### ISSUE THREAD

**Issue by lindsayrattray** [DiscoverMeteor/book#71]
The text below is from the book:

Finally, we can just simply remove the commentsCount helper from client/views/posts/post_item.js, as the field is now directly available on the comment.

```
Template.postItem.helpers({
  ownPost: function() {
    return this.userId == Meteor.userId();
  },
    domain: function() {
        var a = document.createElement('a');
        a.href = this.url;
        return a.hostname;
    },
       commentsCount: function() {
         return Comments.find({postId: this._id}).count();
       }
});
```

This should not include (or show with a strikethrough?)

```
       ,
       commentsCount: function() {
         return Comments.find({postId: this._id}).count();
       }
```

**Comment by SachaG** [comment]
You're right, it actually highlights those lines in red in the online version to indicate we're removing them, but since that doesn't carry over to the PDF or ePub versions I can see how it'd be confusing. I'll just remove that code block.
