### ISSUE TITLE
Last code box on the rss api.

### ISSUE THREAD

**Issue by pnunn** [DiscoverMeteor/book#72]
The console example uses "/api/posts/blah", it should be /api/post/blah"

Peter.

**Comment by SachaG** [comment]
No, I just checked and it's `posts` with an "s". Unless I don't understand what you mean?

**Comment by pnunn** [comment]
The route (16-5) is '/api/post/:_id':  The last screen shot shows
curl "http://localhost:3000/api/posts/5blahblah"
It should be "http://localhost:3000/post/5blahblah" I think to return one post rather than the whole posts collection.

Peter.

**Comment by SachaG** [comment]
This seems more like a personal preference in API design, but for example
this article recommends using the plural noun everywhere to avoid any
inconsistencies:

https://blog.apigee.com/detail/restful_api_design_plural_nouns_and_concrete_names

**Comment by pnunn** [comment]
That's fine Sacha, all I'm saying is that the code isn't consistent in the example chapter. The code in has the singular route for the individual post, but the plural for the curl invocation of it, which doesn't work... Not a big deal, just a consistency thing in the book.

Peter.

On Wed, 28 Aug 2013 12:38:49 AM Sacha Greif wrote:

> This seems more like a personal preference in API design, but for example
> this article recommends using the plural noun everywhere to avoid any
> inconsistencies:
> 
> https://blog.apigee.com/detail/restful_api_design_plural_nouns_and_concrete_names
> 
> On Wed, Aug 28, 2013 at 2:43 PM, Peter Nunn notifications@github.comwrote:
> 
> > The route (16-5) is '/api/post/:_id': The last screen shot shows
> > curl "http://localhost:3000/api/posts/5blahblah"
> > It should be "http://localhost:3000/post/5blahblah" I think to return one
> > post rather than the whole posts collection.
> > 
> > Peter.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/DiscoverMeteor/book/issues/72#issuecomment-23392739
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/DiscoverMeteor/book/issues/72#issuecomment-23396463

## 

Director
InfoTeq Pty Ltd
0412 174 230
03 9017 2707

**Comment by SachaG** [comment]
Oh ok, sorry about this! The code was correct in the actual repo, which is
why I didn't realize where the mistake was until now. I'll fix it, thanks
for pointing it out!
