### ISSUE TITLE
Clarity - Wiring the data to our HTML with helpers

### ISSUE THREAD

**Issue by hippomoe** [DiscoverMeteor/book#73]
I may have missed something but in the section "Wiring the data to our HTML with helpers", won't the static data that was created in the previous template chapter still exist. It seems to be implied in the code listing for posts_list.js that the static data has been removed, but this comes after the "To get these posts into rendered HTML..." statement. I think having a statement about explicitly removing the array of static data from that file and noticing in the browser that even though the posts exist in the database they have not yet been wired up using the helpers, might be helpful. Again, I may have missed something that made this clear or I'm misunderstanding.

**Comment by SachaG** [comment]
I'm not sure if I understand what you mean completely, but there's two distinct sets of posts: the static `postsData` object we use in the Templates chapter, and the three posts we insert into the database to populate it in the Collections chapter. 

So the "To get these posts into rendered HTML..." statement refers to the database posts, not the Templates chapter's static data (which we've removed). 

Does that make things clearer?

**Comment by hippomoe** [comment]
I just didn't see where in the book it was mentioned before the "To get these posts into rendered HTML..." statement that the static data in posts_list.js should be removed. Was it stated somewhere before this section to remove it or is it just implied? I understood that I needed to remove it after reading the "Wiring the data to our HTML with helpers" section, but it seems that it should be explicitly stated before that section - maybe I missed it or maybe this confusion is just on my part.

**Comment by SachaG** [comment]
I've clarified this, thanks.
