### ISSUE TITLE
Installing meteorite

### ISSUE THREAD

**Issue by hippomoe** [DiscoverMeteor/book#74]
This is probably an unusual (unique) environment problem since I haven't seen it asked nor could I find any information when doing a web search, but I receive the following error: env -H No such file or directory  when executing sudo -H npm install -g meteorite. Any ideas on this issue?

**Comment by hippomoe** [comment]
This was a sudo alias issue. Here's the information that I used to resolve this problem. http://askubuntu.com/questions/183093/sudo-arguments-not-working  
I will leave this issue open and allow the authors to close it. It may be helpful to address this possible problem in the "Getting Started" chapter, but I think it's probably not a common case and the book doesn't need to cover uncommon problems. I left a comment on the book's online discussion section for the "Getting Started" chapter that provides the information for resolving this problem which is probably sufficient.

**Comment by tmeasday** [comment]
Thanks @hippomoe -- I'll (try to) remember this if I ever see it again.
