### ISSUE TITLE
Installing Meteor - password

### ISSUE THREAD

**Issue by CarlCarpenter** [DiscoverMeteor/book#75]
During Meteor install, when writing launcher script, I'm prompted for a password. Not sure which password this is, but it doesn't matter because when I try to type a password in the cursor doesn't move, then when I hit Enter it says it couldn't write the launcher script. Says to rerun the command, but that doesn't help.

I'm new to Mac. What do I do here?

**Comment by SachaG** [comment]
This would probably be your own admin user password (the one you filled in when installing Mac OS the first time). 

The cursor not moving is normal, for security reasons nothing shows up when you type passwords in the terminal.

**Comment by CarlCarpenter** [comment]
Hi Sacha, thanks very much for getting right back. Yes, I assumed it was my own pw, and also that the cursor not moving might be just for passwords, thanks for confirming, but I am entering the pw and it doesn't seem to make a difference. Here's what I'm seeing immediately after entering the pw.

cp: /usr/local/bin/meteor: No such file or directory

Couldn't write the launcher script. Please either:

  (1) Run the following as root:
        cp ~/.meteor/tools/latest/launch-meteor /usr/bin/meteor
  (2) Add ~/.meteor to your path, or
  (3) Rerun this command to try again.

Don't know how to do 1 or 2, so I'm stuck...

**Comment by SachaG** [comment]
I know it's been a while, but did you manage to sort this out? If you can't get Meteor to run locally, I suggest checking out http://nitrous.io, it's a great alternative.

**Comment by CarlCarpenter** [comment]
Yes, Sacha, thanks, I solved this shortly after posting the above. Actually replied in this thread I thought, so not sure why that reply is not here. Thanks for the suggestion, Nitrous looks very cool!
