### ISSUE TITLE
teaser version of book for training kids

### ISSUE THREAD

**Issue by jimmack1963** [DiscoverMeteor/book#77]
Hi.  I am a big fan.  When I read your book, as an experienced developer, I thought it did a great job of starting someone from nothing, and quickly seeing results.  You could get into the details, or keep just typing things and seeing 'magic'.  To me, meteor is a reboot of web development, and we are in the golden age of JS.

I've shown the first parts to a few young minimum wage workers I know, and they got very excited.  They both learned to type in EXACTLY what you tell them to, and they got to see the results, which they talked about with their friends for hours...

Would you consider releasing a free subset, which just shows the first few chapters of what to type, without the sidebars or too much explanation, to use as a teaser to get quick results and lure kids in?  

Thanks.  I have been teaching on my mac, but will soon have time to write up how a non programmer can sign up for the free resources necessary to get started and see results immediately.  Then, I feel like teaching meteor.

**Comment by SachaG** [comment]
We've actually been thinking about doing either this, or else coming out with a cheaper version of the book that wouldn't include the sidebars. 

I think we'll do one or the other soon :)

**Comment by jimmack1963** [comment]
Thanks.

**Comment by SachaG** [comment]
This is in the works, so I'll close this for now.

**Comment by jimmack1963** [comment]
Oh, a Thanksgiving present!  :)   

All I'm recommending is a little coloring book.  You wouldn't even need to rewrite anything, just a publish of the first few main sections, of just the magic, in coloring-book form.
