### ISSUE TITLE
Deploying to EC2

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#79]
These are the final steps from the book for deploying to EC2:
![screen shot 2013-09-05 at 10 41 39 am](https://f.cloud.github.com/assets/4665847/1090222/a5c24456-1652-11e3-94b5-aa9947c32c1a.png)

I get the following error messages: 
![screen shot 2013-09-05 at 10 43 36 am](https://f.cloud.github.com/assets/4665847/1090229/ce48c74c-1652-11e3-8ddb-1da91bcec2c2.png)

What am I doing wrong?

**Comment by tmeasday** [comment]
Are you using an old version of Meteorite?

**Comment by ghost** [comment]
![screen shot 2013-09-05 at 3 26 29 pm](https://f.cloud.github.com/assets/4665847/1092318/47f8976c-167a-11e3-94f3-0a7ffb6bcbc1.png)

**Comment by tmeasday** [comment]
Hi @ghost -- apologies, I missed your reply. 

This is in fact an error in the book, if you are bundling on the server, you either have to first run `mrt install`, or run `mrt bundle`, rather than `meteor bundle`. Fixing the book up now. Sorry again.
