### ISSUE TITLE
Reference to wrong file on http://book.discovermeteor.com/chapter/comments/

### ISSUE THREAD

**Issue by GiraffeSlacks** [DiscoverMeteor/book#8]
Hello,

The paragraph describing the final code change on http://book.discovermeteor.com/chapter/comments/ references the wrong file. The sentence says, "...helper from client/views/comments/comment.js, ..." but the codeblock (correctly) references "clients/views/posts/post_item.js."

**Comment by SachaG** [comment]
Thanks!
