### ISSUE TITLE
Meteor requires Node v0.8.24 or later

### ISSUE THREAD

**Issue by ee7klt** [DiscoverMeteor/book#85]
Got this error after pushing to Heroku. Any ideas on how to fix it?

**Comment by ee7klt** [comment]
OK, it looks like the version is hardcoded in the buildpack. Perhaps the authors should consider forking the buildpack with updated version number.

**Comment by SachaG** [comment]
I don't think that buildpack is still up to date. Maybe try other Meteor hosting options, like http://stackful.io for example?
