### ISSUE TITLE
2.5: what is the purpose of bundle?

### ISSUE THREAD

**Issue by ee7klt** [DiscoverMeteor/book#86]
it looks like the app is bundled in to a tarball, and then unzipped again in the directory above, which is the same as moving the app to a directory above. can someone please enlighten me as to the purpose of doing this?

**Comment by SachaG** [comment]
Bundling the app doesn't just create a tarball, it also transforms your Meteor app into a Node.js app. If you compare your app with the resulting extracted tarball you'll see that they're different.
