### ISSUE TITLE
data not loading after computer resume from sleep

### ISSUE THREAD

**Issue by serkandurusoy** [DiscoverMeteor/book#89]
I'm using windows 7 64bit and Chrome 29 and have the habbit of keeping discover meteor open and not shut down the computer

It seems that whenever I resume from sleep, the connection to the server is lost, nothing in the console but data is not loading. the outermost template (header, footer) is there and I see the spinner.

I hit reload and nothing happens. If I open up a new tab/window and browse to the same address, then I see the page with data.

Or sometimes if I wait long enough (more than a couple of minutes) data starts coming back in.

Again, nothing observed on the browser console.

**Comment by SachaG** [comment]
That's worrying, but it sounds more like a browser/Meteor issue than an issue with the book itself. I don't know if there's much we can do about it… Although I'll try to enable caching, maybe that'll help.
