### ISSUE TITLE
Router Screencast

### ISSUE THREAD

**Issue by rjsandman** [DiscoverMeteor/book#9]
Hello,

Just wanted to comment on "The Router" screencast.  I didn't see a place to comment directly on the screencast so I figured this was as good a place as any.  It is almost impossible to see the code in the screencast even when viewing in HD.  Is it possible to increase the quality of the video so the code can be followed?  It's a very informative screencast just can't really see the code.

Thanks,

Rob

**Comment by tmeasday** [comment]
Hi Rob,

I'm really sorry about that. It's actually the original picture quality, unfortunately my recording wasn't very good. 

At the moment I'm actively collaborating with Chris Mather (who wrote mini-pages) and a couple of others to come up with a new "super"-router; so rather than re-recording this video, I want to hold out until that is released (a couple of weeks) and then post a video on the new router.

I hope that you can figure out the contents of the video from the git repo that's attached. I'm really sorry about the poor quality.

Tom

**Comment by rjsandman** [comment]
Hi Tom,

 No problem.  I can use a little clarification on the third party apps if you don't mind.  The router is a third party add on for meteor, correct?  Is there a standard that meteor uses to keep these updated?  Is there any risk that building a web app with meteor and its add ons will eventually become out dated?  

Thanks,

Rob

**Comment by tmeasday** [comment]
Yes, this is correct.  

Right now it's all a little bit ad-hoc, and there is some risk of that happening, although they are (all?) open source and easily modified if it does come to that.

In the future the Meteor team (once they officially support 3rd party packages) want to make the process more certain for developers.

Tom

**Comment by rjsandman** [comment]
Thanks.  Oh by the way, I had posted a question on the book.discovermeteor.com site on the chapter regarding user accounts.  I didn't hear back so maybe I can ask you here.  I was curious to know why on the header where the sign up button is placed, when you resize the browser (make is smaller), the signup button disappears?  Is this due to bootstrap css?  Or something to do with Meteor?  I tried adding a fluid class to the div but it didn't seem to change anything.

Thanks,

Rob

**Comment by tmeasday** [comment]
Hi Rob,  

Yes, I was going to let Sacha reply to that one :)

I'm not sure what it is exactly. It's either something in bootstrap or the builtin accounts-ui or both. I haven't really looked at the CSS of Microscope at all so I can't properly answer.

Tom

**Comment by rjsandman** [comment]
Thanks Tom.  

On a different note.  I am trying to get JW Player to work with meteor.js.  Is there anything special that needs to be done in order for the media to play?  I am trying to play an .mp3 in JW player on the microscope tutorial just to see if I can get it to work.  It doesn't seem to play the file though.  I have the file in the /public folder and I am using 'http://localhost:3000/name.mp3.  Any help would be appreciated.

Kindly,

Rob Sand

**Comment by tmeasday** [comment]
Does going to the link directly not work?

**Comment by rjsandman** [comment]
No it doesn't.  

I am calling JW player in the <head> and using the normal javascript to add the player to a div with the same "id"  and nothing is showing.  I have tried to call files locally as well as links being hosted on a server and still cannot get anything to show.

Thanks,

Rob

**Comment by rjsandman** [comment]
Here is my main.html file:

<head>
  <title>Microscope</title>

  <script src="http://jwpsrv.com/library/7fD0gL19EeKgRxIxOQulpA.js"></script>

</head>
<body>
  <div id='my-video'></div>

<script type='text/javascript'>
    jwplayer('my-video').setup({
        file: 'http://localhost:3000/01TodayIsTheDay.mp3',
        width: '640',
        height: '360'
    });
</script>

</script>
</body>

I have also tried file: 'http://localhost:3000/public/01TodayIsTheDay.mp3',

and cannot get the file to play.

Thanks,

Rob

**Comment by tmeasday** [comment]
Right, but what do you see if you browse directly to that URL?  

e.g. if you type  

curl "http://localhost:3000/public/01TodayIsTheDay.mp3 (http://localhost:3000/public/01TodayIsTheDay.mp3')"

On the commandline?

**Comment by rjsandman** [comment]
The music plays in the browser.

**Comment by tmeasday** [comment]
Right, so the file is hosted by your meteor server properly.  

So now you just need to figure out how to get the JS library to work properly..

**Comment by rjsandman** [comment]
Any thoughts on how to make that happen?

**Comment by tmeasday** [comment]
Not really, I don't know anything about the jwplayer library, sorry!

**Comment by jamesdwilson** [comment]
It's been two months, you said you'd have the super-router screencast done in "couple of weeks". Any update on this?

Thank you

**Comment by tmeasday** [comment]
Fair enough!

We're in the final stages of polishing up a release of the new router at the moment, so the video should follow closely behind. Appreciate your patience, sorry about this. (As always) things turned out to be more difficult than we anticipated.

**Comment by jamesdwilson** [comment]
Thanks for the update! Love everything else! Keep up the great work. :)

**Comment by SachaG** [comment]
The new Router is coming soon :)

https://www.youtube.com/watch?v=Ep2lpzcXR0g

**Comment by SachaG** [comment]
The new router video is now live.
