### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by rjsandman** [DiscoverMeteor/book#90]
Hello,

I am in the routing chapter and for some reason I get this for a url:

http://localhost:3000/praisers/ObjectID(%225230c222de7169b20577ea95%22)

I have changed a couple of the template names so you will see praisers instead of posts.  But for some reason the Id is not showing up properly, this renders the page but  does not display my individual template.  Any idea why it is showing ObjectID in the url?

**Comment by tmeasday** [comment]
Perhaps the object was inserted to Mongo outside of Meteor (and Mongo gave it that object ID?)
