### ISSUE TITLE
Creating Posts, posts.js needs allow()

### ISSUE THREAD

**Issue by brotherbill** [DiscoverMeteor/book#91]
Near the bottom of the Creating Posts section, it shows all the code, but there is a part removed that is necessary after Posts = new Meteor.Collection('posts');

Please add in:
Posts.allow({
   insert: function(userId, doc) {
   // only allow posting if you are logged in
   return !! userId;
   }
});

Without this added code, user is denied permission to post.

**Comment by MikeDepies** [comment]
Isn't the post added via a server method? In that case, the server doesn't care about allows and denys. I believe that this is to be true.

**Comment by SachaG** [comment]
@MikeDepies you're correct, allow/denys only apply for client-side operations. 

@brotherbill I'll close this for now, unless you're still not able to insert new posts?
