### ISSUE TITLE
Templates typo

### ISSUE THREAD

**Issue by brotherbill** [DiscoverMeteor/book#94]
After Commit 3-1,
  you write: 
      Defining the posts helper means it is now available for our template to use:

I believe that you mean:
      Defining the postsList helper means it is now available for our template to use:

In this code shown below, the postsList in the name of the helper.
posts is simple an exposed value.

Template.postsList.helpers({
  posts: postsData
});

As a newbie, please double check this, as this is very early in the book.
But I think I'm right, and clarity counts, especially for newbies.

**Comment by SachaG** [comment]
No, `postsList` is the name of the template, and `posts` is the name of the helper. So the book is correct as far as I can tell.
