### ISSUE TITLE
Templates - The Value of "this", explanation of javascript magic

### ISSUE THREAD

**Issue by brotherbill** [DiscoverMeteor/book#95]
Sorry, this is in CoffeeScript, but you can translate it back into Javascript.
You may want to add this in for those that can't follow the magic.

```
Template.postItem.helpers 
  domain: ->
    a = document.createElement("a")
    a.href = @url
    a.hostname
```

The value of this (in Javascript) or @ (in CoffeeScript)
is an array element from postsData, so @url is the value of the key url for the current array element.

So line by line, here is the play by play
  Line 3: create an empty, unattached anchor tag object
  Line 4: The a.href property is assigned the value of @url.  Ex:  "http://sachagreif.com/introducing-telescope/"
  Line 5: Since this is the last line of the coffee script, this value will be returned
             The a object has a property called hostname that contains just the host name, without extraneous baggage.
             Return the extracted hostname, which includes whatever comes after the http:// and up to the next / or ?
             This includes www. as well as .com, but not / or ?
             In this example, we first return "sachagreif.com", which is displayed on the right of the {{title}}

**Comment by tmeasday** [comment]
I edited the issue description to be a bit more readable :)

**Comment by SachaG** [comment]
Thanks, I clarified that part.
