### ISSUE TITLE
p 145 (after commit 11-3), shouldn't the command in the browser console have the arguement {read: false} ?}

### ISSUE THREAD

**Issue by shafiquejamal** [DiscoverMeteor/book#96]
Shouldn't:

Notifications.find().count();

be 

Notifications.find({read: false}).count();

since we are only looking for notifications that have not been read? 

Also, some typos:

p148
"that decides if something..."
should be
"that decides whether something..."

p149
"So any data that is gathered by a helpers..."
should be
"So any data that is gathered by helpers..."

p150
"with a couple special methods."
should be
"with a couple of special methods."

**Comment by SachaG** [comment]
In this case I think we're just trying to check that different users see different notifications. So it doesn't really matter if they're read or not. 

And thanks for the corrections :)
