### ISSUE TITLE
Iron-Routing and Hot code reload

### ISSUE THREAD

**Issue by brotherbill** [DiscoverMeteor/book#98]
For Iron-Routing, do we need to do anything special to support Hot code reload?

**Comment by SachaG** [comment]
I don't think so, what do you mean exactly?

**Comment by brotherbill** [comment]
If we want to support Hot Code Reload, and are using Iron-Routing, which doesn't use Session variables,
do we need to set Session variables ourselves to be nice, and support Hot Code Reload?
----- Original Message -----

**Comment by SachaG** [comment]
No, since IronRouter doesn't use Session variables at all. Of course, if you're using those Session variables elsewhere in the app for something else, then that's another matter.
