### ISSUE TITLE
Screenshot in middle out of sequence

### ISSUE THREAD

**Issue by brotherbill** [DiscoverMeteor/book#99]
The Screenshot shows Sign Up / In with Username, but the default is Email.  So Email is what will show if they follow your instructions exactly.  Only after following the next section will the Email change to UserName.

Newbies can get confused when they follow your directions, and don't get expected results.  Newbies tend to blame themselves for somehow missing a step.

**Comment by SachaG** [comment]
Sorry, which screenshot?

**Comment by brotherbill** [comment]
On page http://book.discovermeteor.com/chapter/adding-users/
there is only one screenshot, in the middle of the page, vertically.
Just above Commit 6-1.
----- Original Message -----

**Comment by SachaG** [comment]
OK got it, thanks for pointing it out! We'll fix that when we get a chance to redo that screenshot.
